/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package net.explorys.samhat.z12.r837;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class X837Pro_2430_SVD03_CompositeMedicalProcedureIdentifier extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"X837Pro_2430_SVD03_CompositeMedicalProcedureIdentifier\",\"namespace\":\"net.explorys.samhat.z12.r837\",\"fields\":[{\"name\":\"_2430SVD0301ProductOrServiceIDQualifier\",\"type\":\"string\"},{\"name\":\"_2430SVD0302ProcedureCode\",\"type\":\"string\"},{\"name\":\"_2430SVD0303ProcedureModifier\",\"type\":\"string\"},{\"name\":\"_2430SVD0304ProcedureModifier\",\"type\":\"string\"},{\"name\":\"_2430SVD0305ProcedureModifier\",\"type\":\"string\"},{\"name\":\"_2430SVD0306ProcedureModifier\",\"type\":\"string\"},{\"name\":\"_2430SVD0307ProcedureCodeDescription\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence _2430SVD0301ProductOrServiceIDQualifier;
  @Deprecated public java.lang.CharSequence _2430SVD0302ProcedureCode;
  @Deprecated public java.lang.CharSequence _2430SVD0303ProcedureModifier;
  @Deprecated public java.lang.CharSequence _2430SVD0304ProcedureModifier;
  @Deprecated public java.lang.CharSequence _2430SVD0305ProcedureModifier;
  @Deprecated public java.lang.CharSequence _2430SVD0306ProcedureModifier;
  @Deprecated public java.lang.CharSequence _2430SVD0307ProcedureCodeDescription;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public X837Pro_2430_SVD03_CompositeMedicalProcedureIdentifier() {}

  /**
   * All-args constructor.
   */
  public X837Pro_2430_SVD03_CompositeMedicalProcedureIdentifier(java.lang.CharSequence _2430SVD0301ProductOrServiceIDQualifier, java.lang.CharSequence _2430SVD0302ProcedureCode, java.lang.CharSequence _2430SVD0303ProcedureModifier, java.lang.CharSequence _2430SVD0304ProcedureModifier, java.lang.CharSequence _2430SVD0305ProcedureModifier, java.lang.CharSequence _2430SVD0306ProcedureModifier, java.lang.CharSequence _2430SVD0307ProcedureCodeDescription) {
    this._2430SVD0301ProductOrServiceIDQualifier = _2430SVD0301ProductOrServiceIDQualifier;
    this._2430SVD0302ProcedureCode = _2430SVD0302ProcedureCode;
    this._2430SVD0303ProcedureModifier = _2430SVD0303ProcedureModifier;
    this._2430SVD0304ProcedureModifier = _2430SVD0304ProcedureModifier;
    this._2430SVD0305ProcedureModifier = _2430SVD0305ProcedureModifier;
    this._2430SVD0306ProcedureModifier = _2430SVD0306ProcedureModifier;
    this._2430SVD0307ProcedureCodeDescription = _2430SVD0307ProcedureCodeDescription;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return _2430SVD0301ProductOrServiceIDQualifier;
    case 1: return _2430SVD0302ProcedureCode;
    case 2: return _2430SVD0303ProcedureModifier;
    case 3: return _2430SVD0304ProcedureModifier;
    case 4: return _2430SVD0305ProcedureModifier;
    case 5: return _2430SVD0306ProcedureModifier;
    case 6: return _2430SVD0307ProcedureCodeDescription;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: _2430SVD0301ProductOrServiceIDQualifier = (java.lang.CharSequence)value$; break;
    case 1: _2430SVD0302ProcedureCode = (java.lang.CharSequence)value$; break;
    case 2: _2430SVD0303ProcedureModifier = (java.lang.CharSequence)value$; break;
    case 3: _2430SVD0304ProcedureModifier = (java.lang.CharSequence)value$; break;
    case 4: _2430SVD0305ProcedureModifier = (java.lang.CharSequence)value$; break;
    case 5: _2430SVD0306ProcedureModifier = (java.lang.CharSequence)value$; break;
    case 6: _2430SVD0307ProcedureCodeDescription = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the '_2430SVD0301ProductOrServiceIDQualifier' field.
   */
  public java.lang.CharSequence get2430SVD0301ProductOrServiceIDQualifier$1() {
    return _2430SVD0301ProductOrServiceIDQualifier;
  }

  /**
   * Sets the value of the '_2430SVD0301ProductOrServiceIDQualifier' field.
   * @param value the value to set.
   */
  public void set2430SVD0301ProductOrServiceIDQualifier$1(java.lang.CharSequence value) {
    this._2430SVD0301ProductOrServiceIDQualifier = value;
  }

  /**
   * Gets the value of the '_2430SVD0302ProcedureCode' field.
   */
  public java.lang.CharSequence get2430SVD0302ProcedureCode$1() {
    return _2430SVD0302ProcedureCode;
  }

  /**
   * Sets the value of the '_2430SVD0302ProcedureCode' field.
   * @param value the value to set.
   */
  public void set2430SVD0302ProcedureCode$1(java.lang.CharSequence value) {
    this._2430SVD0302ProcedureCode = value;
  }

  /**
   * Gets the value of the '_2430SVD0303ProcedureModifier' field.
   */
  public java.lang.CharSequence get2430SVD0303ProcedureModifier$1() {
    return _2430SVD0303ProcedureModifier;
  }

  /**
   * Sets the value of the '_2430SVD0303ProcedureModifier' field.
   * @param value the value to set.
   */
  public void set2430SVD0303ProcedureModifier$1(java.lang.CharSequence value) {
    this._2430SVD0303ProcedureModifier = value;
  }

  /**
   * Gets the value of the '_2430SVD0304ProcedureModifier' field.
   */
  public java.lang.CharSequence get2430SVD0304ProcedureModifier$1() {
    return _2430SVD0304ProcedureModifier;
  }

  /**
   * Sets the value of the '_2430SVD0304ProcedureModifier' field.
   * @param value the value to set.
   */
  public void set2430SVD0304ProcedureModifier$1(java.lang.CharSequence value) {
    this._2430SVD0304ProcedureModifier = value;
  }

  /**
   * Gets the value of the '_2430SVD0305ProcedureModifier' field.
   */
  public java.lang.CharSequence get2430SVD0305ProcedureModifier$1() {
    return _2430SVD0305ProcedureModifier;
  }

  /**
   * Sets the value of the '_2430SVD0305ProcedureModifier' field.
   * @param value the value to set.
   */
  public void set2430SVD0305ProcedureModifier$1(java.lang.CharSequence value) {
    this._2430SVD0305ProcedureModifier = value;
  }

  /**
   * Gets the value of the '_2430SVD0306ProcedureModifier' field.
   */
  public java.lang.CharSequence get2430SVD0306ProcedureModifier$1() {
    return _2430SVD0306ProcedureModifier;
  }

  /**
   * Sets the value of the '_2430SVD0306ProcedureModifier' field.
   * @param value the value to set.
   */
  public void set2430SVD0306ProcedureModifier$1(java.lang.CharSequence value) {
    this._2430SVD0306ProcedureModifier = value;
  }

  /**
   * Gets the value of the '_2430SVD0307ProcedureCodeDescription' field.
   */
  public java.lang.CharSequence get2430SVD0307ProcedureCodeDescription$1() {
    return _2430SVD0307ProcedureCodeDescription;
  }

  /**
   * Sets the value of the '_2430SVD0307ProcedureCodeDescription' field.
   * @param value the value to set.
   */
  public void set2430SVD0307ProcedureCodeDescription$1(java.lang.CharSequence value) {
    this._2430SVD0307ProcedureCodeDescription = value;
  }

  /** Creates a new X837Pro_2430_SVD03_CompositeMedicalProcedureIdentifier RecordBuilder */
  public static net.explorys.samhat.z12.r837.X837Pro_2430_SVD03_CompositeMedicalProcedureIdentifier.Builder newBuilder() {
    return new net.explorys.samhat.z12.r837.X837Pro_2430_SVD03_CompositeMedicalProcedureIdentifier.Builder();
  }
  
  /** Creates a new X837Pro_2430_SVD03_CompositeMedicalProcedureIdentifier RecordBuilder by copying an existing Builder */
  public static net.explorys.samhat.z12.r837.X837Pro_2430_SVD03_CompositeMedicalProcedureIdentifier.Builder newBuilder(net.explorys.samhat.z12.r837.X837Pro_2430_SVD03_CompositeMedicalProcedureIdentifier.Builder other) {
    return new net.explorys.samhat.z12.r837.X837Pro_2430_SVD03_CompositeMedicalProcedureIdentifier.Builder(other);
  }
  
  /** Creates a new X837Pro_2430_SVD03_CompositeMedicalProcedureIdentifier RecordBuilder by copying an existing X837Pro_2430_SVD03_CompositeMedicalProcedureIdentifier instance */
  public static net.explorys.samhat.z12.r837.X837Pro_2430_SVD03_CompositeMedicalProcedureIdentifier.Builder newBuilder(net.explorys.samhat.z12.r837.X837Pro_2430_SVD03_CompositeMedicalProcedureIdentifier other) {
    return new net.explorys.samhat.z12.r837.X837Pro_2430_SVD03_CompositeMedicalProcedureIdentifier.Builder(other);
  }
  
  /**
   * RecordBuilder for X837Pro_2430_SVD03_CompositeMedicalProcedureIdentifier instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<X837Pro_2430_SVD03_CompositeMedicalProcedureIdentifier>
    implements org.apache.avro.data.RecordBuilder<X837Pro_2430_SVD03_CompositeMedicalProcedureIdentifier> {

    private java.lang.CharSequence _2430SVD0301ProductOrServiceIDQualifier;
    private java.lang.CharSequence _2430SVD0302ProcedureCode;
    private java.lang.CharSequence _2430SVD0303ProcedureModifier;
    private java.lang.CharSequence _2430SVD0304ProcedureModifier;
    private java.lang.CharSequence _2430SVD0305ProcedureModifier;
    private java.lang.CharSequence _2430SVD0306ProcedureModifier;
    private java.lang.CharSequence _2430SVD0307ProcedureCodeDescription;

    /** Creates a new Builder */
    private Builder() {
      super(net.explorys.samhat.z12.r837.X837Pro_2430_SVD03_CompositeMedicalProcedureIdentifier.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(net.explorys.samhat.z12.r837.X837Pro_2430_SVD03_CompositeMedicalProcedureIdentifier.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other._2430SVD0301ProductOrServiceIDQualifier)) {
        this._2430SVD0301ProductOrServiceIDQualifier = data().deepCopy(fields()[0].schema(), other._2430SVD0301ProductOrServiceIDQualifier);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other._2430SVD0302ProcedureCode)) {
        this._2430SVD0302ProcedureCode = data().deepCopy(fields()[1].schema(), other._2430SVD0302ProcedureCode);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other._2430SVD0303ProcedureModifier)) {
        this._2430SVD0303ProcedureModifier = data().deepCopy(fields()[2].schema(), other._2430SVD0303ProcedureModifier);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other._2430SVD0304ProcedureModifier)) {
        this._2430SVD0304ProcedureModifier = data().deepCopy(fields()[3].schema(), other._2430SVD0304ProcedureModifier);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other._2430SVD0305ProcedureModifier)) {
        this._2430SVD0305ProcedureModifier = data().deepCopy(fields()[4].schema(), other._2430SVD0305ProcedureModifier);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other._2430SVD0306ProcedureModifier)) {
        this._2430SVD0306ProcedureModifier = data().deepCopy(fields()[5].schema(), other._2430SVD0306ProcedureModifier);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other._2430SVD0307ProcedureCodeDescription)) {
        this._2430SVD0307ProcedureCodeDescription = data().deepCopy(fields()[6].schema(), other._2430SVD0307ProcedureCodeDescription);
        fieldSetFlags()[6] = true;
      }
    }
    
    /** Creates a Builder by copying an existing X837Pro_2430_SVD03_CompositeMedicalProcedureIdentifier instance */
    private Builder(net.explorys.samhat.z12.r837.X837Pro_2430_SVD03_CompositeMedicalProcedureIdentifier other) {
            super(net.explorys.samhat.z12.r837.X837Pro_2430_SVD03_CompositeMedicalProcedureIdentifier.SCHEMA$);
      if (isValidValue(fields()[0], other._2430SVD0301ProductOrServiceIDQualifier)) {
        this._2430SVD0301ProductOrServiceIDQualifier = data().deepCopy(fields()[0].schema(), other._2430SVD0301ProductOrServiceIDQualifier);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other._2430SVD0302ProcedureCode)) {
        this._2430SVD0302ProcedureCode = data().deepCopy(fields()[1].schema(), other._2430SVD0302ProcedureCode);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other._2430SVD0303ProcedureModifier)) {
        this._2430SVD0303ProcedureModifier = data().deepCopy(fields()[2].schema(), other._2430SVD0303ProcedureModifier);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other._2430SVD0304ProcedureModifier)) {
        this._2430SVD0304ProcedureModifier = data().deepCopy(fields()[3].schema(), other._2430SVD0304ProcedureModifier);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other._2430SVD0305ProcedureModifier)) {
        this._2430SVD0305ProcedureModifier = data().deepCopy(fields()[4].schema(), other._2430SVD0305ProcedureModifier);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other._2430SVD0306ProcedureModifier)) {
        this._2430SVD0306ProcedureModifier = data().deepCopy(fields()[5].schema(), other._2430SVD0306ProcedureModifier);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other._2430SVD0307ProcedureCodeDescription)) {
        this._2430SVD0307ProcedureCodeDescription = data().deepCopy(fields()[6].schema(), other._2430SVD0307ProcedureCodeDescription);
        fieldSetFlags()[6] = true;
      }
    }

    /** Gets the value of the '_2430SVD0301ProductOrServiceIDQualifier' field */
    public java.lang.CharSequence get2430SVD0301ProductOrServiceIDQualifier$1() {
      return _2430SVD0301ProductOrServiceIDQualifier;
    }
    
    /** Sets the value of the '_2430SVD0301ProductOrServiceIDQualifier' field */
    public net.explorys.samhat.z12.r837.X837Pro_2430_SVD03_CompositeMedicalProcedureIdentifier.Builder set2430SVD0301ProductOrServiceIDQualifier$1(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this._2430SVD0301ProductOrServiceIDQualifier = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the '_2430SVD0301ProductOrServiceIDQualifier' field has been set */
    public boolean has2430SVD0301ProductOrServiceIDQualifier$1() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the '_2430SVD0301ProductOrServiceIDQualifier' field */
    public net.explorys.samhat.z12.r837.X837Pro_2430_SVD03_CompositeMedicalProcedureIdentifier.Builder clear2430SVD0301ProductOrServiceIDQualifier$1() {
      _2430SVD0301ProductOrServiceIDQualifier = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the '_2430SVD0302ProcedureCode' field */
    public java.lang.CharSequence get2430SVD0302ProcedureCode$1() {
      return _2430SVD0302ProcedureCode;
    }
    
    /** Sets the value of the '_2430SVD0302ProcedureCode' field */
    public net.explorys.samhat.z12.r837.X837Pro_2430_SVD03_CompositeMedicalProcedureIdentifier.Builder set2430SVD0302ProcedureCode$1(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this._2430SVD0302ProcedureCode = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the '_2430SVD0302ProcedureCode' field has been set */
    public boolean has2430SVD0302ProcedureCode$1() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the '_2430SVD0302ProcedureCode' field */
    public net.explorys.samhat.z12.r837.X837Pro_2430_SVD03_CompositeMedicalProcedureIdentifier.Builder clear2430SVD0302ProcedureCode$1() {
      _2430SVD0302ProcedureCode = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the '_2430SVD0303ProcedureModifier' field */
    public java.lang.CharSequence get2430SVD0303ProcedureModifier$1() {
      return _2430SVD0303ProcedureModifier;
    }
    
    /** Sets the value of the '_2430SVD0303ProcedureModifier' field */
    public net.explorys.samhat.z12.r837.X837Pro_2430_SVD03_CompositeMedicalProcedureIdentifier.Builder set2430SVD0303ProcedureModifier$1(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this._2430SVD0303ProcedureModifier = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the '_2430SVD0303ProcedureModifier' field has been set */
    public boolean has2430SVD0303ProcedureModifier$1() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the '_2430SVD0303ProcedureModifier' field */
    public net.explorys.samhat.z12.r837.X837Pro_2430_SVD03_CompositeMedicalProcedureIdentifier.Builder clear2430SVD0303ProcedureModifier$1() {
      _2430SVD0303ProcedureModifier = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the '_2430SVD0304ProcedureModifier' field */
    public java.lang.CharSequence get2430SVD0304ProcedureModifier$1() {
      return _2430SVD0304ProcedureModifier;
    }
    
    /** Sets the value of the '_2430SVD0304ProcedureModifier' field */
    public net.explorys.samhat.z12.r837.X837Pro_2430_SVD03_CompositeMedicalProcedureIdentifier.Builder set2430SVD0304ProcedureModifier$1(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this._2430SVD0304ProcedureModifier = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the '_2430SVD0304ProcedureModifier' field has been set */
    public boolean has2430SVD0304ProcedureModifier$1() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the '_2430SVD0304ProcedureModifier' field */
    public net.explorys.samhat.z12.r837.X837Pro_2430_SVD03_CompositeMedicalProcedureIdentifier.Builder clear2430SVD0304ProcedureModifier$1() {
      _2430SVD0304ProcedureModifier = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the '_2430SVD0305ProcedureModifier' field */
    public java.lang.CharSequence get2430SVD0305ProcedureModifier$1() {
      return _2430SVD0305ProcedureModifier;
    }
    
    /** Sets the value of the '_2430SVD0305ProcedureModifier' field */
    public net.explorys.samhat.z12.r837.X837Pro_2430_SVD03_CompositeMedicalProcedureIdentifier.Builder set2430SVD0305ProcedureModifier$1(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this._2430SVD0305ProcedureModifier = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the '_2430SVD0305ProcedureModifier' field has been set */
    public boolean has2430SVD0305ProcedureModifier$1() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the '_2430SVD0305ProcedureModifier' field */
    public net.explorys.samhat.z12.r837.X837Pro_2430_SVD03_CompositeMedicalProcedureIdentifier.Builder clear2430SVD0305ProcedureModifier$1() {
      _2430SVD0305ProcedureModifier = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the '_2430SVD0306ProcedureModifier' field */
    public java.lang.CharSequence get2430SVD0306ProcedureModifier$1() {
      return _2430SVD0306ProcedureModifier;
    }
    
    /** Sets the value of the '_2430SVD0306ProcedureModifier' field */
    public net.explorys.samhat.z12.r837.X837Pro_2430_SVD03_CompositeMedicalProcedureIdentifier.Builder set2430SVD0306ProcedureModifier$1(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this._2430SVD0306ProcedureModifier = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the '_2430SVD0306ProcedureModifier' field has been set */
    public boolean has2430SVD0306ProcedureModifier$1() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the '_2430SVD0306ProcedureModifier' field */
    public net.explorys.samhat.z12.r837.X837Pro_2430_SVD03_CompositeMedicalProcedureIdentifier.Builder clear2430SVD0306ProcedureModifier$1() {
      _2430SVD0306ProcedureModifier = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the '_2430SVD0307ProcedureCodeDescription' field */
    public java.lang.CharSequence get2430SVD0307ProcedureCodeDescription$1() {
      return _2430SVD0307ProcedureCodeDescription;
    }
    
    /** Sets the value of the '_2430SVD0307ProcedureCodeDescription' field */
    public net.explorys.samhat.z12.r837.X837Pro_2430_SVD03_CompositeMedicalProcedureIdentifier.Builder set2430SVD0307ProcedureCodeDescription$1(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this._2430SVD0307ProcedureCodeDescription = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the '_2430SVD0307ProcedureCodeDescription' field has been set */
    public boolean has2430SVD0307ProcedureCodeDescription$1() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the '_2430SVD0307ProcedureCodeDescription' field */
    public net.explorys.samhat.z12.r837.X837Pro_2430_SVD03_CompositeMedicalProcedureIdentifier.Builder clear2430SVD0307ProcedureCodeDescription$1() {
      _2430SVD0307ProcedureCodeDescription = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    public X837Pro_2430_SVD03_CompositeMedicalProcedureIdentifier build() {
      try {
        X837Pro_2430_SVD03_CompositeMedicalProcedureIdentifier record = new X837Pro_2430_SVD03_CompositeMedicalProcedureIdentifier();
        record._2430SVD0301ProductOrServiceIDQualifier = fieldSetFlags()[0] ? this._2430SVD0301ProductOrServiceIDQualifier : (java.lang.CharSequence) defaultValue(fields()[0]);
        record._2430SVD0302ProcedureCode = fieldSetFlags()[1] ? this._2430SVD0302ProcedureCode : (java.lang.CharSequence) defaultValue(fields()[1]);
        record._2430SVD0303ProcedureModifier = fieldSetFlags()[2] ? this._2430SVD0303ProcedureModifier : (java.lang.CharSequence) defaultValue(fields()[2]);
        record._2430SVD0304ProcedureModifier = fieldSetFlags()[3] ? this._2430SVD0304ProcedureModifier : (java.lang.CharSequence) defaultValue(fields()[3]);
        record._2430SVD0305ProcedureModifier = fieldSetFlags()[4] ? this._2430SVD0305ProcedureModifier : (java.lang.CharSequence) defaultValue(fields()[4]);
        record._2430SVD0306ProcedureModifier = fieldSetFlags()[5] ? this._2430SVD0306ProcedureModifier : (java.lang.CharSequence) defaultValue(fields()[5]);
        record._2430SVD0307ProcedureCodeDescription = fieldSetFlags()[6] ? this._2430SVD0307ProcedureCodeDescription : (java.lang.CharSequence) defaultValue(fields()[6]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
