/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package net.explorys.samhat.z12.r837;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class X837Ins_1000A_NM1_SubmitterName extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"X837Ins_1000A_NM1_SubmitterName\",\"namespace\":\"net.explorys.samhat.z12.r837\",\"fields\":[{\"name\":\"_1000ANM101EntityIdentifierCode\",\"type\":\"string\"},{\"name\":\"_1000ANM102EntityTypeQualifier\",\"type\":\"string\"},{\"name\":\"_1000ANM103SubmitterLastOrOrganizationName\",\"type\":\"string\"},{\"name\":\"_1000ANM104SubmitterFirstName\",\"type\":\"string\"},{\"name\":\"_1000ANM105SubmitterMiddleName\",\"type\":\"string\"},{\"name\":\"_1000ANM108IdentificationCodeQualifier\",\"type\":\"string\"},{\"name\":\"_1000ANM109SubmitterIdentifier\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence _1000ANM101EntityIdentifierCode;
  @Deprecated public java.lang.CharSequence _1000ANM102EntityTypeQualifier;
  @Deprecated public java.lang.CharSequence _1000ANM103SubmitterLastOrOrganizationName;
  @Deprecated public java.lang.CharSequence _1000ANM104SubmitterFirstName;
  @Deprecated public java.lang.CharSequence _1000ANM105SubmitterMiddleName;
  @Deprecated public java.lang.CharSequence _1000ANM108IdentificationCodeQualifier;
  @Deprecated public java.lang.CharSequence _1000ANM109SubmitterIdentifier;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public X837Ins_1000A_NM1_SubmitterName() {}

  /**
   * All-args constructor.
   */
  public X837Ins_1000A_NM1_SubmitterName(java.lang.CharSequence _1000ANM101EntityIdentifierCode, java.lang.CharSequence _1000ANM102EntityTypeQualifier, java.lang.CharSequence _1000ANM103SubmitterLastOrOrganizationName, java.lang.CharSequence _1000ANM104SubmitterFirstName, java.lang.CharSequence _1000ANM105SubmitterMiddleName, java.lang.CharSequence _1000ANM108IdentificationCodeQualifier, java.lang.CharSequence _1000ANM109SubmitterIdentifier) {
    this._1000ANM101EntityIdentifierCode = _1000ANM101EntityIdentifierCode;
    this._1000ANM102EntityTypeQualifier = _1000ANM102EntityTypeQualifier;
    this._1000ANM103SubmitterLastOrOrganizationName = _1000ANM103SubmitterLastOrOrganizationName;
    this._1000ANM104SubmitterFirstName = _1000ANM104SubmitterFirstName;
    this._1000ANM105SubmitterMiddleName = _1000ANM105SubmitterMiddleName;
    this._1000ANM108IdentificationCodeQualifier = _1000ANM108IdentificationCodeQualifier;
    this._1000ANM109SubmitterIdentifier = _1000ANM109SubmitterIdentifier;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return _1000ANM101EntityIdentifierCode;
    case 1: return _1000ANM102EntityTypeQualifier;
    case 2: return _1000ANM103SubmitterLastOrOrganizationName;
    case 3: return _1000ANM104SubmitterFirstName;
    case 4: return _1000ANM105SubmitterMiddleName;
    case 5: return _1000ANM108IdentificationCodeQualifier;
    case 6: return _1000ANM109SubmitterIdentifier;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: _1000ANM101EntityIdentifierCode = (java.lang.CharSequence)value$; break;
    case 1: _1000ANM102EntityTypeQualifier = (java.lang.CharSequence)value$; break;
    case 2: _1000ANM103SubmitterLastOrOrganizationName = (java.lang.CharSequence)value$; break;
    case 3: _1000ANM104SubmitterFirstName = (java.lang.CharSequence)value$; break;
    case 4: _1000ANM105SubmitterMiddleName = (java.lang.CharSequence)value$; break;
    case 5: _1000ANM108IdentificationCodeQualifier = (java.lang.CharSequence)value$; break;
    case 6: _1000ANM109SubmitterIdentifier = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the '_1000ANM101EntityIdentifierCode' field.
   */
  public java.lang.CharSequence get1000ANM101EntityIdentifierCode$1() {
    return _1000ANM101EntityIdentifierCode;
  }

  /**
   * Sets the value of the '_1000ANM101EntityIdentifierCode' field.
   * @param value the value to set.
   */
  public void set1000ANM101EntityIdentifierCode$1(java.lang.CharSequence value) {
    this._1000ANM101EntityIdentifierCode = value;
  }

  /**
   * Gets the value of the '_1000ANM102EntityTypeQualifier' field.
   */
  public java.lang.CharSequence get1000ANM102EntityTypeQualifier$1() {
    return _1000ANM102EntityTypeQualifier;
  }

  /**
   * Sets the value of the '_1000ANM102EntityTypeQualifier' field.
   * @param value the value to set.
   */
  public void set1000ANM102EntityTypeQualifier$1(java.lang.CharSequence value) {
    this._1000ANM102EntityTypeQualifier = value;
  }

  /**
   * Gets the value of the '_1000ANM103SubmitterLastOrOrganizationName' field.
   */
  public java.lang.CharSequence get1000ANM103SubmitterLastOrOrganizationName$1() {
    return _1000ANM103SubmitterLastOrOrganizationName;
  }

  /**
   * Sets the value of the '_1000ANM103SubmitterLastOrOrganizationName' field.
   * @param value the value to set.
   */
  public void set1000ANM103SubmitterLastOrOrganizationName$1(java.lang.CharSequence value) {
    this._1000ANM103SubmitterLastOrOrganizationName = value;
  }

  /**
   * Gets the value of the '_1000ANM104SubmitterFirstName' field.
   */
  public java.lang.CharSequence get1000ANM104SubmitterFirstName$1() {
    return _1000ANM104SubmitterFirstName;
  }

  /**
   * Sets the value of the '_1000ANM104SubmitterFirstName' field.
   * @param value the value to set.
   */
  public void set1000ANM104SubmitterFirstName$1(java.lang.CharSequence value) {
    this._1000ANM104SubmitterFirstName = value;
  }

  /**
   * Gets the value of the '_1000ANM105SubmitterMiddleName' field.
   */
  public java.lang.CharSequence get1000ANM105SubmitterMiddleName$1() {
    return _1000ANM105SubmitterMiddleName;
  }

  /**
   * Sets the value of the '_1000ANM105SubmitterMiddleName' field.
   * @param value the value to set.
   */
  public void set1000ANM105SubmitterMiddleName$1(java.lang.CharSequence value) {
    this._1000ANM105SubmitterMiddleName = value;
  }

  /**
   * Gets the value of the '_1000ANM108IdentificationCodeQualifier' field.
   */
  public java.lang.CharSequence get1000ANM108IdentificationCodeQualifier$1() {
    return _1000ANM108IdentificationCodeQualifier;
  }

  /**
   * Sets the value of the '_1000ANM108IdentificationCodeQualifier' field.
   * @param value the value to set.
   */
  public void set1000ANM108IdentificationCodeQualifier$1(java.lang.CharSequence value) {
    this._1000ANM108IdentificationCodeQualifier = value;
  }

  /**
   * Gets the value of the '_1000ANM109SubmitterIdentifier' field.
   */
  public java.lang.CharSequence get1000ANM109SubmitterIdentifier$1() {
    return _1000ANM109SubmitterIdentifier;
  }

  /**
   * Sets the value of the '_1000ANM109SubmitterIdentifier' field.
   * @param value the value to set.
   */
  public void set1000ANM109SubmitterIdentifier$1(java.lang.CharSequence value) {
    this._1000ANM109SubmitterIdentifier = value;
  }

  /** Creates a new X837Ins_1000A_NM1_SubmitterName RecordBuilder */
  public static net.explorys.samhat.z12.r837.X837Ins_1000A_NM1_SubmitterName.Builder newBuilder() {
    return new net.explorys.samhat.z12.r837.X837Ins_1000A_NM1_SubmitterName.Builder();
  }
  
  /** Creates a new X837Ins_1000A_NM1_SubmitterName RecordBuilder by copying an existing Builder */
  public static net.explorys.samhat.z12.r837.X837Ins_1000A_NM1_SubmitterName.Builder newBuilder(net.explorys.samhat.z12.r837.X837Ins_1000A_NM1_SubmitterName.Builder other) {
    return new net.explorys.samhat.z12.r837.X837Ins_1000A_NM1_SubmitterName.Builder(other);
  }
  
  /** Creates a new X837Ins_1000A_NM1_SubmitterName RecordBuilder by copying an existing X837Ins_1000A_NM1_SubmitterName instance */
  public static net.explorys.samhat.z12.r837.X837Ins_1000A_NM1_SubmitterName.Builder newBuilder(net.explorys.samhat.z12.r837.X837Ins_1000A_NM1_SubmitterName other) {
    return new net.explorys.samhat.z12.r837.X837Ins_1000A_NM1_SubmitterName.Builder(other);
  }
  
  /**
   * RecordBuilder for X837Ins_1000A_NM1_SubmitterName instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<X837Ins_1000A_NM1_SubmitterName>
    implements org.apache.avro.data.RecordBuilder<X837Ins_1000A_NM1_SubmitterName> {

    private java.lang.CharSequence _1000ANM101EntityIdentifierCode;
    private java.lang.CharSequence _1000ANM102EntityTypeQualifier;
    private java.lang.CharSequence _1000ANM103SubmitterLastOrOrganizationName;
    private java.lang.CharSequence _1000ANM104SubmitterFirstName;
    private java.lang.CharSequence _1000ANM105SubmitterMiddleName;
    private java.lang.CharSequence _1000ANM108IdentificationCodeQualifier;
    private java.lang.CharSequence _1000ANM109SubmitterIdentifier;

    /** Creates a new Builder */
    private Builder() {
      super(net.explorys.samhat.z12.r837.X837Ins_1000A_NM1_SubmitterName.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(net.explorys.samhat.z12.r837.X837Ins_1000A_NM1_SubmitterName.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other._1000ANM101EntityIdentifierCode)) {
        this._1000ANM101EntityIdentifierCode = data().deepCopy(fields()[0].schema(), other._1000ANM101EntityIdentifierCode);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other._1000ANM102EntityTypeQualifier)) {
        this._1000ANM102EntityTypeQualifier = data().deepCopy(fields()[1].schema(), other._1000ANM102EntityTypeQualifier);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other._1000ANM103SubmitterLastOrOrganizationName)) {
        this._1000ANM103SubmitterLastOrOrganizationName = data().deepCopy(fields()[2].schema(), other._1000ANM103SubmitterLastOrOrganizationName);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other._1000ANM104SubmitterFirstName)) {
        this._1000ANM104SubmitterFirstName = data().deepCopy(fields()[3].schema(), other._1000ANM104SubmitterFirstName);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other._1000ANM105SubmitterMiddleName)) {
        this._1000ANM105SubmitterMiddleName = data().deepCopy(fields()[4].schema(), other._1000ANM105SubmitterMiddleName);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other._1000ANM108IdentificationCodeQualifier)) {
        this._1000ANM108IdentificationCodeQualifier = data().deepCopy(fields()[5].schema(), other._1000ANM108IdentificationCodeQualifier);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other._1000ANM109SubmitterIdentifier)) {
        this._1000ANM109SubmitterIdentifier = data().deepCopy(fields()[6].schema(), other._1000ANM109SubmitterIdentifier);
        fieldSetFlags()[6] = true;
      }
    }
    
    /** Creates a Builder by copying an existing X837Ins_1000A_NM1_SubmitterName instance */
    private Builder(net.explorys.samhat.z12.r837.X837Ins_1000A_NM1_SubmitterName other) {
            super(net.explorys.samhat.z12.r837.X837Ins_1000A_NM1_SubmitterName.SCHEMA$);
      if (isValidValue(fields()[0], other._1000ANM101EntityIdentifierCode)) {
        this._1000ANM101EntityIdentifierCode = data().deepCopy(fields()[0].schema(), other._1000ANM101EntityIdentifierCode);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other._1000ANM102EntityTypeQualifier)) {
        this._1000ANM102EntityTypeQualifier = data().deepCopy(fields()[1].schema(), other._1000ANM102EntityTypeQualifier);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other._1000ANM103SubmitterLastOrOrganizationName)) {
        this._1000ANM103SubmitterLastOrOrganizationName = data().deepCopy(fields()[2].schema(), other._1000ANM103SubmitterLastOrOrganizationName);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other._1000ANM104SubmitterFirstName)) {
        this._1000ANM104SubmitterFirstName = data().deepCopy(fields()[3].schema(), other._1000ANM104SubmitterFirstName);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other._1000ANM105SubmitterMiddleName)) {
        this._1000ANM105SubmitterMiddleName = data().deepCopy(fields()[4].schema(), other._1000ANM105SubmitterMiddleName);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other._1000ANM108IdentificationCodeQualifier)) {
        this._1000ANM108IdentificationCodeQualifier = data().deepCopy(fields()[5].schema(), other._1000ANM108IdentificationCodeQualifier);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other._1000ANM109SubmitterIdentifier)) {
        this._1000ANM109SubmitterIdentifier = data().deepCopy(fields()[6].schema(), other._1000ANM109SubmitterIdentifier);
        fieldSetFlags()[6] = true;
      }
    }

    /** Gets the value of the '_1000ANM101EntityIdentifierCode' field */
    public java.lang.CharSequence get1000ANM101EntityIdentifierCode$1() {
      return _1000ANM101EntityIdentifierCode;
    }
    
    /** Sets the value of the '_1000ANM101EntityIdentifierCode' field */
    public net.explorys.samhat.z12.r837.X837Ins_1000A_NM1_SubmitterName.Builder set1000ANM101EntityIdentifierCode$1(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this._1000ANM101EntityIdentifierCode = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the '_1000ANM101EntityIdentifierCode' field has been set */
    public boolean has1000ANM101EntityIdentifierCode$1() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the '_1000ANM101EntityIdentifierCode' field */
    public net.explorys.samhat.z12.r837.X837Ins_1000A_NM1_SubmitterName.Builder clear1000ANM101EntityIdentifierCode$1() {
      _1000ANM101EntityIdentifierCode = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the '_1000ANM102EntityTypeQualifier' field */
    public java.lang.CharSequence get1000ANM102EntityTypeQualifier$1() {
      return _1000ANM102EntityTypeQualifier;
    }
    
    /** Sets the value of the '_1000ANM102EntityTypeQualifier' field */
    public net.explorys.samhat.z12.r837.X837Ins_1000A_NM1_SubmitterName.Builder set1000ANM102EntityTypeQualifier$1(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this._1000ANM102EntityTypeQualifier = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the '_1000ANM102EntityTypeQualifier' field has been set */
    public boolean has1000ANM102EntityTypeQualifier$1() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the '_1000ANM102EntityTypeQualifier' field */
    public net.explorys.samhat.z12.r837.X837Ins_1000A_NM1_SubmitterName.Builder clear1000ANM102EntityTypeQualifier$1() {
      _1000ANM102EntityTypeQualifier = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the '_1000ANM103SubmitterLastOrOrganizationName' field */
    public java.lang.CharSequence get1000ANM103SubmitterLastOrOrganizationName$1() {
      return _1000ANM103SubmitterLastOrOrganizationName;
    }
    
    /** Sets the value of the '_1000ANM103SubmitterLastOrOrganizationName' field */
    public net.explorys.samhat.z12.r837.X837Ins_1000A_NM1_SubmitterName.Builder set1000ANM103SubmitterLastOrOrganizationName$1(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this._1000ANM103SubmitterLastOrOrganizationName = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the '_1000ANM103SubmitterLastOrOrganizationName' field has been set */
    public boolean has1000ANM103SubmitterLastOrOrganizationName$1() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the '_1000ANM103SubmitterLastOrOrganizationName' field */
    public net.explorys.samhat.z12.r837.X837Ins_1000A_NM1_SubmitterName.Builder clear1000ANM103SubmitterLastOrOrganizationName$1() {
      _1000ANM103SubmitterLastOrOrganizationName = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the '_1000ANM104SubmitterFirstName' field */
    public java.lang.CharSequence get1000ANM104SubmitterFirstName$1() {
      return _1000ANM104SubmitterFirstName;
    }
    
    /** Sets the value of the '_1000ANM104SubmitterFirstName' field */
    public net.explorys.samhat.z12.r837.X837Ins_1000A_NM1_SubmitterName.Builder set1000ANM104SubmitterFirstName$1(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this._1000ANM104SubmitterFirstName = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the '_1000ANM104SubmitterFirstName' field has been set */
    public boolean has1000ANM104SubmitterFirstName$1() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the '_1000ANM104SubmitterFirstName' field */
    public net.explorys.samhat.z12.r837.X837Ins_1000A_NM1_SubmitterName.Builder clear1000ANM104SubmitterFirstName$1() {
      _1000ANM104SubmitterFirstName = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the '_1000ANM105SubmitterMiddleName' field */
    public java.lang.CharSequence get1000ANM105SubmitterMiddleName$1() {
      return _1000ANM105SubmitterMiddleName;
    }
    
    /** Sets the value of the '_1000ANM105SubmitterMiddleName' field */
    public net.explorys.samhat.z12.r837.X837Ins_1000A_NM1_SubmitterName.Builder set1000ANM105SubmitterMiddleName$1(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this._1000ANM105SubmitterMiddleName = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the '_1000ANM105SubmitterMiddleName' field has been set */
    public boolean has1000ANM105SubmitterMiddleName$1() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the '_1000ANM105SubmitterMiddleName' field */
    public net.explorys.samhat.z12.r837.X837Ins_1000A_NM1_SubmitterName.Builder clear1000ANM105SubmitterMiddleName$1() {
      _1000ANM105SubmitterMiddleName = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the '_1000ANM108IdentificationCodeQualifier' field */
    public java.lang.CharSequence get1000ANM108IdentificationCodeQualifier$1() {
      return _1000ANM108IdentificationCodeQualifier;
    }
    
    /** Sets the value of the '_1000ANM108IdentificationCodeQualifier' field */
    public net.explorys.samhat.z12.r837.X837Ins_1000A_NM1_SubmitterName.Builder set1000ANM108IdentificationCodeQualifier$1(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this._1000ANM108IdentificationCodeQualifier = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the '_1000ANM108IdentificationCodeQualifier' field has been set */
    public boolean has1000ANM108IdentificationCodeQualifier$1() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the '_1000ANM108IdentificationCodeQualifier' field */
    public net.explorys.samhat.z12.r837.X837Ins_1000A_NM1_SubmitterName.Builder clear1000ANM108IdentificationCodeQualifier$1() {
      _1000ANM108IdentificationCodeQualifier = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the '_1000ANM109SubmitterIdentifier' field */
    public java.lang.CharSequence get1000ANM109SubmitterIdentifier$1() {
      return _1000ANM109SubmitterIdentifier;
    }
    
    /** Sets the value of the '_1000ANM109SubmitterIdentifier' field */
    public net.explorys.samhat.z12.r837.X837Ins_1000A_NM1_SubmitterName.Builder set1000ANM109SubmitterIdentifier$1(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this._1000ANM109SubmitterIdentifier = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the '_1000ANM109SubmitterIdentifier' field has been set */
    public boolean has1000ANM109SubmitterIdentifier$1() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the '_1000ANM109SubmitterIdentifier' field */
    public net.explorys.samhat.z12.r837.X837Ins_1000A_NM1_SubmitterName.Builder clear1000ANM109SubmitterIdentifier$1() {
      _1000ANM109SubmitterIdentifier = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    public X837Ins_1000A_NM1_SubmitterName build() {
      try {
        X837Ins_1000A_NM1_SubmitterName record = new X837Ins_1000A_NM1_SubmitterName();
        record._1000ANM101EntityIdentifierCode = fieldSetFlags()[0] ? this._1000ANM101EntityIdentifierCode : (java.lang.CharSequence) defaultValue(fields()[0]);
        record._1000ANM102EntityTypeQualifier = fieldSetFlags()[1] ? this._1000ANM102EntityTypeQualifier : (java.lang.CharSequence) defaultValue(fields()[1]);
        record._1000ANM103SubmitterLastOrOrganizationName = fieldSetFlags()[2] ? this._1000ANM103SubmitterLastOrOrganizationName : (java.lang.CharSequence) defaultValue(fields()[2]);
        record._1000ANM104SubmitterFirstName = fieldSetFlags()[3] ? this._1000ANM104SubmitterFirstName : (java.lang.CharSequence) defaultValue(fields()[3]);
        record._1000ANM105SubmitterMiddleName = fieldSetFlags()[4] ? this._1000ANM105SubmitterMiddleName : (java.lang.CharSequence) defaultValue(fields()[4]);
        record._1000ANM108IdentificationCodeQualifier = fieldSetFlags()[5] ? this._1000ANM108IdentificationCodeQualifier : (java.lang.CharSequence) defaultValue(fields()[5]);
        record._1000ANM109SubmitterIdentifier = fieldSetFlags()[6] ? this._1000ANM109SubmitterIdentifier : (java.lang.CharSequence) defaultValue(fields()[6]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
