/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package net.explorys.samhat.z12.r837;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class X837Ins_2330B_N3_OtherPayerAddress extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"X837Ins_2330B_N3_OtherPayerAddress\",\"namespace\":\"net.explorys.samhat.z12.r837\",\"fields\":[{\"name\":\"_2330BN301OtherPayerAddressLine\",\"type\":\"string\"},{\"name\":\"_2330BN302OtherPayerAddressLine\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence _2330BN301OtherPayerAddressLine;
  @Deprecated public java.lang.CharSequence _2330BN302OtherPayerAddressLine;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public X837Ins_2330B_N3_OtherPayerAddress() {}

  /**
   * All-args constructor.
   */
  public X837Ins_2330B_N3_OtherPayerAddress(java.lang.CharSequence _2330BN301OtherPayerAddressLine, java.lang.CharSequence _2330BN302OtherPayerAddressLine) {
    this._2330BN301OtherPayerAddressLine = _2330BN301OtherPayerAddressLine;
    this._2330BN302OtherPayerAddressLine = _2330BN302OtherPayerAddressLine;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return _2330BN301OtherPayerAddressLine;
    case 1: return _2330BN302OtherPayerAddressLine;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: _2330BN301OtherPayerAddressLine = (java.lang.CharSequence)value$; break;
    case 1: _2330BN302OtherPayerAddressLine = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the '_2330BN301OtherPayerAddressLine' field.
   */
  public java.lang.CharSequence get2330BN301OtherPayerAddressLine$1() {
    return _2330BN301OtherPayerAddressLine;
  }

  /**
   * Sets the value of the '_2330BN301OtherPayerAddressLine' field.
   * @param value the value to set.
   */
  public void set2330BN301OtherPayerAddressLine$1(java.lang.CharSequence value) {
    this._2330BN301OtherPayerAddressLine = value;
  }

  /**
   * Gets the value of the '_2330BN302OtherPayerAddressLine' field.
   */
  public java.lang.CharSequence get2330BN302OtherPayerAddressLine$1() {
    return _2330BN302OtherPayerAddressLine;
  }

  /**
   * Sets the value of the '_2330BN302OtherPayerAddressLine' field.
   * @param value the value to set.
   */
  public void set2330BN302OtherPayerAddressLine$1(java.lang.CharSequence value) {
    this._2330BN302OtherPayerAddressLine = value;
  }

  /** Creates a new X837Ins_2330B_N3_OtherPayerAddress RecordBuilder */
  public static net.explorys.samhat.z12.r837.X837Ins_2330B_N3_OtherPayerAddress.Builder newBuilder() {
    return new net.explorys.samhat.z12.r837.X837Ins_2330B_N3_OtherPayerAddress.Builder();
  }
  
  /** Creates a new X837Ins_2330B_N3_OtherPayerAddress RecordBuilder by copying an existing Builder */
  public static net.explorys.samhat.z12.r837.X837Ins_2330B_N3_OtherPayerAddress.Builder newBuilder(net.explorys.samhat.z12.r837.X837Ins_2330B_N3_OtherPayerAddress.Builder other) {
    return new net.explorys.samhat.z12.r837.X837Ins_2330B_N3_OtherPayerAddress.Builder(other);
  }
  
  /** Creates a new X837Ins_2330B_N3_OtherPayerAddress RecordBuilder by copying an existing X837Ins_2330B_N3_OtherPayerAddress instance */
  public static net.explorys.samhat.z12.r837.X837Ins_2330B_N3_OtherPayerAddress.Builder newBuilder(net.explorys.samhat.z12.r837.X837Ins_2330B_N3_OtherPayerAddress other) {
    return new net.explorys.samhat.z12.r837.X837Ins_2330B_N3_OtherPayerAddress.Builder(other);
  }
  
  /**
   * RecordBuilder for X837Ins_2330B_N3_OtherPayerAddress instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<X837Ins_2330B_N3_OtherPayerAddress>
    implements org.apache.avro.data.RecordBuilder<X837Ins_2330B_N3_OtherPayerAddress> {

    private java.lang.CharSequence _2330BN301OtherPayerAddressLine;
    private java.lang.CharSequence _2330BN302OtherPayerAddressLine;

    /** Creates a new Builder */
    private Builder() {
      super(net.explorys.samhat.z12.r837.X837Ins_2330B_N3_OtherPayerAddress.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(net.explorys.samhat.z12.r837.X837Ins_2330B_N3_OtherPayerAddress.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other._2330BN301OtherPayerAddressLine)) {
        this._2330BN301OtherPayerAddressLine = data().deepCopy(fields()[0].schema(), other._2330BN301OtherPayerAddressLine);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other._2330BN302OtherPayerAddressLine)) {
        this._2330BN302OtherPayerAddressLine = data().deepCopy(fields()[1].schema(), other._2330BN302OtherPayerAddressLine);
        fieldSetFlags()[1] = true;
      }
    }
    
    /** Creates a Builder by copying an existing X837Ins_2330B_N3_OtherPayerAddress instance */
    private Builder(net.explorys.samhat.z12.r837.X837Ins_2330B_N3_OtherPayerAddress other) {
            super(net.explorys.samhat.z12.r837.X837Ins_2330B_N3_OtherPayerAddress.SCHEMA$);
      if (isValidValue(fields()[0], other._2330BN301OtherPayerAddressLine)) {
        this._2330BN301OtherPayerAddressLine = data().deepCopy(fields()[0].schema(), other._2330BN301OtherPayerAddressLine);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other._2330BN302OtherPayerAddressLine)) {
        this._2330BN302OtherPayerAddressLine = data().deepCopy(fields()[1].schema(), other._2330BN302OtherPayerAddressLine);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the '_2330BN301OtherPayerAddressLine' field */
    public java.lang.CharSequence get2330BN301OtherPayerAddressLine$1() {
      return _2330BN301OtherPayerAddressLine;
    }
    
    /** Sets the value of the '_2330BN301OtherPayerAddressLine' field */
    public net.explorys.samhat.z12.r837.X837Ins_2330B_N3_OtherPayerAddress.Builder set2330BN301OtherPayerAddressLine$1(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this._2330BN301OtherPayerAddressLine = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the '_2330BN301OtherPayerAddressLine' field has been set */
    public boolean has2330BN301OtherPayerAddressLine$1() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the '_2330BN301OtherPayerAddressLine' field */
    public net.explorys.samhat.z12.r837.X837Ins_2330B_N3_OtherPayerAddress.Builder clear2330BN301OtherPayerAddressLine$1() {
      _2330BN301OtherPayerAddressLine = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the '_2330BN302OtherPayerAddressLine' field */
    public java.lang.CharSequence get2330BN302OtherPayerAddressLine$1() {
      return _2330BN302OtherPayerAddressLine;
    }
    
    /** Sets the value of the '_2330BN302OtherPayerAddressLine' field */
    public net.explorys.samhat.z12.r837.X837Ins_2330B_N3_OtherPayerAddress.Builder set2330BN302OtherPayerAddressLine$1(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this._2330BN302OtherPayerAddressLine = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the '_2330BN302OtherPayerAddressLine' field has been set */
    public boolean has2330BN302OtherPayerAddressLine$1() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the '_2330BN302OtherPayerAddressLine' field */
    public net.explorys.samhat.z12.r837.X837Ins_2330B_N3_OtherPayerAddress.Builder clear2330BN302OtherPayerAddressLine$1() {
      _2330BN302OtherPayerAddressLine = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public X837Ins_2330B_N3_OtherPayerAddress build() {
      try {
        X837Ins_2330B_N3_OtherPayerAddress record = new X837Ins_2330B_N3_OtherPayerAddress();
        record._2330BN301OtherPayerAddressLine = fieldSetFlags()[0] ? this._2330BN301OtherPayerAddressLine : (java.lang.CharSequence) defaultValue(fields()[0]);
        record._2330BN302OtherPayerAddressLine = fieldSetFlags()[1] ? this._2330BN302OtherPayerAddressLine : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
