/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package net.explorys.samhat.z12.r837;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class X837Pro_2400_HSD_HealthCareServicesDelivery extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"X837Pro_2400_HSD_HealthCareServicesDelivery\",\"namespace\":\"net.explorys.samhat.z12.r837\",\"fields\":[{\"name\":\"_2400HSD01Visits\",\"type\":\"string\"},{\"name\":\"_2400HSD02NumberOfVisits\",\"type\":\"string\"},{\"name\":\"_2400HSD03FrequencyPeriod\",\"type\":\"string\"},{\"name\":\"_2400HSD04FrequencyCount\",\"type\":\"string\"},{\"name\":\"_2400HSD05DurationOfVisitsUnits\",\"type\":\"string\"},{\"name\":\"_2400HSD06DurationOfVisitsNumberOfUnits\",\"type\":\"string\"},{\"name\":\"_2400HSD07ShipDeliveryOrCalendarPatternCode\",\"type\":\"string\"},{\"name\":\"_2400HSD08DeliveryPatternTimeCode\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence _2400HSD01Visits;
  @Deprecated public java.lang.CharSequence _2400HSD02NumberOfVisits;
  @Deprecated public java.lang.CharSequence _2400HSD03FrequencyPeriod;
  @Deprecated public java.lang.CharSequence _2400HSD04FrequencyCount;
  @Deprecated public java.lang.CharSequence _2400HSD05DurationOfVisitsUnits;
  @Deprecated public java.lang.CharSequence _2400HSD06DurationOfVisitsNumberOfUnits;
  @Deprecated public java.lang.CharSequence _2400HSD07ShipDeliveryOrCalendarPatternCode;
  @Deprecated public java.lang.CharSequence _2400HSD08DeliveryPatternTimeCode;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public X837Pro_2400_HSD_HealthCareServicesDelivery() {}

  /**
   * All-args constructor.
   */
  public X837Pro_2400_HSD_HealthCareServicesDelivery(java.lang.CharSequence _2400HSD01Visits, java.lang.CharSequence _2400HSD02NumberOfVisits, java.lang.CharSequence _2400HSD03FrequencyPeriod, java.lang.CharSequence _2400HSD04FrequencyCount, java.lang.CharSequence _2400HSD05DurationOfVisitsUnits, java.lang.CharSequence _2400HSD06DurationOfVisitsNumberOfUnits, java.lang.CharSequence _2400HSD07ShipDeliveryOrCalendarPatternCode, java.lang.CharSequence _2400HSD08DeliveryPatternTimeCode) {
    this._2400HSD01Visits = _2400HSD01Visits;
    this._2400HSD02NumberOfVisits = _2400HSD02NumberOfVisits;
    this._2400HSD03FrequencyPeriod = _2400HSD03FrequencyPeriod;
    this._2400HSD04FrequencyCount = _2400HSD04FrequencyCount;
    this._2400HSD05DurationOfVisitsUnits = _2400HSD05DurationOfVisitsUnits;
    this._2400HSD06DurationOfVisitsNumberOfUnits = _2400HSD06DurationOfVisitsNumberOfUnits;
    this._2400HSD07ShipDeliveryOrCalendarPatternCode = _2400HSD07ShipDeliveryOrCalendarPatternCode;
    this._2400HSD08DeliveryPatternTimeCode = _2400HSD08DeliveryPatternTimeCode;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return _2400HSD01Visits;
    case 1: return _2400HSD02NumberOfVisits;
    case 2: return _2400HSD03FrequencyPeriod;
    case 3: return _2400HSD04FrequencyCount;
    case 4: return _2400HSD05DurationOfVisitsUnits;
    case 5: return _2400HSD06DurationOfVisitsNumberOfUnits;
    case 6: return _2400HSD07ShipDeliveryOrCalendarPatternCode;
    case 7: return _2400HSD08DeliveryPatternTimeCode;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: _2400HSD01Visits = (java.lang.CharSequence)value$; break;
    case 1: _2400HSD02NumberOfVisits = (java.lang.CharSequence)value$; break;
    case 2: _2400HSD03FrequencyPeriod = (java.lang.CharSequence)value$; break;
    case 3: _2400HSD04FrequencyCount = (java.lang.CharSequence)value$; break;
    case 4: _2400HSD05DurationOfVisitsUnits = (java.lang.CharSequence)value$; break;
    case 5: _2400HSD06DurationOfVisitsNumberOfUnits = (java.lang.CharSequence)value$; break;
    case 6: _2400HSD07ShipDeliveryOrCalendarPatternCode = (java.lang.CharSequence)value$; break;
    case 7: _2400HSD08DeliveryPatternTimeCode = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the '_2400HSD01Visits' field.
   */
  public java.lang.CharSequence get2400HSD01Visits$1() {
    return _2400HSD01Visits;
  }

  /**
   * Sets the value of the '_2400HSD01Visits' field.
   * @param value the value to set.
   */
  public void set2400HSD01Visits$1(java.lang.CharSequence value) {
    this._2400HSD01Visits = value;
  }

  /**
   * Gets the value of the '_2400HSD02NumberOfVisits' field.
   */
  public java.lang.CharSequence get2400HSD02NumberOfVisits$1() {
    return _2400HSD02NumberOfVisits;
  }

  /**
   * Sets the value of the '_2400HSD02NumberOfVisits' field.
   * @param value the value to set.
   */
  public void set2400HSD02NumberOfVisits$1(java.lang.CharSequence value) {
    this._2400HSD02NumberOfVisits = value;
  }

  /**
   * Gets the value of the '_2400HSD03FrequencyPeriod' field.
   */
  public java.lang.CharSequence get2400HSD03FrequencyPeriod$1() {
    return _2400HSD03FrequencyPeriod;
  }

  /**
   * Sets the value of the '_2400HSD03FrequencyPeriod' field.
   * @param value the value to set.
   */
  public void set2400HSD03FrequencyPeriod$1(java.lang.CharSequence value) {
    this._2400HSD03FrequencyPeriod = value;
  }

  /**
   * Gets the value of the '_2400HSD04FrequencyCount' field.
   */
  public java.lang.CharSequence get2400HSD04FrequencyCount$1() {
    return _2400HSD04FrequencyCount;
  }

  /**
   * Sets the value of the '_2400HSD04FrequencyCount' field.
   * @param value the value to set.
   */
  public void set2400HSD04FrequencyCount$1(java.lang.CharSequence value) {
    this._2400HSD04FrequencyCount = value;
  }

  /**
   * Gets the value of the '_2400HSD05DurationOfVisitsUnits' field.
   */
  public java.lang.CharSequence get2400HSD05DurationOfVisitsUnits$1() {
    return _2400HSD05DurationOfVisitsUnits;
  }

  /**
   * Sets the value of the '_2400HSD05DurationOfVisitsUnits' field.
   * @param value the value to set.
   */
  public void set2400HSD05DurationOfVisitsUnits$1(java.lang.CharSequence value) {
    this._2400HSD05DurationOfVisitsUnits = value;
  }

  /**
   * Gets the value of the '_2400HSD06DurationOfVisitsNumberOfUnits' field.
   */
  public java.lang.CharSequence get2400HSD06DurationOfVisitsNumberOfUnits$1() {
    return _2400HSD06DurationOfVisitsNumberOfUnits;
  }

  /**
   * Sets the value of the '_2400HSD06DurationOfVisitsNumberOfUnits' field.
   * @param value the value to set.
   */
  public void set2400HSD06DurationOfVisitsNumberOfUnits$1(java.lang.CharSequence value) {
    this._2400HSD06DurationOfVisitsNumberOfUnits = value;
  }

  /**
   * Gets the value of the '_2400HSD07ShipDeliveryOrCalendarPatternCode' field.
   */
  public java.lang.CharSequence get2400HSD07ShipDeliveryOrCalendarPatternCode$1() {
    return _2400HSD07ShipDeliveryOrCalendarPatternCode;
  }

  /**
   * Sets the value of the '_2400HSD07ShipDeliveryOrCalendarPatternCode' field.
   * @param value the value to set.
   */
  public void set2400HSD07ShipDeliveryOrCalendarPatternCode$1(java.lang.CharSequence value) {
    this._2400HSD07ShipDeliveryOrCalendarPatternCode = value;
  }

  /**
   * Gets the value of the '_2400HSD08DeliveryPatternTimeCode' field.
   */
  public java.lang.CharSequence get2400HSD08DeliveryPatternTimeCode$1() {
    return _2400HSD08DeliveryPatternTimeCode;
  }

  /**
   * Sets the value of the '_2400HSD08DeliveryPatternTimeCode' field.
   * @param value the value to set.
   */
  public void set2400HSD08DeliveryPatternTimeCode$1(java.lang.CharSequence value) {
    this._2400HSD08DeliveryPatternTimeCode = value;
  }

  /** Creates a new X837Pro_2400_HSD_HealthCareServicesDelivery RecordBuilder */
  public static net.explorys.samhat.z12.r837.X837Pro_2400_HSD_HealthCareServicesDelivery.Builder newBuilder() {
    return new net.explorys.samhat.z12.r837.X837Pro_2400_HSD_HealthCareServicesDelivery.Builder();
  }
  
  /** Creates a new X837Pro_2400_HSD_HealthCareServicesDelivery RecordBuilder by copying an existing Builder */
  public static net.explorys.samhat.z12.r837.X837Pro_2400_HSD_HealthCareServicesDelivery.Builder newBuilder(net.explorys.samhat.z12.r837.X837Pro_2400_HSD_HealthCareServicesDelivery.Builder other) {
    return new net.explorys.samhat.z12.r837.X837Pro_2400_HSD_HealthCareServicesDelivery.Builder(other);
  }
  
  /** Creates a new X837Pro_2400_HSD_HealthCareServicesDelivery RecordBuilder by copying an existing X837Pro_2400_HSD_HealthCareServicesDelivery instance */
  public static net.explorys.samhat.z12.r837.X837Pro_2400_HSD_HealthCareServicesDelivery.Builder newBuilder(net.explorys.samhat.z12.r837.X837Pro_2400_HSD_HealthCareServicesDelivery other) {
    return new net.explorys.samhat.z12.r837.X837Pro_2400_HSD_HealthCareServicesDelivery.Builder(other);
  }
  
  /**
   * RecordBuilder for X837Pro_2400_HSD_HealthCareServicesDelivery instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<X837Pro_2400_HSD_HealthCareServicesDelivery>
    implements org.apache.avro.data.RecordBuilder<X837Pro_2400_HSD_HealthCareServicesDelivery> {

    private java.lang.CharSequence _2400HSD01Visits;
    private java.lang.CharSequence _2400HSD02NumberOfVisits;
    private java.lang.CharSequence _2400HSD03FrequencyPeriod;
    private java.lang.CharSequence _2400HSD04FrequencyCount;
    private java.lang.CharSequence _2400HSD05DurationOfVisitsUnits;
    private java.lang.CharSequence _2400HSD06DurationOfVisitsNumberOfUnits;
    private java.lang.CharSequence _2400HSD07ShipDeliveryOrCalendarPatternCode;
    private java.lang.CharSequence _2400HSD08DeliveryPatternTimeCode;

    /** Creates a new Builder */
    private Builder() {
      super(net.explorys.samhat.z12.r837.X837Pro_2400_HSD_HealthCareServicesDelivery.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(net.explorys.samhat.z12.r837.X837Pro_2400_HSD_HealthCareServicesDelivery.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other._2400HSD01Visits)) {
        this._2400HSD01Visits = data().deepCopy(fields()[0].schema(), other._2400HSD01Visits);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other._2400HSD02NumberOfVisits)) {
        this._2400HSD02NumberOfVisits = data().deepCopy(fields()[1].schema(), other._2400HSD02NumberOfVisits);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other._2400HSD03FrequencyPeriod)) {
        this._2400HSD03FrequencyPeriod = data().deepCopy(fields()[2].schema(), other._2400HSD03FrequencyPeriod);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other._2400HSD04FrequencyCount)) {
        this._2400HSD04FrequencyCount = data().deepCopy(fields()[3].schema(), other._2400HSD04FrequencyCount);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other._2400HSD05DurationOfVisitsUnits)) {
        this._2400HSD05DurationOfVisitsUnits = data().deepCopy(fields()[4].schema(), other._2400HSD05DurationOfVisitsUnits);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other._2400HSD06DurationOfVisitsNumberOfUnits)) {
        this._2400HSD06DurationOfVisitsNumberOfUnits = data().deepCopy(fields()[5].schema(), other._2400HSD06DurationOfVisitsNumberOfUnits);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other._2400HSD07ShipDeliveryOrCalendarPatternCode)) {
        this._2400HSD07ShipDeliveryOrCalendarPatternCode = data().deepCopy(fields()[6].schema(), other._2400HSD07ShipDeliveryOrCalendarPatternCode);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other._2400HSD08DeliveryPatternTimeCode)) {
        this._2400HSD08DeliveryPatternTimeCode = data().deepCopy(fields()[7].schema(), other._2400HSD08DeliveryPatternTimeCode);
        fieldSetFlags()[7] = true;
      }
    }
    
    /** Creates a Builder by copying an existing X837Pro_2400_HSD_HealthCareServicesDelivery instance */
    private Builder(net.explorys.samhat.z12.r837.X837Pro_2400_HSD_HealthCareServicesDelivery other) {
            super(net.explorys.samhat.z12.r837.X837Pro_2400_HSD_HealthCareServicesDelivery.SCHEMA$);
      if (isValidValue(fields()[0], other._2400HSD01Visits)) {
        this._2400HSD01Visits = data().deepCopy(fields()[0].schema(), other._2400HSD01Visits);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other._2400HSD02NumberOfVisits)) {
        this._2400HSD02NumberOfVisits = data().deepCopy(fields()[1].schema(), other._2400HSD02NumberOfVisits);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other._2400HSD03FrequencyPeriod)) {
        this._2400HSD03FrequencyPeriod = data().deepCopy(fields()[2].schema(), other._2400HSD03FrequencyPeriod);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other._2400HSD04FrequencyCount)) {
        this._2400HSD04FrequencyCount = data().deepCopy(fields()[3].schema(), other._2400HSD04FrequencyCount);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other._2400HSD05DurationOfVisitsUnits)) {
        this._2400HSD05DurationOfVisitsUnits = data().deepCopy(fields()[4].schema(), other._2400HSD05DurationOfVisitsUnits);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other._2400HSD06DurationOfVisitsNumberOfUnits)) {
        this._2400HSD06DurationOfVisitsNumberOfUnits = data().deepCopy(fields()[5].schema(), other._2400HSD06DurationOfVisitsNumberOfUnits);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other._2400HSD07ShipDeliveryOrCalendarPatternCode)) {
        this._2400HSD07ShipDeliveryOrCalendarPatternCode = data().deepCopy(fields()[6].schema(), other._2400HSD07ShipDeliveryOrCalendarPatternCode);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other._2400HSD08DeliveryPatternTimeCode)) {
        this._2400HSD08DeliveryPatternTimeCode = data().deepCopy(fields()[7].schema(), other._2400HSD08DeliveryPatternTimeCode);
        fieldSetFlags()[7] = true;
      }
    }

    /** Gets the value of the '_2400HSD01Visits' field */
    public java.lang.CharSequence get2400HSD01Visits$1() {
      return _2400HSD01Visits;
    }
    
    /** Sets the value of the '_2400HSD01Visits' field */
    public net.explorys.samhat.z12.r837.X837Pro_2400_HSD_HealthCareServicesDelivery.Builder set2400HSD01Visits$1(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this._2400HSD01Visits = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the '_2400HSD01Visits' field has been set */
    public boolean has2400HSD01Visits$1() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the '_2400HSD01Visits' field */
    public net.explorys.samhat.z12.r837.X837Pro_2400_HSD_HealthCareServicesDelivery.Builder clear2400HSD01Visits$1() {
      _2400HSD01Visits = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the '_2400HSD02NumberOfVisits' field */
    public java.lang.CharSequence get2400HSD02NumberOfVisits$1() {
      return _2400HSD02NumberOfVisits;
    }
    
    /** Sets the value of the '_2400HSD02NumberOfVisits' field */
    public net.explorys.samhat.z12.r837.X837Pro_2400_HSD_HealthCareServicesDelivery.Builder set2400HSD02NumberOfVisits$1(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this._2400HSD02NumberOfVisits = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the '_2400HSD02NumberOfVisits' field has been set */
    public boolean has2400HSD02NumberOfVisits$1() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the '_2400HSD02NumberOfVisits' field */
    public net.explorys.samhat.z12.r837.X837Pro_2400_HSD_HealthCareServicesDelivery.Builder clear2400HSD02NumberOfVisits$1() {
      _2400HSD02NumberOfVisits = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the '_2400HSD03FrequencyPeriod' field */
    public java.lang.CharSequence get2400HSD03FrequencyPeriod$1() {
      return _2400HSD03FrequencyPeriod;
    }
    
    /** Sets the value of the '_2400HSD03FrequencyPeriod' field */
    public net.explorys.samhat.z12.r837.X837Pro_2400_HSD_HealthCareServicesDelivery.Builder set2400HSD03FrequencyPeriod$1(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this._2400HSD03FrequencyPeriod = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the '_2400HSD03FrequencyPeriod' field has been set */
    public boolean has2400HSD03FrequencyPeriod$1() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the '_2400HSD03FrequencyPeriod' field */
    public net.explorys.samhat.z12.r837.X837Pro_2400_HSD_HealthCareServicesDelivery.Builder clear2400HSD03FrequencyPeriod$1() {
      _2400HSD03FrequencyPeriod = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the '_2400HSD04FrequencyCount' field */
    public java.lang.CharSequence get2400HSD04FrequencyCount$1() {
      return _2400HSD04FrequencyCount;
    }
    
    /** Sets the value of the '_2400HSD04FrequencyCount' field */
    public net.explorys.samhat.z12.r837.X837Pro_2400_HSD_HealthCareServicesDelivery.Builder set2400HSD04FrequencyCount$1(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this._2400HSD04FrequencyCount = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the '_2400HSD04FrequencyCount' field has been set */
    public boolean has2400HSD04FrequencyCount$1() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the '_2400HSD04FrequencyCount' field */
    public net.explorys.samhat.z12.r837.X837Pro_2400_HSD_HealthCareServicesDelivery.Builder clear2400HSD04FrequencyCount$1() {
      _2400HSD04FrequencyCount = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the '_2400HSD05DurationOfVisitsUnits' field */
    public java.lang.CharSequence get2400HSD05DurationOfVisitsUnits$1() {
      return _2400HSD05DurationOfVisitsUnits;
    }
    
    /** Sets the value of the '_2400HSD05DurationOfVisitsUnits' field */
    public net.explorys.samhat.z12.r837.X837Pro_2400_HSD_HealthCareServicesDelivery.Builder set2400HSD05DurationOfVisitsUnits$1(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this._2400HSD05DurationOfVisitsUnits = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the '_2400HSD05DurationOfVisitsUnits' field has been set */
    public boolean has2400HSD05DurationOfVisitsUnits$1() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the '_2400HSD05DurationOfVisitsUnits' field */
    public net.explorys.samhat.z12.r837.X837Pro_2400_HSD_HealthCareServicesDelivery.Builder clear2400HSD05DurationOfVisitsUnits$1() {
      _2400HSD05DurationOfVisitsUnits = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the '_2400HSD06DurationOfVisitsNumberOfUnits' field */
    public java.lang.CharSequence get2400HSD06DurationOfVisitsNumberOfUnits$1() {
      return _2400HSD06DurationOfVisitsNumberOfUnits;
    }
    
    /** Sets the value of the '_2400HSD06DurationOfVisitsNumberOfUnits' field */
    public net.explorys.samhat.z12.r837.X837Pro_2400_HSD_HealthCareServicesDelivery.Builder set2400HSD06DurationOfVisitsNumberOfUnits$1(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this._2400HSD06DurationOfVisitsNumberOfUnits = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the '_2400HSD06DurationOfVisitsNumberOfUnits' field has been set */
    public boolean has2400HSD06DurationOfVisitsNumberOfUnits$1() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the '_2400HSD06DurationOfVisitsNumberOfUnits' field */
    public net.explorys.samhat.z12.r837.X837Pro_2400_HSD_HealthCareServicesDelivery.Builder clear2400HSD06DurationOfVisitsNumberOfUnits$1() {
      _2400HSD06DurationOfVisitsNumberOfUnits = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the '_2400HSD07ShipDeliveryOrCalendarPatternCode' field */
    public java.lang.CharSequence get2400HSD07ShipDeliveryOrCalendarPatternCode$1() {
      return _2400HSD07ShipDeliveryOrCalendarPatternCode;
    }
    
    /** Sets the value of the '_2400HSD07ShipDeliveryOrCalendarPatternCode' field */
    public net.explorys.samhat.z12.r837.X837Pro_2400_HSD_HealthCareServicesDelivery.Builder set2400HSD07ShipDeliveryOrCalendarPatternCode$1(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this._2400HSD07ShipDeliveryOrCalendarPatternCode = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the '_2400HSD07ShipDeliveryOrCalendarPatternCode' field has been set */
    public boolean has2400HSD07ShipDeliveryOrCalendarPatternCode$1() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the '_2400HSD07ShipDeliveryOrCalendarPatternCode' field */
    public net.explorys.samhat.z12.r837.X837Pro_2400_HSD_HealthCareServicesDelivery.Builder clear2400HSD07ShipDeliveryOrCalendarPatternCode$1() {
      _2400HSD07ShipDeliveryOrCalendarPatternCode = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the '_2400HSD08DeliveryPatternTimeCode' field */
    public java.lang.CharSequence get2400HSD08DeliveryPatternTimeCode$1() {
      return _2400HSD08DeliveryPatternTimeCode;
    }
    
    /** Sets the value of the '_2400HSD08DeliveryPatternTimeCode' field */
    public net.explorys.samhat.z12.r837.X837Pro_2400_HSD_HealthCareServicesDelivery.Builder set2400HSD08DeliveryPatternTimeCode$1(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this._2400HSD08DeliveryPatternTimeCode = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the '_2400HSD08DeliveryPatternTimeCode' field has been set */
    public boolean has2400HSD08DeliveryPatternTimeCode$1() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the '_2400HSD08DeliveryPatternTimeCode' field */
    public net.explorys.samhat.z12.r837.X837Pro_2400_HSD_HealthCareServicesDelivery.Builder clear2400HSD08DeliveryPatternTimeCode$1() {
      _2400HSD08DeliveryPatternTimeCode = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    @Override
    public X837Pro_2400_HSD_HealthCareServicesDelivery build() {
      try {
        X837Pro_2400_HSD_HealthCareServicesDelivery record = new X837Pro_2400_HSD_HealthCareServicesDelivery();
        record._2400HSD01Visits = fieldSetFlags()[0] ? this._2400HSD01Visits : (java.lang.CharSequence) defaultValue(fields()[0]);
        record._2400HSD02NumberOfVisits = fieldSetFlags()[1] ? this._2400HSD02NumberOfVisits : (java.lang.CharSequence) defaultValue(fields()[1]);
        record._2400HSD03FrequencyPeriod = fieldSetFlags()[2] ? this._2400HSD03FrequencyPeriod : (java.lang.CharSequence) defaultValue(fields()[2]);
        record._2400HSD04FrequencyCount = fieldSetFlags()[3] ? this._2400HSD04FrequencyCount : (java.lang.CharSequence) defaultValue(fields()[3]);
        record._2400HSD05DurationOfVisitsUnits = fieldSetFlags()[4] ? this._2400HSD05DurationOfVisitsUnits : (java.lang.CharSequence) defaultValue(fields()[4]);
        record._2400HSD06DurationOfVisitsNumberOfUnits = fieldSetFlags()[5] ? this._2400HSD06DurationOfVisitsNumberOfUnits : (java.lang.CharSequence) defaultValue(fields()[5]);
        record._2400HSD07ShipDeliveryOrCalendarPatternCode = fieldSetFlags()[6] ? this._2400HSD07ShipDeliveryOrCalendarPatternCode : (java.lang.CharSequence) defaultValue(fields()[6]);
        record._2400HSD08DeliveryPatternTimeCode = fieldSetFlags()[7] ? this._2400HSD08DeliveryPatternTimeCode : (java.lang.CharSequence) defaultValue(fields()[7]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
