/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package net.explorys.samhat.z12.r837;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class X837Ins_2320_CAS_ClaimLevelAdjustment extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"X837Ins_2320_CAS_ClaimLevelAdjustment\",\"namespace\":\"net.explorys.samhat.z12.r837\",\"fields\":[{\"name\":\"_2320CAS01ClaimAdjustmentGroupCode\",\"type\":\"string\"},{\"name\":\"_2320CAS02AdjustmentReasonCode\",\"type\":\"string\"},{\"name\":\"_2320CAS03AdjustmentAmount\",\"type\":\"string\"},{\"name\":\"_2320CAS04AdjustmentQuantity\",\"type\":\"string\"},{\"name\":\"_2320CAS05AdjustmentReasonCode\",\"type\":\"string\"},{\"name\":\"_2320CAS06AdjustmentAmount\",\"type\":\"string\"},{\"name\":\"_2320CAS07AdjustmentQuantity\",\"type\":\"string\"},{\"name\":\"_2320CAS08AdjustmentReasonCode\",\"type\":\"string\"},{\"name\":\"_2320CAS09AdjustmentAmount\",\"type\":\"string\"},{\"name\":\"_2320CAS10AdjustmentQuantity\",\"type\":\"string\"},{\"name\":\"_2320CAS11AdjustmentReasonCode\",\"type\":\"string\"},{\"name\":\"_2320CAS12AdjustmentAmount\",\"type\":\"string\"},{\"name\":\"_2320CAS13AdjustmentQuantity\",\"type\":\"string\"},{\"name\":\"_2320CAS14AdjustmentReasonCode\",\"type\":\"string\"},{\"name\":\"_2320CAS15AdjustmentAmount\",\"type\":\"string\"},{\"name\":\"_2320CAS16AdjustmentQuantity\",\"type\":\"string\"},{\"name\":\"_2320CAS17AdjustmentReasonCode\",\"type\":\"string\"},{\"name\":\"_2320CAS18AdjustmentAmount\",\"type\":\"string\"},{\"name\":\"_2320CAS19AdjustmentQuantity\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence _2320CAS01ClaimAdjustmentGroupCode;
  @Deprecated public java.lang.CharSequence _2320CAS02AdjustmentReasonCode;
  @Deprecated public java.lang.CharSequence _2320CAS03AdjustmentAmount;
  @Deprecated public java.lang.CharSequence _2320CAS04AdjustmentQuantity;
  @Deprecated public java.lang.CharSequence _2320CAS05AdjustmentReasonCode;
  @Deprecated public java.lang.CharSequence _2320CAS06AdjustmentAmount;
  @Deprecated public java.lang.CharSequence _2320CAS07AdjustmentQuantity;
  @Deprecated public java.lang.CharSequence _2320CAS08AdjustmentReasonCode;
  @Deprecated public java.lang.CharSequence _2320CAS09AdjustmentAmount;
  @Deprecated public java.lang.CharSequence _2320CAS10AdjustmentQuantity;
  @Deprecated public java.lang.CharSequence _2320CAS11AdjustmentReasonCode;
  @Deprecated public java.lang.CharSequence _2320CAS12AdjustmentAmount;
  @Deprecated public java.lang.CharSequence _2320CAS13AdjustmentQuantity;
  @Deprecated public java.lang.CharSequence _2320CAS14AdjustmentReasonCode;
  @Deprecated public java.lang.CharSequence _2320CAS15AdjustmentAmount;
  @Deprecated public java.lang.CharSequence _2320CAS16AdjustmentQuantity;
  @Deprecated public java.lang.CharSequence _2320CAS17AdjustmentReasonCode;
  @Deprecated public java.lang.CharSequence _2320CAS18AdjustmentAmount;
  @Deprecated public java.lang.CharSequence _2320CAS19AdjustmentQuantity;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public X837Ins_2320_CAS_ClaimLevelAdjustment() {}

  /**
   * All-args constructor.
   */
  public X837Ins_2320_CAS_ClaimLevelAdjustment(java.lang.CharSequence _2320CAS01ClaimAdjustmentGroupCode, java.lang.CharSequence _2320CAS02AdjustmentReasonCode, java.lang.CharSequence _2320CAS03AdjustmentAmount, java.lang.CharSequence _2320CAS04AdjustmentQuantity, java.lang.CharSequence _2320CAS05AdjustmentReasonCode, java.lang.CharSequence _2320CAS06AdjustmentAmount, java.lang.CharSequence _2320CAS07AdjustmentQuantity, java.lang.CharSequence _2320CAS08AdjustmentReasonCode, java.lang.CharSequence _2320CAS09AdjustmentAmount, java.lang.CharSequence _2320CAS10AdjustmentQuantity, java.lang.CharSequence _2320CAS11AdjustmentReasonCode, java.lang.CharSequence _2320CAS12AdjustmentAmount, java.lang.CharSequence _2320CAS13AdjustmentQuantity, java.lang.CharSequence _2320CAS14AdjustmentReasonCode, java.lang.CharSequence _2320CAS15AdjustmentAmount, java.lang.CharSequence _2320CAS16AdjustmentQuantity, java.lang.CharSequence _2320CAS17AdjustmentReasonCode, java.lang.CharSequence _2320CAS18AdjustmentAmount, java.lang.CharSequence _2320CAS19AdjustmentQuantity) {
    this._2320CAS01ClaimAdjustmentGroupCode = _2320CAS01ClaimAdjustmentGroupCode;
    this._2320CAS02AdjustmentReasonCode = _2320CAS02AdjustmentReasonCode;
    this._2320CAS03AdjustmentAmount = _2320CAS03AdjustmentAmount;
    this._2320CAS04AdjustmentQuantity = _2320CAS04AdjustmentQuantity;
    this._2320CAS05AdjustmentReasonCode = _2320CAS05AdjustmentReasonCode;
    this._2320CAS06AdjustmentAmount = _2320CAS06AdjustmentAmount;
    this._2320CAS07AdjustmentQuantity = _2320CAS07AdjustmentQuantity;
    this._2320CAS08AdjustmentReasonCode = _2320CAS08AdjustmentReasonCode;
    this._2320CAS09AdjustmentAmount = _2320CAS09AdjustmentAmount;
    this._2320CAS10AdjustmentQuantity = _2320CAS10AdjustmentQuantity;
    this._2320CAS11AdjustmentReasonCode = _2320CAS11AdjustmentReasonCode;
    this._2320CAS12AdjustmentAmount = _2320CAS12AdjustmentAmount;
    this._2320CAS13AdjustmentQuantity = _2320CAS13AdjustmentQuantity;
    this._2320CAS14AdjustmentReasonCode = _2320CAS14AdjustmentReasonCode;
    this._2320CAS15AdjustmentAmount = _2320CAS15AdjustmentAmount;
    this._2320CAS16AdjustmentQuantity = _2320CAS16AdjustmentQuantity;
    this._2320CAS17AdjustmentReasonCode = _2320CAS17AdjustmentReasonCode;
    this._2320CAS18AdjustmentAmount = _2320CAS18AdjustmentAmount;
    this._2320CAS19AdjustmentQuantity = _2320CAS19AdjustmentQuantity;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return _2320CAS01ClaimAdjustmentGroupCode;
    case 1: return _2320CAS02AdjustmentReasonCode;
    case 2: return _2320CAS03AdjustmentAmount;
    case 3: return _2320CAS04AdjustmentQuantity;
    case 4: return _2320CAS05AdjustmentReasonCode;
    case 5: return _2320CAS06AdjustmentAmount;
    case 6: return _2320CAS07AdjustmentQuantity;
    case 7: return _2320CAS08AdjustmentReasonCode;
    case 8: return _2320CAS09AdjustmentAmount;
    case 9: return _2320CAS10AdjustmentQuantity;
    case 10: return _2320CAS11AdjustmentReasonCode;
    case 11: return _2320CAS12AdjustmentAmount;
    case 12: return _2320CAS13AdjustmentQuantity;
    case 13: return _2320CAS14AdjustmentReasonCode;
    case 14: return _2320CAS15AdjustmentAmount;
    case 15: return _2320CAS16AdjustmentQuantity;
    case 16: return _2320CAS17AdjustmentReasonCode;
    case 17: return _2320CAS18AdjustmentAmount;
    case 18: return _2320CAS19AdjustmentQuantity;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: _2320CAS01ClaimAdjustmentGroupCode = (java.lang.CharSequence)value$; break;
    case 1: _2320CAS02AdjustmentReasonCode = (java.lang.CharSequence)value$; break;
    case 2: _2320CAS03AdjustmentAmount = (java.lang.CharSequence)value$; break;
    case 3: _2320CAS04AdjustmentQuantity = (java.lang.CharSequence)value$; break;
    case 4: _2320CAS05AdjustmentReasonCode = (java.lang.CharSequence)value$; break;
    case 5: _2320CAS06AdjustmentAmount = (java.lang.CharSequence)value$; break;
    case 6: _2320CAS07AdjustmentQuantity = (java.lang.CharSequence)value$; break;
    case 7: _2320CAS08AdjustmentReasonCode = (java.lang.CharSequence)value$; break;
    case 8: _2320CAS09AdjustmentAmount = (java.lang.CharSequence)value$; break;
    case 9: _2320CAS10AdjustmentQuantity = (java.lang.CharSequence)value$; break;
    case 10: _2320CAS11AdjustmentReasonCode = (java.lang.CharSequence)value$; break;
    case 11: _2320CAS12AdjustmentAmount = (java.lang.CharSequence)value$; break;
    case 12: _2320CAS13AdjustmentQuantity = (java.lang.CharSequence)value$; break;
    case 13: _2320CAS14AdjustmentReasonCode = (java.lang.CharSequence)value$; break;
    case 14: _2320CAS15AdjustmentAmount = (java.lang.CharSequence)value$; break;
    case 15: _2320CAS16AdjustmentQuantity = (java.lang.CharSequence)value$; break;
    case 16: _2320CAS17AdjustmentReasonCode = (java.lang.CharSequence)value$; break;
    case 17: _2320CAS18AdjustmentAmount = (java.lang.CharSequence)value$; break;
    case 18: _2320CAS19AdjustmentQuantity = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the '_2320CAS01ClaimAdjustmentGroupCode' field.
   */
  public java.lang.CharSequence get2320CAS01ClaimAdjustmentGroupCode$1() {
    return _2320CAS01ClaimAdjustmentGroupCode;
  }

  /**
   * Sets the value of the '_2320CAS01ClaimAdjustmentGroupCode' field.
   * @param value the value to set.
   */
  public void set2320CAS01ClaimAdjustmentGroupCode$1(java.lang.CharSequence value) {
    this._2320CAS01ClaimAdjustmentGroupCode = value;
  }

  /**
   * Gets the value of the '_2320CAS02AdjustmentReasonCode' field.
   */
  public java.lang.CharSequence get2320CAS02AdjustmentReasonCode$1() {
    return _2320CAS02AdjustmentReasonCode;
  }

  /**
   * Sets the value of the '_2320CAS02AdjustmentReasonCode' field.
   * @param value the value to set.
   */
  public void set2320CAS02AdjustmentReasonCode$1(java.lang.CharSequence value) {
    this._2320CAS02AdjustmentReasonCode = value;
  }

  /**
   * Gets the value of the '_2320CAS03AdjustmentAmount' field.
   */
  public java.lang.CharSequence get2320CAS03AdjustmentAmount$1() {
    return _2320CAS03AdjustmentAmount;
  }

  /**
   * Sets the value of the '_2320CAS03AdjustmentAmount' field.
   * @param value the value to set.
   */
  public void set2320CAS03AdjustmentAmount$1(java.lang.CharSequence value) {
    this._2320CAS03AdjustmentAmount = value;
  }

  /**
   * Gets the value of the '_2320CAS04AdjustmentQuantity' field.
   */
  public java.lang.CharSequence get2320CAS04AdjustmentQuantity$1() {
    return _2320CAS04AdjustmentQuantity;
  }

  /**
   * Sets the value of the '_2320CAS04AdjustmentQuantity' field.
   * @param value the value to set.
   */
  public void set2320CAS04AdjustmentQuantity$1(java.lang.CharSequence value) {
    this._2320CAS04AdjustmentQuantity = value;
  }

  /**
   * Gets the value of the '_2320CAS05AdjustmentReasonCode' field.
   */
  public java.lang.CharSequence get2320CAS05AdjustmentReasonCode$1() {
    return _2320CAS05AdjustmentReasonCode;
  }

  /**
   * Sets the value of the '_2320CAS05AdjustmentReasonCode' field.
   * @param value the value to set.
   */
  public void set2320CAS05AdjustmentReasonCode$1(java.lang.CharSequence value) {
    this._2320CAS05AdjustmentReasonCode = value;
  }

  /**
   * Gets the value of the '_2320CAS06AdjustmentAmount' field.
   */
  public java.lang.CharSequence get2320CAS06AdjustmentAmount$1() {
    return _2320CAS06AdjustmentAmount;
  }

  /**
   * Sets the value of the '_2320CAS06AdjustmentAmount' field.
   * @param value the value to set.
   */
  public void set2320CAS06AdjustmentAmount$1(java.lang.CharSequence value) {
    this._2320CAS06AdjustmentAmount = value;
  }

  /**
   * Gets the value of the '_2320CAS07AdjustmentQuantity' field.
   */
  public java.lang.CharSequence get2320CAS07AdjustmentQuantity$1() {
    return _2320CAS07AdjustmentQuantity;
  }

  /**
   * Sets the value of the '_2320CAS07AdjustmentQuantity' field.
   * @param value the value to set.
   */
  public void set2320CAS07AdjustmentQuantity$1(java.lang.CharSequence value) {
    this._2320CAS07AdjustmentQuantity = value;
  }

  /**
   * Gets the value of the '_2320CAS08AdjustmentReasonCode' field.
   */
  public java.lang.CharSequence get2320CAS08AdjustmentReasonCode$1() {
    return _2320CAS08AdjustmentReasonCode;
  }

  /**
   * Sets the value of the '_2320CAS08AdjustmentReasonCode' field.
   * @param value the value to set.
   */
  public void set2320CAS08AdjustmentReasonCode$1(java.lang.CharSequence value) {
    this._2320CAS08AdjustmentReasonCode = value;
  }

  /**
   * Gets the value of the '_2320CAS09AdjustmentAmount' field.
   */
  public java.lang.CharSequence get2320CAS09AdjustmentAmount$1() {
    return _2320CAS09AdjustmentAmount;
  }

  /**
   * Sets the value of the '_2320CAS09AdjustmentAmount' field.
   * @param value the value to set.
   */
  public void set2320CAS09AdjustmentAmount$1(java.lang.CharSequence value) {
    this._2320CAS09AdjustmentAmount = value;
  }

  /**
   * Gets the value of the '_2320CAS10AdjustmentQuantity' field.
   */
  public java.lang.CharSequence get2320CAS10AdjustmentQuantity$1() {
    return _2320CAS10AdjustmentQuantity;
  }

  /**
   * Sets the value of the '_2320CAS10AdjustmentQuantity' field.
   * @param value the value to set.
   */
  public void set2320CAS10AdjustmentQuantity$1(java.lang.CharSequence value) {
    this._2320CAS10AdjustmentQuantity = value;
  }

  /**
   * Gets the value of the '_2320CAS11AdjustmentReasonCode' field.
   */
  public java.lang.CharSequence get2320CAS11AdjustmentReasonCode$1() {
    return _2320CAS11AdjustmentReasonCode;
  }

  /**
   * Sets the value of the '_2320CAS11AdjustmentReasonCode' field.
   * @param value the value to set.
   */
  public void set2320CAS11AdjustmentReasonCode$1(java.lang.CharSequence value) {
    this._2320CAS11AdjustmentReasonCode = value;
  }

  /**
   * Gets the value of the '_2320CAS12AdjustmentAmount' field.
   */
  public java.lang.CharSequence get2320CAS12AdjustmentAmount$1() {
    return _2320CAS12AdjustmentAmount;
  }

  /**
   * Sets the value of the '_2320CAS12AdjustmentAmount' field.
   * @param value the value to set.
   */
  public void set2320CAS12AdjustmentAmount$1(java.lang.CharSequence value) {
    this._2320CAS12AdjustmentAmount = value;
  }

  /**
   * Gets the value of the '_2320CAS13AdjustmentQuantity' field.
   */
  public java.lang.CharSequence get2320CAS13AdjustmentQuantity$1() {
    return _2320CAS13AdjustmentQuantity;
  }

  /**
   * Sets the value of the '_2320CAS13AdjustmentQuantity' field.
   * @param value the value to set.
   */
  public void set2320CAS13AdjustmentQuantity$1(java.lang.CharSequence value) {
    this._2320CAS13AdjustmentQuantity = value;
  }

  /**
   * Gets the value of the '_2320CAS14AdjustmentReasonCode' field.
   */
  public java.lang.CharSequence get2320CAS14AdjustmentReasonCode$1() {
    return _2320CAS14AdjustmentReasonCode;
  }

  /**
   * Sets the value of the '_2320CAS14AdjustmentReasonCode' field.
   * @param value the value to set.
   */
  public void set2320CAS14AdjustmentReasonCode$1(java.lang.CharSequence value) {
    this._2320CAS14AdjustmentReasonCode = value;
  }

  /**
   * Gets the value of the '_2320CAS15AdjustmentAmount' field.
   */
  public java.lang.CharSequence get2320CAS15AdjustmentAmount$1() {
    return _2320CAS15AdjustmentAmount;
  }

  /**
   * Sets the value of the '_2320CAS15AdjustmentAmount' field.
   * @param value the value to set.
   */
  public void set2320CAS15AdjustmentAmount$1(java.lang.CharSequence value) {
    this._2320CAS15AdjustmentAmount = value;
  }

  /**
   * Gets the value of the '_2320CAS16AdjustmentQuantity' field.
   */
  public java.lang.CharSequence get2320CAS16AdjustmentQuantity$1() {
    return _2320CAS16AdjustmentQuantity;
  }

  /**
   * Sets the value of the '_2320CAS16AdjustmentQuantity' field.
   * @param value the value to set.
   */
  public void set2320CAS16AdjustmentQuantity$1(java.lang.CharSequence value) {
    this._2320CAS16AdjustmentQuantity = value;
  }

  /**
   * Gets the value of the '_2320CAS17AdjustmentReasonCode' field.
   */
  public java.lang.CharSequence get2320CAS17AdjustmentReasonCode$1() {
    return _2320CAS17AdjustmentReasonCode;
  }

  /**
   * Sets the value of the '_2320CAS17AdjustmentReasonCode' field.
   * @param value the value to set.
   */
  public void set2320CAS17AdjustmentReasonCode$1(java.lang.CharSequence value) {
    this._2320CAS17AdjustmentReasonCode = value;
  }

  /**
   * Gets the value of the '_2320CAS18AdjustmentAmount' field.
   */
  public java.lang.CharSequence get2320CAS18AdjustmentAmount$1() {
    return _2320CAS18AdjustmentAmount;
  }

  /**
   * Sets the value of the '_2320CAS18AdjustmentAmount' field.
   * @param value the value to set.
   */
  public void set2320CAS18AdjustmentAmount$1(java.lang.CharSequence value) {
    this._2320CAS18AdjustmentAmount = value;
  }

  /**
   * Gets the value of the '_2320CAS19AdjustmentQuantity' field.
   */
  public java.lang.CharSequence get2320CAS19AdjustmentQuantity$1() {
    return _2320CAS19AdjustmentQuantity;
  }

  /**
   * Sets the value of the '_2320CAS19AdjustmentQuantity' field.
   * @param value the value to set.
   */
  public void set2320CAS19AdjustmentQuantity$1(java.lang.CharSequence value) {
    this._2320CAS19AdjustmentQuantity = value;
  }

  /** Creates a new X837Ins_2320_CAS_ClaimLevelAdjustment RecordBuilder */
  public static net.explorys.samhat.z12.r837.X837Ins_2320_CAS_ClaimLevelAdjustment.Builder newBuilder() {
    return new net.explorys.samhat.z12.r837.X837Ins_2320_CAS_ClaimLevelAdjustment.Builder();
  }
  
  /** Creates a new X837Ins_2320_CAS_ClaimLevelAdjustment RecordBuilder by copying an existing Builder */
  public static net.explorys.samhat.z12.r837.X837Ins_2320_CAS_ClaimLevelAdjustment.Builder newBuilder(net.explorys.samhat.z12.r837.X837Ins_2320_CAS_ClaimLevelAdjustment.Builder other) {
    return new net.explorys.samhat.z12.r837.X837Ins_2320_CAS_ClaimLevelAdjustment.Builder(other);
  }
  
  /** Creates a new X837Ins_2320_CAS_ClaimLevelAdjustment RecordBuilder by copying an existing X837Ins_2320_CAS_ClaimLevelAdjustment instance */
  public static net.explorys.samhat.z12.r837.X837Ins_2320_CAS_ClaimLevelAdjustment.Builder newBuilder(net.explorys.samhat.z12.r837.X837Ins_2320_CAS_ClaimLevelAdjustment other) {
    return new net.explorys.samhat.z12.r837.X837Ins_2320_CAS_ClaimLevelAdjustment.Builder(other);
  }
  
  /**
   * RecordBuilder for X837Ins_2320_CAS_ClaimLevelAdjustment instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<X837Ins_2320_CAS_ClaimLevelAdjustment>
    implements org.apache.avro.data.RecordBuilder<X837Ins_2320_CAS_ClaimLevelAdjustment> {

    private java.lang.CharSequence _2320CAS01ClaimAdjustmentGroupCode;
    private java.lang.CharSequence _2320CAS02AdjustmentReasonCode;
    private java.lang.CharSequence _2320CAS03AdjustmentAmount;
    private java.lang.CharSequence _2320CAS04AdjustmentQuantity;
    private java.lang.CharSequence _2320CAS05AdjustmentReasonCode;
    private java.lang.CharSequence _2320CAS06AdjustmentAmount;
    private java.lang.CharSequence _2320CAS07AdjustmentQuantity;
    private java.lang.CharSequence _2320CAS08AdjustmentReasonCode;
    private java.lang.CharSequence _2320CAS09AdjustmentAmount;
    private java.lang.CharSequence _2320CAS10AdjustmentQuantity;
    private java.lang.CharSequence _2320CAS11AdjustmentReasonCode;
    private java.lang.CharSequence _2320CAS12AdjustmentAmount;
    private java.lang.CharSequence _2320CAS13AdjustmentQuantity;
    private java.lang.CharSequence _2320CAS14AdjustmentReasonCode;
    private java.lang.CharSequence _2320CAS15AdjustmentAmount;
    private java.lang.CharSequence _2320CAS16AdjustmentQuantity;
    private java.lang.CharSequence _2320CAS17AdjustmentReasonCode;
    private java.lang.CharSequence _2320CAS18AdjustmentAmount;
    private java.lang.CharSequence _2320CAS19AdjustmentQuantity;

    /** Creates a new Builder */
    private Builder() {
      super(net.explorys.samhat.z12.r837.X837Ins_2320_CAS_ClaimLevelAdjustment.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(net.explorys.samhat.z12.r837.X837Ins_2320_CAS_ClaimLevelAdjustment.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other._2320CAS01ClaimAdjustmentGroupCode)) {
        this._2320CAS01ClaimAdjustmentGroupCode = data().deepCopy(fields()[0].schema(), other._2320CAS01ClaimAdjustmentGroupCode);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other._2320CAS02AdjustmentReasonCode)) {
        this._2320CAS02AdjustmentReasonCode = data().deepCopy(fields()[1].schema(), other._2320CAS02AdjustmentReasonCode);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other._2320CAS03AdjustmentAmount)) {
        this._2320CAS03AdjustmentAmount = data().deepCopy(fields()[2].schema(), other._2320CAS03AdjustmentAmount);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other._2320CAS04AdjustmentQuantity)) {
        this._2320CAS04AdjustmentQuantity = data().deepCopy(fields()[3].schema(), other._2320CAS04AdjustmentQuantity);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other._2320CAS05AdjustmentReasonCode)) {
        this._2320CAS05AdjustmentReasonCode = data().deepCopy(fields()[4].schema(), other._2320CAS05AdjustmentReasonCode);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other._2320CAS06AdjustmentAmount)) {
        this._2320CAS06AdjustmentAmount = data().deepCopy(fields()[5].schema(), other._2320CAS06AdjustmentAmount);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other._2320CAS07AdjustmentQuantity)) {
        this._2320CAS07AdjustmentQuantity = data().deepCopy(fields()[6].schema(), other._2320CAS07AdjustmentQuantity);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other._2320CAS08AdjustmentReasonCode)) {
        this._2320CAS08AdjustmentReasonCode = data().deepCopy(fields()[7].schema(), other._2320CAS08AdjustmentReasonCode);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other._2320CAS09AdjustmentAmount)) {
        this._2320CAS09AdjustmentAmount = data().deepCopy(fields()[8].schema(), other._2320CAS09AdjustmentAmount);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other._2320CAS10AdjustmentQuantity)) {
        this._2320CAS10AdjustmentQuantity = data().deepCopy(fields()[9].schema(), other._2320CAS10AdjustmentQuantity);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other._2320CAS11AdjustmentReasonCode)) {
        this._2320CAS11AdjustmentReasonCode = data().deepCopy(fields()[10].schema(), other._2320CAS11AdjustmentReasonCode);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other._2320CAS12AdjustmentAmount)) {
        this._2320CAS12AdjustmentAmount = data().deepCopy(fields()[11].schema(), other._2320CAS12AdjustmentAmount);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other._2320CAS13AdjustmentQuantity)) {
        this._2320CAS13AdjustmentQuantity = data().deepCopy(fields()[12].schema(), other._2320CAS13AdjustmentQuantity);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other._2320CAS14AdjustmentReasonCode)) {
        this._2320CAS14AdjustmentReasonCode = data().deepCopy(fields()[13].schema(), other._2320CAS14AdjustmentReasonCode);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other._2320CAS15AdjustmentAmount)) {
        this._2320CAS15AdjustmentAmount = data().deepCopy(fields()[14].schema(), other._2320CAS15AdjustmentAmount);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other._2320CAS16AdjustmentQuantity)) {
        this._2320CAS16AdjustmentQuantity = data().deepCopy(fields()[15].schema(), other._2320CAS16AdjustmentQuantity);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other._2320CAS17AdjustmentReasonCode)) {
        this._2320CAS17AdjustmentReasonCode = data().deepCopy(fields()[16].schema(), other._2320CAS17AdjustmentReasonCode);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other._2320CAS18AdjustmentAmount)) {
        this._2320CAS18AdjustmentAmount = data().deepCopy(fields()[17].schema(), other._2320CAS18AdjustmentAmount);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other._2320CAS19AdjustmentQuantity)) {
        this._2320CAS19AdjustmentQuantity = data().deepCopy(fields()[18].schema(), other._2320CAS19AdjustmentQuantity);
        fieldSetFlags()[18] = true;
      }
    }
    
    /** Creates a Builder by copying an existing X837Ins_2320_CAS_ClaimLevelAdjustment instance */
    private Builder(net.explorys.samhat.z12.r837.X837Ins_2320_CAS_ClaimLevelAdjustment other) {
            super(net.explorys.samhat.z12.r837.X837Ins_2320_CAS_ClaimLevelAdjustment.SCHEMA$);
      if (isValidValue(fields()[0], other._2320CAS01ClaimAdjustmentGroupCode)) {
        this._2320CAS01ClaimAdjustmentGroupCode = data().deepCopy(fields()[0].schema(), other._2320CAS01ClaimAdjustmentGroupCode);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other._2320CAS02AdjustmentReasonCode)) {
        this._2320CAS02AdjustmentReasonCode = data().deepCopy(fields()[1].schema(), other._2320CAS02AdjustmentReasonCode);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other._2320CAS03AdjustmentAmount)) {
        this._2320CAS03AdjustmentAmount = data().deepCopy(fields()[2].schema(), other._2320CAS03AdjustmentAmount);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other._2320CAS04AdjustmentQuantity)) {
        this._2320CAS04AdjustmentQuantity = data().deepCopy(fields()[3].schema(), other._2320CAS04AdjustmentQuantity);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other._2320CAS05AdjustmentReasonCode)) {
        this._2320CAS05AdjustmentReasonCode = data().deepCopy(fields()[4].schema(), other._2320CAS05AdjustmentReasonCode);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other._2320CAS06AdjustmentAmount)) {
        this._2320CAS06AdjustmentAmount = data().deepCopy(fields()[5].schema(), other._2320CAS06AdjustmentAmount);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other._2320CAS07AdjustmentQuantity)) {
        this._2320CAS07AdjustmentQuantity = data().deepCopy(fields()[6].schema(), other._2320CAS07AdjustmentQuantity);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other._2320CAS08AdjustmentReasonCode)) {
        this._2320CAS08AdjustmentReasonCode = data().deepCopy(fields()[7].schema(), other._2320CAS08AdjustmentReasonCode);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other._2320CAS09AdjustmentAmount)) {
        this._2320CAS09AdjustmentAmount = data().deepCopy(fields()[8].schema(), other._2320CAS09AdjustmentAmount);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other._2320CAS10AdjustmentQuantity)) {
        this._2320CAS10AdjustmentQuantity = data().deepCopy(fields()[9].schema(), other._2320CAS10AdjustmentQuantity);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other._2320CAS11AdjustmentReasonCode)) {
        this._2320CAS11AdjustmentReasonCode = data().deepCopy(fields()[10].schema(), other._2320CAS11AdjustmentReasonCode);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other._2320CAS12AdjustmentAmount)) {
        this._2320CAS12AdjustmentAmount = data().deepCopy(fields()[11].schema(), other._2320CAS12AdjustmentAmount);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other._2320CAS13AdjustmentQuantity)) {
        this._2320CAS13AdjustmentQuantity = data().deepCopy(fields()[12].schema(), other._2320CAS13AdjustmentQuantity);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other._2320CAS14AdjustmentReasonCode)) {
        this._2320CAS14AdjustmentReasonCode = data().deepCopy(fields()[13].schema(), other._2320CAS14AdjustmentReasonCode);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other._2320CAS15AdjustmentAmount)) {
        this._2320CAS15AdjustmentAmount = data().deepCopy(fields()[14].schema(), other._2320CAS15AdjustmentAmount);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other._2320CAS16AdjustmentQuantity)) {
        this._2320CAS16AdjustmentQuantity = data().deepCopy(fields()[15].schema(), other._2320CAS16AdjustmentQuantity);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other._2320CAS17AdjustmentReasonCode)) {
        this._2320CAS17AdjustmentReasonCode = data().deepCopy(fields()[16].schema(), other._2320CAS17AdjustmentReasonCode);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other._2320CAS18AdjustmentAmount)) {
        this._2320CAS18AdjustmentAmount = data().deepCopy(fields()[17].schema(), other._2320CAS18AdjustmentAmount);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other._2320CAS19AdjustmentQuantity)) {
        this._2320CAS19AdjustmentQuantity = data().deepCopy(fields()[18].schema(), other._2320CAS19AdjustmentQuantity);
        fieldSetFlags()[18] = true;
      }
    }

    /** Gets the value of the '_2320CAS01ClaimAdjustmentGroupCode' field */
    public java.lang.CharSequence get2320CAS01ClaimAdjustmentGroupCode$1() {
      return _2320CAS01ClaimAdjustmentGroupCode;
    }
    
    /** Sets the value of the '_2320CAS01ClaimAdjustmentGroupCode' field */
    public net.explorys.samhat.z12.r837.X837Ins_2320_CAS_ClaimLevelAdjustment.Builder set2320CAS01ClaimAdjustmentGroupCode$1(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this._2320CAS01ClaimAdjustmentGroupCode = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the '_2320CAS01ClaimAdjustmentGroupCode' field has been set */
    public boolean has2320CAS01ClaimAdjustmentGroupCode$1() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the '_2320CAS01ClaimAdjustmentGroupCode' field */
    public net.explorys.samhat.z12.r837.X837Ins_2320_CAS_ClaimLevelAdjustment.Builder clear2320CAS01ClaimAdjustmentGroupCode$1() {
      _2320CAS01ClaimAdjustmentGroupCode = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the '_2320CAS02AdjustmentReasonCode' field */
    public java.lang.CharSequence get2320CAS02AdjustmentReasonCode$1() {
      return _2320CAS02AdjustmentReasonCode;
    }
    
    /** Sets the value of the '_2320CAS02AdjustmentReasonCode' field */
    public net.explorys.samhat.z12.r837.X837Ins_2320_CAS_ClaimLevelAdjustment.Builder set2320CAS02AdjustmentReasonCode$1(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this._2320CAS02AdjustmentReasonCode = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the '_2320CAS02AdjustmentReasonCode' field has been set */
    public boolean has2320CAS02AdjustmentReasonCode$1() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the '_2320CAS02AdjustmentReasonCode' field */
    public net.explorys.samhat.z12.r837.X837Ins_2320_CAS_ClaimLevelAdjustment.Builder clear2320CAS02AdjustmentReasonCode$1() {
      _2320CAS02AdjustmentReasonCode = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the '_2320CAS03AdjustmentAmount' field */
    public java.lang.CharSequence get2320CAS03AdjustmentAmount$1() {
      return _2320CAS03AdjustmentAmount;
    }
    
    /** Sets the value of the '_2320CAS03AdjustmentAmount' field */
    public net.explorys.samhat.z12.r837.X837Ins_2320_CAS_ClaimLevelAdjustment.Builder set2320CAS03AdjustmentAmount$1(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this._2320CAS03AdjustmentAmount = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the '_2320CAS03AdjustmentAmount' field has been set */
    public boolean has2320CAS03AdjustmentAmount$1() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the '_2320CAS03AdjustmentAmount' field */
    public net.explorys.samhat.z12.r837.X837Ins_2320_CAS_ClaimLevelAdjustment.Builder clear2320CAS03AdjustmentAmount$1() {
      _2320CAS03AdjustmentAmount = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the '_2320CAS04AdjustmentQuantity' field */
    public java.lang.CharSequence get2320CAS04AdjustmentQuantity$1() {
      return _2320CAS04AdjustmentQuantity;
    }
    
    /** Sets the value of the '_2320CAS04AdjustmentQuantity' field */
    public net.explorys.samhat.z12.r837.X837Ins_2320_CAS_ClaimLevelAdjustment.Builder set2320CAS04AdjustmentQuantity$1(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this._2320CAS04AdjustmentQuantity = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the '_2320CAS04AdjustmentQuantity' field has been set */
    public boolean has2320CAS04AdjustmentQuantity$1() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the '_2320CAS04AdjustmentQuantity' field */
    public net.explorys.samhat.z12.r837.X837Ins_2320_CAS_ClaimLevelAdjustment.Builder clear2320CAS04AdjustmentQuantity$1() {
      _2320CAS04AdjustmentQuantity = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the '_2320CAS05AdjustmentReasonCode' field */
    public java.lang.CharSequence get2320CAS05AdjustmentReasonCode$1() {
      return _2320CAS05AdjustmentReasonCode;
    }
    
    /** Sets the value of the '_2320CAS05AdjustmentReasonCode' field */
    public net.explorys.samhat.z12.r837.X837Ins_2320_CAS_ClaimLevelAdjustment.Builder set2320CAS05AdjustmentReasonCode$1(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this._2320CAS05AdjustmentReasonCode = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the '_2320CAS05AdjustmentReasonCode' field has been set */
    public boolean has2320CAS05AdjustmentReasonCode$1() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the '_2320CAS05AdjustmentReasonCode' field */
    public net.explorys.samhat.z12.r837.X837Ins_2320_CAS_ClaimLevelAdjustment.Builder clear2320CAS05AdjustmentReasonCode$1() {
      _2320CAS05AdjustmentReasonCode = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the '_2320CAS06AdjustmentAmount' field */
    public java.lang.CharSequence get2320CAS06AdjustmentAmount$1() {
      return _2320CAS06AdjustmentAmount;
    }
    
    /** Sets the value of the '_2320CAS06AdjustmentAmount' field */
    public net.explorys.samhat.z12.r837.X837Ins_2320_CAS_ClaimLevelAdjustment.Builder set2320CAS06AdjustmentAmount$1(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this._2320CAS06AdjustmentAmount = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the '_2320CAS06AdjustmentAmount' field has been set */
    public boolean has2320CAS06AdjustmentAmount$1() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the '_2320CAS06AdjustmentAmount' field */
    public net.explorys.samhat.z12.r837.X837Ins_2320_CAS_ClaimLevelAdjustment.Builder clear2320CAS06AdjustmentAmount$1() {
      _2320CAS06AdjustmentAmount = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the '_2320CAS07AdjustmentQuantity' field */
    public java.lang.CharSequence get2320CAS07AdjustmentQuantity$1() {
      return _2320CAS07AdjustmentQuantity;
    }
    
    /** Sets the value of the '_2320CAS07AdjustmentQuantity' field */
    public net.explorys.samhat.z12.r837.X837Ins_2320_CAS_ClaimLevelAdjustment.Builder set2320CAS07AdjustmentQuantity$1(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this._2320CAS07AdjustmentQuantity = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the '_2320CAS07AdjustmentQuantity' field has been set */
    public boolean has2320CAS07AdjustmentQuantity$1() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the '_2320CAS07AdjustmentQuantity' field */
    public net.explorys.samhat.z12.r837.X837Ins_2320_CAS_ClaimLevelAdjustment.Builder clear2320CAS07AdjustmentQuantity$1() {
      _2320CAS07AdjustmentQuantity = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the '_2320CAS08AdjustmentReasonCode' field */
    public java.lang.CharSequence get2320CAS08AdjustmentReasonCode$1() {
      return _2320CAS08AdjustmentReasonCode;
    }
    
    /** Sets the value of the '_2320CAS08AdjustmentReasonCode' field */
    public net.explorys.samhat.z12.r837.X837Ins_2320_CAS_ClaimLevelAdjustment.Builder set2320CAS08AdjustmentReasonCode$1(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this._2320CAS08AdjustmentReasonCode = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the '_2320CAS08AdjustmentReasonCode' field has been set */
    public boolean has2320CAS08AdjustmentReasonCode$1() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the '_2320CAS08AdjustmentReasonCode' field */
    public net.explorys.samhat.z12.r837.X837Ins_2320_CAS_ClaimLevelAdjustment.Builder clear2320CAS08AdjustmentReasonCode$1() {
      _2320CAS08AdjustmentReasonCode = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the '_2320CAS09AdjustmentAmount' field */
    public java.lang.CharSequence get2320CAS09AdjustmentAmount$1() {
      return _2320CAS09AdjustmentAmount;
    }
    
    /** Sets the value of the '_2320CAS09AdjustmentAmount' field */
    public net.explorys.samhat.z12.r837.X837Ins_2320_CAS_ClaimLevelAdjustment.Builder set2320CAS09AdjustmentAmount$1(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this._2320CAS09AdjustmentAmount = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the '_2320CAS09AdjustmentAmount' field has been set */
    public boolean has2320CAS09AdjustmentAmount$1() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the '_2320CAS09AdjustmentAmount' field */
    public net.explorys.samhat.z12.r837.X837Ins_2320_CAS_ClaimLevelAdjustment.Builder clear2320CAS09AdjustmentAmount$1() {
      _2320CAS09AdjustmentAmount = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /** Gets the value of the '_2320CAS10AdjustmentQuantity' field */
    public java.lang.CharSequence get2320CAS10AdjustmentQuantity$1() {
      return _2320CAS10AdjustmentQuantity;
    }
    
    /** Sets the value of the '_2320CAS10AdjustmentQuantity' field */
    public net.explorys.samhat.z12.r837.X837Ins_2320_CAS_ClaimLevelAdjustment.Builder set2320CAS10AdjustmentQuantity$1(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this._2320CAS10AdjustmentQuantity = value;
      fieldSetFlags()[9] = true;
      return this; 
    }
    
    /** Checks whether the '_2320CAS10AdjustmentQuantity' field has been set */
    public boolean has2320CAS10AdjustmentQuantity$1() {
      return fieldSetFlags()[9];
    }
    
    /** Clears the value of the '_2320CAS10AdjustmentQuantity' field */
    public net.explorys.samhat.z12.r837.X837Ins_2320_CAS_ClaimLevelAdjustment.Builder clear2320CAS10AdjustmentQuantity$1() {
      _2320CAS10AdjustmentQuantity = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /** Gets the value of the '_2320CAS11AdjustmentReasonCode' field */
    public java.lang.CharSequence get2320CAS11AdjustmentReasonCode$1() {
      return _2320CAS11AdjustmentReasonCode;
    }
    
    /** Sets the value of the '_2320CAS11AdjustmentReasonCode' field */
    public net.explorys.samhat.z12.r837.X837Ins_2320_CAS_ClaimLevelAdjustment.Builder set2320CAS11AdjustmentReasonCode$1(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this._2320CAS11AdjustmentReasonCode = value;
      fieldSetFlags()[10] = true;
      return this; 
    }
    
    /** Checks whether the '_2320CAS11AdjustmentReasonCode' field has been set */
    public boolean has2320CAS11AdjustmentReasonCode$1() {
      return fieldSetFlags()[10];
    }
    
    /** Clears the value of the '_2320CAS11AdjustmentReasonCode' field */
    public net.explorys.samhat.z12.r837.X837Ins_2320_CAS_ClaimLevelAdjustment.Builder clear2320CAS11AdjustmentReasonCode$1() {
      _2320CAS11AdjustmentReasonCode = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /** Gets the value of the '_2320CAS12AdjustmentAmount' field */
    public java.lang.CharSequence get2320CAS12AdjustmentAmount$1() {
      return _2320CAS12AdjustmentAmount;
    }
    
    /** Sets the value of the '_2320CAS12AdjustmentAmount' field */
    public net.explorys.samhat.z12.r837.X837Ins_2320_CAS_ClaimLevelAdjustment.Builder set2320CAS12AdjustmentAmount$1(java.lang.CharSequence value) {
      validate(fields()[11], value);
      this._2320CAS12AdjustmentAmount = value;
      fieldSetFlags()[11] = true;
      return this; 
    }
    
    /** Checks whether the '_2320CAS12AdjustmentAmount' field has been set */
    public boolean has2320CAS12AdjustmentAmount$1() {
      return fieldSetFlags()[11];
    }
    
    /** Clears the value of the '_2320CAS12AdjustmentAmount' field */
    public net.explorys.samhat.z12.r837.X837Ins_2320_CAS_ClaimLevelAdjustment.Builder clear2320CAS12AdjustmentAmount$1() {
      _2320CAS12AdjustmentAmount = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /** Gets the value of the '_2320CAS13AdjustmentQuantity' field */
    public java.lang.CharSequence get2320CAS13AdjustmentQuantity$1() {
      return _2320CAS13AdjustmentQuantity;
    }
    
    /** Sets the value of the '_2320CAS13AdjustmentQuantity' field */
    public net.explorys.samhat.z12.r837.X837Ins_2320_CAS_ClaimLevelAdjustment.Builder set2320CAS13AdjustmentQuantity$1(java.lang.CharSequence value) {
      validate(fields()[12], value);
      this._2320CAS13AdjustmentQuantity = value;
      fieldSetFlags()[12] = true;
      return this; 
    }
    
    /** Checks whether the '_2320CAS13AdjustmentQuantity' field has been set */
    public boolean has2320CAS13AdjustmentQuantity$1() {
      return fieldSetFlags()[12];
    }
    
    /** Clears the value of the '_2320CAS13AdjustmentQuantity' field */
    public net.explorys.samhat.z12.r837.X837Ins_2320_CAS_ClaimLevelAdjustment.Builder clear2320CAS13AdjustmentQuantity$1() {
      _2320CAS13AdjustmentQuantity = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /** Gets the value of the '_2320CAS14AdjustmentReasonCode' field */
    public java.lang.CharSequence get2320CAS14AdjustmentReasonCode$1() {
      return _2320CAS14AdjustmentReasonCode;
    }
    
    /** Sets the value of the '_2320CAS14AdjustmentReasonCode' field */
    public net.explorys.samhat.z12.r837.X837Ins_2320_CAS_ClaimLevelAdjustment.Builder set2320CAS14AdjustmentReasonCode$1(java.lang.CharSequence value) {
      validate(fields()[13], value);
      this._2320CAS14AdjustmentReasonCode = value;
      fieldSetFlags()[13] = true;
      return this; 
    }
    
    /** Checks whether the '_2320CAS14AdjustmentReasonCode' field has been set */
    public boolean has2320CAS14AdjustmentReasonCode$1() {
      return fieldSetFlags()[13];
    }
    
    /** Clears the value of the '_2320CAS14AdjustmentReasonCode' field */
    public net.explorys.samhat.z12.r837.X837Ins_2320_CAS_ClaimLevelAdjustment.Builder clear2320CAS14AdjustmentReasonCode$1() {
      _2320CAS14AdjustmentReasonCode = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    /** Gets the value of the '_2320CAS15AdjustmentAmount' field */
    public java.lang.CharSequence get2320CAS15AdjustmentAmount$1() {
      return _2320CAS15AdjustmentAmount;
    }
    
    /** Sets the value of the '_2320CAS15AdjustmentAmount' field */
    public net.explorys.samhat.z12.r837.X837Ins_2320_CAS_ClaimLevelAdjustment.Builder set2320CAS15AdjustmentAmount$1(java.lang.CharSequence value) {
      validate(fields()[14], value);
      this._2320CAS15AdjustmentAmount = value;
      fieldSetFlags()[14] = true;
      return this; 
    }
    
    /** Checks whether the '_2320CAS15AdjustmentAmount' field has been set */
    public boolean has2320CAS15AdjustmentAmount$1() {
      return fieldSetFlags()[14];
    }
    
    /** Clears the value of the '_2320CAS15AdjustmentAmount' field */
    public net.explorys.samhat.z12.r837.X837Ins_2320_CAS_ClaimLevelAdjustment.Builder clear2320CAS15AdjustmentAmount$1() {
      _2320CAS15AdjustmentAmount = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    /** Gets the value of the '_2320CAS16AdjustmentQuantity' field */
    public java.lang.CharSequence get2320CAS16AdjustmentQuantity$1() {
      return _2320CAS16AdjustmentQuantity;
    }
    
    /** Sets the value of the '_2320CAS16AdjustmentQuantity' field */
    public net.explorys.samhat.z12.r837.X837Ins_2320_CAS_ClaimLevelAdjustment.Builder set2320CAS16AdjustmentQuantity$1(java.lang.CharSequence value) {
      validate(fields()[15], value);
      this._2320CAS16AdjustmentQuantity = value;
      fieldSetFlags()[15] = true;
      return this; 
    }
    
    /** Checks whether the '_2320CAS16AdjustmentQuantity' field has been set */
    public boolean has2320CAS16AdjustmentQuantity$1() {
      return fieldSetFlags()[15];
    }
    
    /** Clears the value of the '_2320CAS16AdjustmentQuantity' field */
    public net.explorys.samhat.z12.r837.X837Ins_2320_CAS_ClaimLevelAdjustment.Builder clear2320CAS16AdjustmentQuantity$1() {
      _2320CAS16AdjustmentQuantity = null;
      fieldSetFlags()[15] = false;
      return this;
    }

    /** Gets the value of the '_2320CAS17AdjustmentReasonCode' field */
    public java.lang.CharSequence get2320CAS17AdjustmentReasonCode$1() {
      return _2320CAS17AdjustmentReasonCode;
    }
    
    /** Sets the value of the '_2320CAS17AdjustmentReasonCode' field */
    public net.explorys.samhat.z12.r837.X837Ins_2320_CAS_ClaimLevelAdjustment.Builder set2320CAS17AdjustmentReasonCode$1(java.lang.CharSequence value) {
      validate(fields()[16], value);
      this._2320CAS17AdjustmentReasonCode = value;
      fieldSetFlags()[16] = true;
      return this; 
    }
    
    /** Checks whether the '_2320CAS17AdjustmentReasonCode' field has been set */
    public boolean has2320CAS17AdjustmentReasonCode$1() {
      return fieldSetFlags()[16];
    }
    
    /** Clears the value of the '_2320CAS17AdjustmentReasonCode' field */
    public net.explorys.samhat.z12.r837.X837Ins_2320_CAS_ClaimLevelAdjustment.Builder clear2320CAS17AdjustmentReasonCode$1() {
      _2320CAS17AdjustmentReasonCode = null;
      fieldSetFlags()[16] = false;
      return this;
    }

    /** Gets the value of the '_2320CAS18AdjustmentAmount' field */
    public java.lang.CharSequence get2320CAS18AdjustmentAmount$1() {
      return _2320CAS18AdjustmentAmount;
    }
    
    /** Sets the value of the '_2320CAS18AdjustmentAmount' field */
    public net.explorys.samhat.z12.r837.X837Ins_2320_CAS_ClaimLevelAdjustment.Builder set2320CAS18AdjustmentAmount$1(java.lang.CharSequence value) {
      validate(fields()[17], value);
      this._2320CAS18AdjustmentAmount = value;
      fieldSetFlags()[17] = true;
      return this; 
    }
    
    /** Checks whether the '_2320CAS18AdjustmentAmount' field has been set */
    public boolean has2320CAS18AdjustmentAmount$1() {
      return fieldSetFlags()[17];
    }
    
    /** Clears the value of the '_2320CAS18AdjustmentAmount' field */
    public net.explorys.samhat.z12.r837.X837Ins_2320_CAS_ClaimLevelAdjustment.Builder clear2320CAS18AdjustmentAmount$1() {
      _2320CAS18AdjustmentAmount = null;
      fieldSetFlags()[17] = false;
      return this;
    }

    /** Gets the value of the '_2320CAS19AdjustmentQuantity' field */
    public java.lang.CharSequence get2320CAS19AdjustmentQuantity$1() {
      return _2320CAS19AdjustmentQuantity;
    }
    
    /** Sets the value of the '_2320CAS19AdjustmentQuantity' field */
    public net.explorys.samhat.z12.r837.X837Ins_2320_CAS_ClaimLevelAdjustment.Builder set2320CAS19AdjustmentQuantity$1(java.lang.CharSequence value) {
      validate(fields()[18], value);
      this._2320CAS19AdjustmentQuantity = value;
      fieldSetFlags()[18] = true;
      return this; 
    }
    
    /** Checks whether the '_2320CAS19AdjustmentQuantity' field has been set */
    public boolean has2320CAS19AdjustmentQuantity$1() {
      return fieldSetFlags()[18];
    }
    
    /** Clears the value of the '_2320CAS19AdjustmentQuantity' field */
    public net.explorys.samhat.z12.r837.X837Ins_2320_CAS_ClaimLevelAdjustment.Builder clear2320CAS19AdjustmentQuantity$1() {
      _2320CAS19AdjustmentQuantity = null;
      fieldSetFlags()[18] = false;
      return this;
    }

    @Override
    public X837Ins_2320_CAS_ClaimLevelAdjustment build() {
      try {
        X837Ins_2320_CAS_ClaimLevelAdjustment record = new X837Ins_2320_CAS_ClaimLevelAdjustment();
        record._2320CAS01ClaimAdjustmentGroupCode = fieldSetFlags()[0] ? this._2320CAS01ClaimAdjustmentGroupCode : (java.lang.CharSequence) defaultValue(fields()[0]);
        record._2320CAS02AdjustmentReasonCode = fieldSetFlags()[1] ? this._2320CAS02AdjustmentReasonCode : (java.lang.CharSequence) defaultValue(fields()[1]);
        record._2320CAS03AdjustmentAmount = fieldSetFlags()[2] ? this._2320CAS03AdjustmentAmount : (java.lang.CharSequence) defaultValue(fields()[2]);
        record._2320CAS04AdjustmentQuantity = fieldSetFlags()[3] ? this._2320CAS04AdjustmentQuantity : (java.lang.CharSequence) defaultValue(fields()[3]);
        record._2320CAS05AdjustmentReasonCode = fieldSetFlags()[4] ? this._2320CAS05AdjustmentReasonCode : (java.lang.CharSequence) defaultValue(fields()[4]);
        record._2320CAS06AdjustmentAmount = fieldSetFlags()[5] ? this._2320CAS06AdjustmentAmount : (java.lang.CharSequence) defaultValue(fields()[5]);
        record._2320CAS07AdjustmentQuantity = fieldSetFlags()[6] ? this._2320CAS07AdjustmentQuantity : (java.lang.CharSequence) defaultValue(fields()[6]);
        record._2320CAS08AdjustmentReasonCode = fieldSetFlags()[7] ? this._2320CAS08AdjustmentReasonCode : (java.lang.CharSequence) defaultValue(fields()[7]);
        record._2320CAS09AdjustmentAmount = fieldSetFlags()[8] ? this._2320CAS09AdjustmentAmount : (java.lang.CharSequence) defaultValue(fields()[8]);
        record._2320CAS10AdjustmentQuantity = fieldSetFlags()[9] ? this._2320CAS10AdjustmentQuantity : (java.lang.CharSequence) defaultValue(fields()[9]);
        record._2320CAS11AdjustmentReasonCode = fieldSetFlags()[10] ? this._2320CAS11AdjustmentReasonCode : (java.lang.CharSequence) defaultValue(fields()[10]);
        record._2320CAS12AdjustmentAmount = fieldSetFlags()[11] ? this._2320CAS12AdjustmentAmount : (java.lang.CharSequence) defaultValue(fields()[11]);
        record._2320CAS13AdjustmentQuantity = fieldSetFlags()[12] ? this._2320CAS13AdjustmentQuantity : (java.lang.CharSequence) defaultValue(fields()[12]);
        record._2320CAS14AdjustmentReasonCode = fieldSetFlags()[13] ? this._2320CAS14AdjustmentReasonCode : (java.lang.CharSequence) defaultValue(fields()[13]);
        record._2320CAS15AdjustmentAmount = fieldSetFlags()[14] ? this._2320CAS15AdjustmentAmount : (java.lang.CharSequence) defaultValue(fields()[14]);
        record._2320CAS16AdjustmentQuantity = fieldSetFlags()[15] ? this._2320CAS16AdjustmentQuantity : (java.lang.CharSequence) defaultValue(fields()[15]);
        record._2320CAS17AdjustmentReasonCode = fieldSetFlags()[16] ? this._2320CAS17AdjustmentReasonCode : (java.lang.CharSequence) defaultValue(fields()[16]);
        record._2320CAS18AdjustmentAmount = fieldSetFlags()[17] ? this._2320CAS18AdjustmentAmount : (java.lang.CharSequence) defaultValue(fields()[17]);
        record._2320CAS19AdjustmentQuantity = fieldSetFlags()[18] ? this._2320CAS19AdjustmentQuantity : (java.lang.CharSequence) defaultValue(fields()[18]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
