/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package net.explorys.samhat.z12.r837;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class X837Pro_2400_REF_MammographyCertificationNumber extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"X837Pro_2400_REF_MammographyCertificationNumber\",\"namespace\":\"net.explorys.samhat.z12.r837\",\"fields\":[{\"name\":\"_2400REF01ReferenceIdentificationQualifier\",\"type\":\"string\"},{\"name\":\"_2400REF02MammographyCertificationNumber\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence _2400REF01ReferenceIdentificationQualifier;
  @Deprecated public java.lang.CharSequence _2400REF02MammographyCertificationNumber;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public X837Pro_2400_REF_MammographyCertificationNumber() {}

  /**
   * All-args constructor.
   */
  public X837Pro_2400_REF_MammographyCertificationNumber(java.lang.CharSequence _2400REF01ReferenceIdentificationQualifier, java.lang.CharSequence _2400REF02MammographyCertificationNumber) {
    this._2400REF01ReferenceIdentificationQualifier = _2400REF01ReferenceIdentificationQualifier;
    this._2400REF02MammographyCertificationNumber = _2400REF02MammographyCertificationNumber;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return _2400REF01ReferenceIdentificationQualifier;
    case 1: return _2400REF02MammographyCertificationNumber;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: _2400REF01ReferenceIdentificationQualifier = (java.lang.CharSequence)value$; break;
    case 1: _2400REF02MammographyCertificationNumber = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the '_2400REF01ReferenceIdentificationQualifier' field.
   */
  public java.lang.CharSequence get2400REF01ReferenceIdentificationQualifier$1() {
    return _2400REF01ReferenceIdentificationQualifier;
  }

  /**
   * Sets the value of the '_2400REF01ReferenceIdentificationQualifier' field.
   * @param value the value to set.
   */
  public void set2400REF01ReferenceIdentificationQualifier$1(java.lang.CharSequence value) {
    this._2400REF01ReferenceIdentificationQualifier = value;
  }

  /**
   * Gets the value of the '_2400REF02MammographyCertificationNumber' field.
   */
  public java.lang.CharSequence get2400REF02MammographyCertificationNumber$1() {
    return _2400REF02MammographyCertificationNumber;
  }

  /**
   * Sets the value of the '_2400REF02MammographyCertificationNumber' field.
   * @param value the value to set.
   */
  public void set2400REF02MammographyCertificationNumber$1(java.lang.CharSequence value) {
    this._2400REF02MammographyCertificationNumber = value;
  }

  /** Creates a new X837Pro_2400_REF_MammographyCertificationNumber RecordBuilder */
  public static net.explorys.samhat.z12.r837.X837Pro_2400_REF_MammographyCertificationNumber.Builder newBuilder() {
    return new net.explorys.samhat.z12.r837.X837Pro_2400_REF_MammographyCertificationNumber.Builder();
  }
  
  /** Creates a new X837Pro_2400_REF_MammographyCertificationNumber RecordBuilder by copying an existing Builder */
  public static net.explorys.samhat.z12.r837.X837Pro_2400_REF_MammographyCertificationNumber.Builder newBuilder(net.explorys.samhat.z12.r837.X837Pro_2400_REF_MammographyCertificationNumber.Builder other) {
    return new net.explorys.samhat.z12.r837.X837Pro_2400_REF_MammographyCertificationNumber.Builder(other);
  }
  
  /** Creates a new X837Pro_2400_REF_MammographyCertificationNumber RecordBuilder by copying an existing X837Pro_2400_REF_MammographyCertificationNumber instance */
  public static net.explorys.samhat.z12.r837.X837Pro_2400_REF_MammographyCertificationNumber.Builder newBuilder(net.explorys.samhat.z12.r837.X837Pro_2400_REF_MammographyCertificationNumber other) {
    return new net.explorys.samhat.z12.r837.X837Pro_2400_REF_MammographyCertificationNumber.Builder(other);
  }
  
  /**
   * RecordBuilder for X837Pro_2400_REF_MammographyCertificationNumber instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<X837Pro_2400_REF_MammographyCertificationNumber>
    implements org.apache.avro.data.RecordBuilder<X837Pro_2400_REF_MammographyCertificationNumber> {

    private java.lang.CharSequence _2400REF01ReferenceIdentificationQualifier;
    private java.lang.CharSequence _2400REF02MammographyCertificationNumber;

    /** Creates a new Builder */
    private Builder() {
      super(net.explorys.samhat.z12.r837.X837Pro_2400_REF_MammographyCertificationNumber.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(net.explorys.samhat.z12.r837.X837Pro_2400_REF_MammographyCertificationNumber.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other._2400REF01ReferenceIdentificationQualifier)) {
        this._2400REF01ReferenceIdentificationQualifier = data().deepCopy(fields()[0].schema(), other._2400REF01ReferenceIdentificationQualifier);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other._2400REF02MammographyCertificationNumber)) {
        this._2400REF02MammographyCertificationNumber = data().deepCopy(fields()[1].schema(), other._2400REF02MammographyCertificationNumber);
        fieldSetFlags()[1] = true;
      }
    }
    
    /** Creates a Builder by copying an existing X837Pro_2400_REF_MammographyCertificationNumber instance */
    private Builder(net.explorys.samhat.z12.r837.X837Pro_2400_REF_MammographyCertificationNumber other) {
            super(net.explorys.samhat.z12.r837.X837Pro_2400_REF_MammographyCertificationNumber.SCHEMA$);
      if (isValidValue(fields()[0], other._2400REF01ReferenceIdentificationQualifier)) {
        this._2400REF01ReferenceIdentificationQualifier = data().deepCopy(fields()[0].schema(), other._2400REF01ReferenceIdentificationQualifier);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other._2400REF02MammographyCertificationNumber)) {
        this._2400REF02MammographyCertificationNumber = data().deepCopy(fields()[1].schema(), other._2400REF02MammographyCertificationNumber);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the '_2400REF01ReferenceIdentificationQualifier' field */
    public java.lang.CharSequence get2400REF01ReferenceIdentificationQualifier$1() {
      return _2400REF01ReferenceIdentificationQualifier;
    }
    
    /** Sets the value of the '_2400REF01ReferenceIdentificationQualifier' field */
    public net.explorys.samhat.z12.r837.X837Pro_2400_REF_MammographyCertificationNumber.Builder set2400REF01ReferenceIdentificationQualifier$1(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this._2400REF01ReferenceIdentificationQualifier = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the '_2400REF01ReferenceIdentificationQualifier' field has been set */
    public boolean has2400REF01ReferenceIdentificationQualifier$1() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the '_2400REF01ReferenceIdentificationQualifier' field */
    public net.explorys.samhat.z12.r837.X837Pro_2400_REF_MammographyCertificationNumber.Builder clear2400REF01ReferenceIdentificationQualifier$1() {
      _2400REF01ReferenceIdentificationQualifier = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the '_2400REF02MammographyCertificationNumber' field */
    public java.lang.CharSequence get2400REF02MammographyCertificationNumber$1() {
      return _2400REF02MammographyCertificationNumber;
    }
    
    /** Sets the value of the '_2400REF02MammographyCertificationNumber' field */
    public net.explorys.samhat.z12.r837.X837Pro_2400_REF_MammographyCertificationNumber.Builder set2400REF02MammographyCertificationNumber$1(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this._2400REF02MammographyCertificationNumber = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the '_2400REF02MammographyCertificationNumber' field has been set */
    public boolean has2400REF02MammographyCertificationNumber$1() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the '_2400REF02MammographyCertificationNumber' field */
    public net.explorys.samhat.z12.r837.X837Pro_2400_REF_MammographyCertificationNumber.Builder clear2400REF02MammographyCertificationNumber$1() {
      _2400REF02MammographyCertificationNumber = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public X837Pro_2400_REF_MammographyCertificationNumber build() {
      try {
        X837Pro_2400_REF_MammographyCertificationNumber record = new X837Pro_2400_REF_MammographyCertificationNumber();
        record._2400REF01ReferenceIdentificationQualifier = fieldSetFlags()[0] ? this._2400REF01ReferenceIdentificationQualifier : (java.lang.CharSequence) defaultValue(fields()[0]);
        record._2400REF02MammographyCertificationNumber = fieldSetFlags()[1] ? this._2400REF02MammographyCertificationNumber : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
