/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package net.explorys.samhat.z12.r837;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class X837Pro_2400_SV501_CompositeMedicalProcedureIdentifier extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"X837Pro_2400_SV501_CompositeMedicalProcedureIdentifier\",\"namespace\":\"net.explorys.samhat.z12.r837\",\"fields\":[{\"name\":\"_2400SV50101ProductServiceIDQualifier\",\"type\":\"string\"},{\"name\":\"_2400SV50102ProcedureCode\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence _2400SV50101ProductServiceIDQualifier;
  @Deprecated public java.lang.CharSequence _2400SV50102ProcedureCode;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public X837Pro_2400_SV501_CompositeMedicalProcedureIdentifier() {}

  /**
   * All-args constructor.
   */
  public X837Pro_2400_SV501_CompositeMedicalProcedureIdentifier(java.lang.CharSequence _2400SV50101ProductServiceIDQualifier, java.lang.CharSequence _2400SV50102ProcedureCode) {
    this._2400SV50101ProductServiceIDQualifier = _2400SV50101ProductServiceIDQualifier;
    this._2400SV50102ProcedureCode = _2400SV50102ProcedureCode;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return _2400SV50101ProductServiceIDQualifier;
    case 1: return _2400SV50102ProcedureCode;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: _2400SV50101ProductServiceIDQualifier = (java.lang.CharSequence)value$; break;
    case 1: _2400SV50102ProcedureCode = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the '_2400SV50101ProductServiceIDQualifier' field.
   */
  public java.lang.CharSequence get2400SV50101ProductServiceIDQualifier$1() {
    return _2400SV50101ProductServiceIDQualifier;
  }

  /**
   * Sets the value of the '_2400SV50101ProductServiceIDQualifier' field.
   * @param value the value to set.
   */
  public void set2400SV50101ProductServiceIDQualifier$1(java.lang.CharSequence value) {
    this._2400SV50101ProductServiceIDQualifier = value;
  }

  /**
   * Gets the value of the '_2400SV50102ProcedureCode' field.
   */
  public java.lang.CharSequence get2400SV50102ProcedureCode$1() {
    return _2400SV50102ProcedureCode;
  }

  /**
   * Sets the value of the '_2400SV50102ProcedureCode' field.
   * @param value the value to set.
   */
  public void set2400SV50102ProcedureCode$1(java.lang.CharSequence value) {
    this._2400SV50102ProcedureCode = value;
  }

  /** Creates a new X837Pro_2400_SV501_CompositeMedicalProcedureIdentifier RecordBuilder */
  public static net.explorys.samhat.z12.r837.X837Pro_2400_SV501_CompositeMedicalProcedureIdentifier.Builder newBuilder() {
    return new net.explorys.samhat.z12.r837.X837Pro_2400_SV501_CompositeMedicalProcedureIdentifier.Builder();
  }
  
  /** Creates a new X837Pro_2400_SV501_CompositeMedicalProcedureIdentifier RecordBuilder by copying an existing Builder */
  public static net.explorys.samhat.z12.r837.X837Pro_2400_SV501_CompositeMedicalProcedureIdentifier.Builder newBuilder(net.explorys.samhat.z12.r837.X837Pro_2400_SV501_CompositeMedicalProcedureIdentifier.Builder other) {
    return new net.explorys.samhat.z12.r837.X837Pro_2400_SV501_CompositeMedicalProcedureIdentifier.Builder(other);
  }
  
  /** Creates a new X837Pro_2400_SV501_CompositeMedicalProcedureIdentifier RecordBuilder by copying an existing X837Pro_2400_SV501_CompositeMedicalProcedureIdentifier instance */
  public static net.explorys.samhat.z12.r837.X837Pro_2400_SV501_CompositeMedicalProcedureIdentifier.Builder newBuilder(net.explorys.samhat.z12.r837.X837Pro_2400_SV501_CompositeMedicalProcedureIdentifier other) {
    return new net.explorys.samhat.z12.r837.X837Pro_2400_SV501_CompositeMedicalProcedureIdentifier.Builder(other);
  }
  
  /**
   * RecordBuilder for X837Pro_2400_SV501_CompositeMedicalProcedureIdentifier instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<X837Pro_2400_SV501_CompositeMedicalProcedureIdentifier>
    implements org.apache.avro.data.RecordBuilder<X837Pro_2400_SV501_CompositeMedicalProcedureIdentifier> {

    private java.lang.CharSequence _2400SV50101ProductServiceIDQualifier;
    private java.lang.CharSequence _2400SV50102ProcedureCode;

    /** Creates a new Builder */
    private Builder() {
      super(net.explorys.samhat.z12.r837.X837Pro_2400_SV501_CompositeMedicalProcedureIdentifier.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(net.explorys.samhat.z12.r837.X837Pro_2400_SV501_CompositeMedicalProcedureIdentifier.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other._2400SV50101ProductServiceIDQualifier)) {
        this._2400SV50101ProductServiceIDQualifier = data().deepCopy(fields()[0].schema(), other._2400SV50101ProductServiceIDQualifier);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other._2400SV50102ProcedureCode)) {
        this._2400SV50102ProcedureCode = data().deepCopy(fields()[1].schema(), other._2400SV50102ProcedureCode);
        fieldSetFlags()[1] = true;
      }
    }
    
    /** Creates a Builder by copying an existing X837Pro_2400_SV501_CompositeMedicalProcedureIdentifier instance */
    private Builder(net.explorys.samhat.z12.r837.X837Pro_2400_SV501_CompositeMedicalProcedureIdentifier other) {
            super(net.explorys.samhat.z12.r837.X837Pro_2400_SV501_CompositeMedicalProcedureIdentifier.SCHEMA$);
      if (isValidValue(fields()[0], other._2400SV50101ProductServiceIDQualifier)) {
        this._2400SV50101ProductServiceIDQualifier = data().deepCopy(fields()[0].schema(), other._2400SV50101ProductServiceIDQualifier);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other._2400SV50102ProcedureCode)) {
        this._2400SV50102ProcedureCode = data().deepCopy(fields()[1].schema(), other._2400SV50102ProcedureCode);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the '_2400SV50101ProductServiceIDQualifier' field */
    public java.lang.CharSequence get2400SV50101ProductServiceIDQualifier$1() {
      return _2400SV50101ProductServiceIDQualifier;
    }
    
    /** Sets the value of the '_2400SV50101ProductServiceIDQualifier' field */
    public net.explorys.samhat.z12.r837.X837Pro_2400_SV501_CompositeMedicalProcedureIdentifier.Builder set2400SV50101ProductServiceIDQualifier$1(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this._2400SV50101ProductServiceIDQualifier = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the '_2400SV50101ProductServiceIDQualifier' field has been set */
    public boolean has2400SV50101ProductServiceIDQualifier$1() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the '_2400SV50101ProductServiceIDQualifier' field */
    public net.explorys.samhat.z12.r837.X837Pro_2400_SV501_CompositeMedicalProcedureIdentifier.Builder clear2400SV50101ProductServiceIDQualifier$1() {
      _2400SV50101ProductServiceIDQualifier = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the '_2400SV50102ProcedureCode' field */
    public java.lang.CharSequence get2400SV50102ProcedureCode$1() {
      return _2400SV50102ProcedureCode;
    }
    
    /** Sets the value of the '_2400SV50102ProcedureCode' field */
    public net.explorys.samhat.z12.r837.X837Pro_2400_SV501_CompositeMedicalProcedureIdentifier.Builder set2400SV50102ProcedureCode$1(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this._2400SV50102ProcedureCode = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the '_2400SV50102ProcedureCode' field has been set */
    public boolean has2400SV50102ProcedureCode$1() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the '_2400SV50102ProcedureCode' field */
    public net.explorys.samhat.z12.r837.X837Pro_2400_SV501_CompositeMedicalProcedureIdentifier.Builder clear2400SV50102ProcedureCode$1() {
      _2400SV50102ProcedureCode = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public X837Pro_2400_SV501_CompositeMedicalProcedureIdentifier build() {
      try {
        X837Pro_2400_SV501_CompositeMedicalProcedureIdentifier record = new X837Pro_2400_SV501_CompositeMedicalProcedureIdentifier();
        record._2400SV50101ProductServiceIDQualifier = fieldSetFlags()[0] ? this._2400SV50101ProductServiceIDQualifier : (java.lang.CharSequence) defaultValue(fields()[0]);
        record._2400SV50102ProcedureCode = fieldSetFlags()[1] ? this._2400SV50102ProcedureCode : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
