/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package net.explorys.samhat.z12.r837;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class X837Pro_2440_FRM_SupportingDocumentation extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"X837Pro_2440_FRM_SupportingDocumentation\",\"namespace\":\"net.explorys.samhat.z12.r837\",\"fields\":[{\"name\":\"_2440FRM01QuestionNumberLetter\",\"type\":\"string\"},{\"name\":\"_2440FRM02QuestionResponse\",\"type\":\"string\"},{\"name\":\"_2440FRM03QuestionResponse\",\"type\":\"string\"},{\"name\":\"_2440FRM04QuestionResponse\",\"type\":\"string\"},{\"name\":\"_2440FRM05QuestionResponse\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence _2440FRM01QuestionNumberLetter;
  @Deprecated public java.lang.CharSequence _2440FRM02QuestionResponse;
  @Deprecated public java.lang.CharSequence _2440FRM03QuestionResponse;
  @Deprecated public java.lang.CharSequence _2440FRM04QuestionResponse;
  @Deprecated public java.lang.CharSequence _2440FRM05QuestionResponse;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public X837Pro_2440_FRM_SupportingDocumentation() {}

  /**
   * All-args constructor.
   */
  public X837Pro_2440_FRM_SupportingDocumentation(java.lang.CharSequence _2440FRM01QuestionNumberLetter, java.lang.CharSequence _2440FRM02QuestionResponse, java.lang.CharSequence _2440FRM03QuestionResponse, java.lang.CharSequence _2440FRM04QuestionResponse, java.lang.CharSequence _2440FRM05QuestionResponse) {
    this._2440FRM01QuestionNumberLetter = _2440FRM01QuestionNumberLetter;
    this._2440FRM02QuestionResponse = _2440FRM02QuestionResponse;
    this._2440FRM03QuestionResponse = _2440FRM03QuestionResponse;
    this._2440FRM04QuestionResponse = _2440FRM04QuestionResponse;
    this._2440FRM05QuestionResponse = _2440FRM05QuestionResponse;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return _2440FRM01QuestionNumberLetter;
    case 1: return _2440FRM02QuestionResponse;
    case 2: return _2440FRM03QuestionResponse;
    case 3: return _2440FRM04QuestionResponse;
    case 4: return _2440FRM05QuestionResponse;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: _2440FRM01QuestionNumberLetter = (java.lang.CharSequence)value$; break;
    case 1: _2440FRM02QuestionResponse = (java.lang.CharSequence)value$; break;
    case 2: _2440FRM03QuestionResponse = (java.lang.CharSequence)value$; break;
    case 3: _2440FRM04QuestionResponse = (java.lang.CharSequence)value$; break;
    case 4: _2440FRM05QuestionResponse = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the '_2440FRM01QuestionNumberLetter' field.
   */
  public java.lang.CharSequence get2440FRM01QuestionNumberLetter$1() {
    return _2440FRM01QuestionNumberLetter;
  }

  /**
   * Sets the value of the '_2440FRM01QuestionNumberLetter' field.
   * @param value the value to set.
   */
  public void set2440FRM01QuestionNumberLetter$1(java.lang.CharSequence value) {
    this._2440FRM01QuestionNumberLetter = value;
  }

  /**
   * Gets the value of the '_2440FRM02QuestionResponse' field.
   */
  public java.lang.CharSequence get2440FRM02QuestionResponse$1() {
    return _2440FRM02QuestionResponse;
  }

  /**
   * Sets the value of the '_2440FRM02QuestionResponse' field.
   * @param value the value to set.
   */
  public void set2440FRM02QuestionResponse$1(java.lang.CharSequence value) {
    this._2440FRM02QuestionResponse = value;
  }

  /**
   * Gets the value of the '_2440FRM03QuestionResponse' field.
   */
  public java.lang.CharSequence get2440FRM03QuestionResponse$1() {
    return _2440FRM03QuestionResponse;
  }

  /**
   * Sets the value of the '_2440FRM03QuestionResponse' field.
   * @param value the value to set.
   */
  public void set2440FRM03QuestionResponse$1(java.lang.CharSequence value) {
    this._2440FRM03QuestionResponse = value;
  }

  /**
   * Gets the value of the '_2440FRM04QuestionResponse' field.
   */
  public java.lang.CharSequence get2440FRM04QuestionResponse$1() {
    return _2440FRM04QuestionResponse;
  }

  /**
   * Sets the value of the '_2440FRM04QuestionResponse' field.
   * @param value the value to set.
   */
  public void set2440FRM04QuestionResponse$1(java.lang.CharSequence value) {
    this._2440FRM04QuestionResponse = value;
  }

  /**
   * Gets the value of the '_2440FRM05QuestionResponse' field.
   */
  public java.lang.CharSequence get2440FRM05QuestionResponse$1() {
    return _2440FRM05QuestionResponse;
  }

  /**
   * Sets the value of the '_2440FRM05QuestionResponse' field.
   * @param value the value to set.
   */
  public void set2440FRM05QuestionResponse$1(java.lang.CharSequence value) {
    this._2440FRM05QuestionResponse = value;
  }

  /** Creates a new X837Pro_2440_FRM_SupportingDocumentation RecordBuilder */
  public static net.explorys.samhat.z12.r837.X837Pro_2440_FRM_SupportingDocumentation.Builder newBuilder() {
    return new net.explorys.samhat.z12.r837.X837Pro_2440_FRM_SupportingDocumentation.Builder();
  }
  
  /** Creates a new X837Pro_2440_FRM_SupportingDocumentation RecordBuilder by copying an existing Builder */
  public static net.explorys.samhat.z12.r837.X837Pro_2440_FRM_SupportingDocumentation.Builder newBuilder(net.explorys.samhat.z12.r837.X837Pro_2440_FRM_SupportingDocumentation.Builder other) {
    return new net.explorys.samhat.z12.r837.X837Pro_2440_FRM_SupportingDocumentation.Builder(other);
  }
  
  /** Creates a new X837Pro_2440_FRM_SupportingDocumentation RecordBuilder by copying an existing X837Pro_2440_FRM_SupportingDocumentation instance */
  public static net.explorys.samhat.z12.r837.X837Pro_2440_FRM_SupportingDocumentation.Builder newBuilder(net.explorys.samhat.z12.r837.X837Pro_2440_FRM_SupportingDocumentation other) {
    return new net.explorys.samhat.z12.r837.X837Pro_2440_FRM_SupportingDocumentation.Builder(other);
  }
  
  /**
   * RecordBuilder for X837Pro_2440_FRM_SupportingDocumentation instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<X837Pro_2440_FRM_SupportingDocumentation>
    implements org.apache.avro.data.RecordBuilder<X837Pro_2440_FRM_SupportingDocumentation> {

    private java.lang.CharSequence _2440FRM01QuestionNumberLetter;
    private java.lang.CharSequence _2440FRM02QuestionResponse;
    private java.lang.CharSequence _2440FRM03QuestionResponse;
    private java.lang.CharSequence _2440FRM04QuestionResponse;
    private java.lang.CharSequence _2440FRM05QuestionResponse;

    /** Creates a new Builder */
    private Builder() {
      super(net.explorys.samhat.z12.r837.X837Pro_2440_FRM_SupportingDocumentation.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(net.explorys.samhat.z12.r837.X837Pro_2440_FRM_SupportingDocumentation.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other._2440FRM01QuestionNumberLetter)) {
        this._2440FRM01QuestionNumberLetter = data().deepCopy(fields()[0].schema(), other._2440FRM01QuestionNumberLetter);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other._2440FRM02QuestionResponse)) {
        this._2440FRM02QuestionResponse = data().deepCopy(fields()[1].schema(), other._2440FRM02QuestionResponse);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other._2440FRM03QuestionResponse)) {
        this._2440FRM03QuestionResponse = data().deepCopy(fields()[2].schema(), other._2440FRM03QuestionResponse);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other._2440FRM04QuestionResponse)) {
        this._2440FRM04QuestionResponse = data().deepCopy(fields()[3].schema(), other._2440FRM04QuestionResponse);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other._2440FRM05QuestionResponse)) {
        this._2440FRM05QuestionResponse = data().deepCopy(fields()[4].schema(), other._2440FRM05QuestionResponse);
        fieldSetFlags()[4] = true;
      }
    }
    
    /** Creates a Builder by copying an existing X837Pro_2440_FRM_SupportingDocumentation instance */
    private Builder(net.explorys.samhat.z12.r837.X837Pro_2440_FRM_SupportingDocumentation other) {
            super(net.explorys.samhat.z12.r837.X837Pro_2440_FRM_SupportingDocumentation.SCHEMA$);
      if (isValidValue(fields()[0], other._2440FRM01QuestionNumberLetter)) {
        this._2440FRM01QuestionNumberLetter = data().deepCopy(fields()[0].schema(), other._2440FRM01QuestionNumberLetter);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other._2440FRM02QuestionResponse)) {
        this._2440FRM02QuestionResponse = data().deepCopy(fields()[1].schema(), other._2440FRM02QuestionResponse);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other._2440FRM03QuestionResponse)) {
        this._2440FRM03QuestionResponse = data().deepCopy(fields()[2].schema(), other._2440FRM03QuestionResponse);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other._2440FRM04QuestionResponse)) {
        this._2440FRM04QuestionResponse = data().deepCopy(fields()[3].schema(), other._2440FRM04QuestionResponse);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other._2440FRM05QuestionResponse)) {
        this._2440FRM05QuestionResponse = data().deepCopy(fields()[4].schema(), other._2440FRM05QuestionResponse);
        fieldSetFlags()[4] = true;
      }
    }

    /** Gets the value of the '_2440FRM01QuestionNumberLetter' field */
    public java.lang.CharSequence get2440FRM01QuestionNumberLetter$1() {
      return _2440FRM01QuestionNumberLetter;
    }
    
    /** Sets the value of the '_2440FRM01QuestionNumberLetter' field */
    public net.explorys.samhat.z12.r837.X837Pro_2440_FRM_SupportingDocumentation.Builder set2440FRM01QuestionNumberLetter$1(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this._2440FRM01QuestionNumberLetter = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the '_2440FRM01QuestionNumberLetter' field has been set */
    public boolean has2440FRM01QuestionNumberLetter$1() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the '_2440FRM01QuestionNumberLetter' field */
    public net.explorys.samhat.z12.r837.X837Pro_2440_FRM_SupportingDocumentation.Builder clear2440FRM01QuestionNumberLetter$1() {
      _2440FRM01QuestionNumberLetter = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the '_2440FRM02QuestionResponse' field */
    public java.lang.CharSequence get2440FRM02QuestionResponse$1() {
      return _2440FRM02QuestionResponse;
    }
    
    /** Sets the value of the '_2440FRM02QuestionResponse' field */
    public net.explorys.samhat.z12.r837.X837Pro_2440_FRM_SupportingDocumentation.Builder set2440FRM02QuestionResponse$1(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this._2440FRM02QuestionResponse = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the '_2440FRM02QuestionResponse' field has been set */
    public boolean has2440FRM02QuestionResponse$1() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the '_2440FRM02QuestionResponse' field */
    public net.explorys.samhat.z12.r837.X837Pro_2440_FRM_SupportingDocumentation.Builder clear2440FRM02QuestionResponse$1() {
      _2440FRM02QuestionResponse = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the '_2440FRM03QuestionResponse' field */
    public java.lang.CharSequence get2440FRM03QuestionResponse$1() {
      return _2440FRM03QuestionResponse;
    }
    
    /** Sets the value of the '_2440FRM03QuestionResponse' field */
    public net.explorys.samhat.z12.r837.X837Pro_2440_FRM_SupportingDocumentation.Builder set2440FRM03QuestionResponse$1(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this._2440FRM03QuestionResponse = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the '_2440FRM03QuestionResponse' field has been set */
    public boolean has2440FRM03QuestionResponse$1() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the '_2440FRM03QuestionResponse' field */
    public net.explorys.samhat.z12.r837.X837Pro_2440_FRM_SupportingDocumentation.Builder clear2440FRM03QuestionResponse$1() {
      _2440FRM03QuestionResponse = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the '_2440FRM04QuestionResponse' field */
    public java.lang.CharSequence get2440FRM04QuestionResponse$1() {
      return _2440FRM04QuestionResponse;
    }
    
    /** Sets the value of the '_2440FRM04QuestionResponse' field */
    public net.explorys.samhat.z12.r837.X837Pro_2440_FRM_SupportingDocumentation.Builder set2440FRM04QuestionResponse$1(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this._2440FRM04QuestionResponse = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the '_2440FRM04QuestionResponse' field has been set */
    public boolean has2440FRM04QuestionResponse$1() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the '_2440FRM04QuestionResponse' field */
    public net.explorys.samhat.z12.r837.X837Pro_2440_FRM_SupportingDocumentation.Builder clear2440FRM04QuestionResponse$1() {
      _2440FRM04QuestionResponse = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the '_2440FRM05QuestionResponse' field */
    public java.lang.CharSequence get2440FRM05QuestionResponse$1() {
      return _2440FRM05QuestionResponse;
    }
    
    /** Sets the value of the '_2440FRM05QuestionResponse' field */
    public net.explorys.samhat.z12.r837.X837Pro_2440_FRM_SupportingDocumentation.Builder set2440FRM05QuestionResponse$1(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this._2440FRM05QuestionResponse = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the '_2440FRM05QuestionResponse' field has been set */
    public boolean has2440FRM05QuestionResponse$1() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the '_2440FRM05QuestionResponse' field */
    public net.explorys.samhat.z12.r837.X837Pro_2440_FRM_SupportingDocumentation.Builder clear2440FRM05QuestionResponse$1() {
      _2440FRM05QuestionResponse = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    public X837Pro_2440_FRM_SupportingDocumentation build() {
      try {
        X837Pro_2440_FRM_SupportingDocumentation record = new X837Pro_2440_FRM_SupportingDocumentation();
        record._2440FRM01QuestionNumberLetter = fieldSetFlags()[0] ? this._2440FRM01QuestionNumberLetter : (java.lang.CharSequence) defaultValue(fields()[0]);
        record._2440FRM02QuestionResponse = fieldSetFlags()[1] ? this._2440FRM02QuestionResponse : (java.lang.CharSequence) defaultValue(fields()[1]);
        record._2440FRM03QuestionResponse = fieldSetFlags()[2] ? this._2440FRM03QuestionResponse : (java.lang.CharSequence) defaultValue(fields()[2]);
        record._2440FRM04QuestionResponse = fieldSetFlags()[3] ? this._2440FRM04QuestionResponse : (java.lang.CharSequence) defaultValue(fields()[3]);
        record._2440FRM05QuestionResponse = fieldSetFlags()[4] ? this._2440FRM05QuestionResponse : (java.lang.CharSequence) defaultValue(fields()[4]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
