/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package net.explorys.samhat.z12.r837;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class X837Ins_2420B_NM1_OperatingPhysicianName extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"X837Ins_2420B_NM1_OperatingPhysicianName\",\"namespace\":\"net.explorys.samhat.z12.r837\",\"fields\":[{\"name\":\"_2420BNM101EntityIdentifierCode\",\"type\":\"string\"},{\"name\":\"_2420BNM102EntityTypeQualifier\",\"type\":\"string\"},{\"name\":\"_2420BNM103OperatingPhysicianLastName\",\"type\":\"string\"},{\"name\":\"_2420BNM104OperatingPhysicianFirstName\",\"type\":\"string\"},{\"name\":\"_2420BNM105OperatingPhysicanMiddleName\",\"type\":\"string\"},{\"name\":\"_2420BNM107OperatingPhysicianNameSuffix\",\"type\":\"string\"},{\"name\":\"_2420BNM108IdentificationCodeQualifier\",\"type\":\"string\"},{\"name\":\"_2420BNM109OperatingPhysicianPrimaryIdentifier\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence _2420BNM101EntityIdentifierCode;
  @Deprecated public java.lang.CharSequence _2420BNM102EntityTypeQualifier;
  @Deprecated public java.lang.CharSequence _2420BNM103OperatingPhysicianLastName;
  @Deprecated public java.lang.CharSequence _2420BNM104OperatingPhysicianFirstName;
  @Deprecated public java.lang.CharSequence _2420BNM105OperatingPhysicanMiddleName;
  @Deprecated public java.lang.CharSequence _2420BNM107OperatingPhysicianNameSuffix;
  @Deprecated public java.lang.CharSequence _2420BNM108IdentificationCodeQualifier;
  @Deprecated public java.lang.CharSequence _2420BNM109OperatingPhysicianPrimaryIdentifier;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public X837Ins_2420B_NM1_OperatingPhysicianName() {}

  /**
   * All-args constructor.
   */
  public X837Ins_2420B_NM1_OperatingPhysicianName(java.lang.CharSequence _2420BNM101EntityIdentifierCode, java.lang.CharSequence _2420BNM102EntityTypeQualifier, java.lang.CharSequence _2420BNM103OperatingPhysicianLastName, java.lang.CharSequence _2420BNM104OperatingPhysicianFirstName, java.lang.CharSequence _2420BNM105OperatingPhysicanMiddleName, java.lang.CharSequence _2420BNM107OperatingPhysicianNameSuffix, java.lang.CharSequence _2420BNM108IdentificationCodeQualifier, java.lang.CharSequence _2420BNM109OperatingPhysicianPrimaryIdentifier) {
    this._2420BNM101EntityIdentifierCode = _2420BNM101EntityIdentifierCode;
    this._2420BNM102EntityTypeQualifier = _2420BNM102EntityTypeQualifier;
    this._2420BNM103OperatingPhysicianLastName = _2420BNM103OperatingPhysicianLastName;
    this._2420BNM104OperatingPhysicianFirstName = _2420BNM104OperatingPhysicianFirstName;
    this._2420BNM105OperatingPhysicanMiddleName = _2420BNM105OperatingPhysicanMiddleName;
    this._2420BNM107OperatingPhysicianNameSuffix = _2420BNM107OperatingPhysicianNameSuffix;
    this._2420BNM108IdentificationCodeQualifier = _2420BNM108IdentificationCodeQualifier;
    this._2420BNM109OperatingPhysicianPrimaryIdentifier = _2420BNM109OperatingPhysicianPrimaryIdentifier;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return _2420BNM101EntityIdentifierCode;
    case 1: return _2420BNM102EntityTypeQualifier;
    case 2: return _2420BNM103OperatingPhysicianLastName;
    case 3: return _2420BNM104OperatingPhysicianFirstName;
    case 4: return _2420BNM105OperatingPhysicanMiddleName;
    case 5: return _2420BNM107OperatingPhysicianNameSuffix;
    case 6: return _2420BNM108IdentificationCodeQualifier;
    case 7: return _2420BNM109OperatingPhysicianPrimaryIdentifier;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: _2420BNM101EntityIdentifierCode = (java.lang.CharSequence)value$; break;
    case 1: _2420BNM102EntityTypeQualifier = (java.lang.CharSequence)value$; break;
    case 2: _2420BNM103OperatingPhysicianLastName = (java.lang.CharSequence)value$; break;
    case 3: _2420BNM104OperatingPhysicianFirstName = (java.lang.CharSequence)value$; break;
    case 4: _2420BNM105OperatingPhysicanMiddleName = (java.lang.CharSequence)value$; break;
    case 5: _2420BNM107OperatingPhysicianNameSuffix = (java.lang.CharSequence)value$; break;
    case 6: _2420BNM108IdentificationCodeQualifier = (java.lang.CharSequence)value$; break;
    case 7: _2420BNM109OperatingPhysicianPrimaryIdentifier = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the '_2420BNM101EntityIdentifierCode' field.
   */
  public java.lang.CharSequence get2420BNM101EntityIdentifierCode$1() {
    return _2420BNM101EntityIdentifierCode;
  }

  /**
   * Sets the value of the '_2420BNM101EntityIdentifierCode' field.
   * @param value the value to set.
   */
  public void set2420BNM101EntityIdentifierCode$1(java.lang.CharSequence value) {
    this._2420BNM101EntityIdentifierCode = value;
  }

  /**
   * Gets the value of the '_2420BNM102EntityTypeQualifier' field.
   */
  public java.lang.CharSequence get2420BNM102EntityTypeQualifier$1() {
    return _2420BNM102EntityTypeQualifier;
  }

  /**
   * Sets the value of the '_2420BNM102EntityTypeQualifier' field.
   * @param value the value to set.
   */
  public void set2420BNM102EntityTypeQualifier$1(java.lang.CharSequence value) {
    this._2420BNM102EntityTypeQualifier = value;
  }

  /**
   * Gets the value of the '_2420BNM103OperatingPhysicianLastName' field.
   */
  public java.lang.CharSequence get2420BNM103OperatingPhysicianLastName$1() {
    return _2420BNM103OperatingPhysicianLastName;
  }

  /**
   * Sets the value of the '_2420BNM103OperatingPhysicianLastName' field.
   * @param value the value to set.
   */
  public void set2420BNM103OperatingPhysicianLastName$1(java.lang.CharSequence value) {
    this._2420BNM103OperatingPhysicianLastName = value;
  }

  /**
   * Gets the value of the '_2420BNM104OperatingPhysicianFirstName' field.
   */
  public java.lang.CharSequence get2420BNM104OperatingPhysicianFirstName$1() {
    return _2420BNM104OperatingPhysicianFirstName;
  }

  /**
   * Sets the value of the '_2420BNM104OperatingPhysicianFirstName' field.
   * @param value the value to set.
   */
  public void set2420BNM104OperatingPhysicianFirstName$1(java.lang.CharSequence value) {
    this._2420BNM104OperatingPhysicianFirstName = value;
  }

  /**
   * Gets the value of the '_2420BNM105OperatingPhysicanMiddleName' field.
   */
  public java.lang.CharSequence get2420BNM105OperatingPhysicanMiddleName$1() {
    return _2420BNM105OperatingPhysicanMiddleName;
  }

  /**
   * Sets the value of the '_2420BNM105OperatingPhysicanMiddleName' field.
   * @param value the value to set.
   */
  public void set2420BNM105OperatingPhysicanMiddleName$1(java.lang.CharSequence value) {
    this._2420BNM105OperatingPhysicanMiddleName = value;
  }

  /**
   * Gets the value of the '_2420BNM107OperatingPhysicianNameSuffix' field.
   */
  public java.lang.CharSequence get2420BNM107OperatingPhysicianNameSuffix$1() {
    return _2420BNM107OperatingPhysicianNameSuffix;
  }

  /**
   * Sets the value of the '_2420BNM107OperatingPhysicianNameSuffix' field.
   * @param value the value to set.
   */
  public void set2420BNM107OperatingPhysicianNameSuffix$1(java.lang.CharSequence value) {
    this._2420BNM107OperatingPhysicianNameSuffix = value;
  }

  /**
   * Gets the value of the '_2420BNM108IdentificationCodeQualifier' field.
   */
  public java.lang.CharSequence get2420BNM108IdentificationCodeQualifier$1() {
    return _2420BNM108IdentificationCodeQualifier;
  }

  /**
   * Sets the value of the '_2420BNM108IdentificationCodeQualifier' field.
   * @param value the value to set.
   */
  public void set2420BNM108IdentificationCodeQualifier$1(java.lang.CharSequence value) {
    this._2420BNM108IdentificationCodeQualifier = value;
  }

  /**
   * Gets the value of the '_2420BNM109OperatingPhysicianPrimaryIdentifier' field.
   */
  public java.lang.CharSequence get2420BNM109OperatingPhysicianPrimaryIdentifier$1() {
    return _2420BNM109OperatingPhysicianPrimaryIdentifier;
  }

  /**
   * Sets the value of the '_2420BNM109OperatingPhysicianPrimaryIdentifier' field.
   * @param value the value to set.
   */
  public void set2420BNM109OperatingPhysicianPrimaryIdentifier$1(java.lang.CharSequence value) {
    this._2420BNM109OperatingPhysicianPrimaryIdentifier = value;
  }

  /** Creates a new X837Ins_2420B_NM1_OperatingPhysicianName RecordBuilder */
  public static net.explorys.samhat.z12.r837.X837Ins_2420B_NM1_OperatingPhysicianName.Builder newBuilder() {
    return new net.explorys.samhat.z12.r837.X837Ins_2420B_NM1_OperatingPhysicianName.Builder();
  }
  
  /** Creates a new X837Ins_2420B_NM1_OperatingPhysicianName RecordBuilder by copying an existing Builder */
  public static net.explorys.samhat.z12.r837.X837Ins_2420B_NM1_OperatingPhysicianName.Builder newBuilder(net.explorys.samhat.z12.r837.X837Ins_2420B_NM1_OperatingPhysicianName.Builder other) {
    return new net.explorys.samhat.z12.r837.X837Ins_2420B_NM1_OperatingPhysicianName.Builder(other);
  }
  
  /** Creates a new X837Ins_2420B_NM1_OperatingPhysicianName RecordBuilder by copying an existing X837Ins_2420B_NM1_OperatingPhysicianName instance */
  public static net.explorys.samhat.z12.r837.X837Ins_2420B_NM1_OperatingPhysicianName.Builder newBuilder(net.explorys.samhat.z12.r837.X837Ins_2420B_NM1_OperatingPhysicianName other) {
    return new net.explorys.samhat.z12.r837.X837Ins_2420B_NM1_OperatingPhysicianName.Builder(other);
  }
  
  /**
   * RecordBuilder for X837Ins_2420B_NM1_OperatingPhysicianName instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<X837Ins_2420B_NM1_OperatingPhysicianName>
    implements org.apache.avro.data.RecordBuilder<X837Ins_2420B_NM1_OperatingPhysicianName> {

    private java.lang.CharSequence _2420BNM101EntityIdentifierCode;
    private java.lang.CharSequence _2420BNM102EntityTypeQualifier;
    private java.lang.CharSequence _2420BNM103OperatingPhysicianLastName;
    private java.lang.CharSequence _2420BNM104OperatingPhysicianFirstName;
    private java.lang.CharSequence _2420BNM105OperatingPhysicanMiddleName;
    private java.lang.CharSequence _2420BNM107OperatingPhysicianNameSuffix;
    private java.lang.CharSequence _2420BNM108IdentificationCodeQualifier;
    private java.lang.CharSequence _2420BNM109OperatingPhysicianPrimaryIdentifier;

    /** Creates a new Builder */
    private Builder() {
      super(net.explorys.samhat.z12.r837.X837Ins_2420B_NM1_OperatingPhysicianName.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(net.explorys.samhat.z12.r837.X837Ins_2420B_NM1_OperatingPhysicianName.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other._2420BNM101EntityIdentifierCode)) {
        this._2420BNM101EntityIdentifierCode = data().deepCopy(fields()[0].schema(), other._2420BNM101EntityIdentifierCode);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other._2420BNM102EntityTypeQualifier)) {
        this._2420BNM102EntityTypeQualifier = data().deepCopy(fields()[1].schema(), other._2420BNM102EntityTypeQualifier);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other._2420BNM103OperatingPhysicianLastName)) {
        this._2420BNM103OperatingPhysicianLastName = data().deepCopy(fields()[2].schema(), other._2420BNM103OperatingPhysicianLastName);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other._2420BNM104OperatingPhysicianFirstName)) {
        this._2420BNM104OperatingPhysicianFirstName = data().deepCopy(fields()[3].schema(), other._2420BNM104OperatingPhysicianFirstName);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other._2420BNM105OperatingPhysicanMiddleName)) {
        this._2420BNM105OperatingPhysicanMiddleName = data().deepCopy(fields()[4].schema(), other._2420BNM105OperatingPhysicanMiddleName);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other._2420BNM107OperatingPhysicianNameSuffix)) {
        this._2420BNM107OperatingPhysicianNameSuffix = data().deepCopy(fields()[5].schema(), other._2420BNM107OperatingPhysicianNameSuffix);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other._2420BNM108IdentificationCodeQualifier)) {
        this._2420BNM108IdentificationCodeQualifier = data().deepCopy(fields()[6].schema(), other._2420BNM108IdentificationCodeQualifier);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other._2420BNM109OperatingPhysicianPrimaryIdentifier)) {
        this._2420BNM109OperatingPhysicianPrimaryIdentifier = data().deepCopy(fields()[7].schema(), other._2420BNM109OperatingPhysicianPrimaryIdentifier);
        fieldSetFlags()[7] = true;
      }
    }
    
    /** Creates a Builder by copying an existing X837Ins_2420B_NM1_OperatingPhysicianName instance */
    private Builder(net.explorys.samhat.z12.r837.X837Ins_2420B_NM1_OperatingPhysicianName other) {
            super(net.explorys.samhat.z12.r837.X837Ins_2420B_NM1_OperatingPhysicianName.SCHEMA$);
      if (isValidValue(fields()[0], other._2420BNM101EntityIdentifierCode)) {
        this._2420BNM101EntityIdentifierCode = data().deepCopy(fields()[0].schema(), other._2420BNM101EntityIdentifierCode);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other._2420BNM102EntityTypeQualifier)) {
        this._2420BNM102EntityTypeQualifier = data().deepCopy(fields()[1].schema(), other._2420BNM102EntityTypeQualifier);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other._2420BNM103OperatingPhysicianLastName)) {
        this._2420BNM103OperatingPhysicianLastName = data().deepCopy(fields()[2].schema(), other._2420BNM103OperatingPhysicianLastName);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other._2420BNM104OperatingPhysicianFirstName)) {
        this._2420BNM104OperatingPhysicianFirstName = data().deepCopy(fields()[3].schema(), other._2420BNM104OperatingPhysicianFirstName);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other._2420BNM105OperatingPhysicanMiddleName)) {
        this._2420BNM105OperatingPhysicanMiddleName = data().deepCopy(fields()[4].schema(), other._2420BNM105OperatingPhysicanMiddleName);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other._2420BNM107OperatingPhysicianNameSuffix)) {
        this._2420BNM107OperatingPhysicianNameSuffix = data().deepCopy(fields()[5].schema(), other._2420BNM107OperatingPhysicianNameSuffix);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other._2420BNM108IdentificationCodeQualifier)) {
        this._2420BNM108IdentificationCodeQualifier = data().deepCopy(fields()[6].schema(), other._2420BNM108IdentificationCodeQualifier);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other._2420BNM109OperatingPhysicianPrimaryIdentifier)) {
        this._2420BNM109OperatingPhysicianPrimaryIdentifier = data().deepCopy(fields()[7].schema(), other._2420BNM109OperatingPhysicianPrimaryIdentifier);
        fieldSetFlags()[7] = true;
      }
    }

    /** Gets the value of the '_2420BNM101EntityIdentifierCode' field */
    public java.lang.CharSequence get2420BNM101EntityIdentifierCode$1() {
      return _2420BNM101EntityIdentifierCode;
    }
    
    /** Sets the value of the '_2420BNM101EntityIdentifierCode' field */
    public net.explorys.samhat.z12.r837.X837Ins_2420B_NM1_OperatingPhysicianName.Builder set2420BNM101EntityIdentifierCode$1(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this._2420BNM101EntityIdentifierCode = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the '_2420BNM101EntityIdentifierCode' field has been set */
    public boolean has2420BNM101EntityIdentifierCode$1() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the '_2420BNM101EntityIdentifierCode' field */
    public net.explorys.samhat.z12.r837.X837Ins_2420B_NM1_OperatingPhysicianName.Builder clear2420BNM101EntityIdentifierCode$1() {
      _2420BNM101EntityIdentifierCode = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the '_2420BNM102EntityTypeQualifier' field */
    public java.lang.CharSequence get2420BNM102EntityTypeQualifier$1() {
      return _2420BNM102EntityTypeQualifier;
    }
    
    /** Sets the value of the '_2420BNM102EntityTypeQualifier' field */
    public net.explorys.samhat.z12.r837.X837Ins_2420B_NM1_OperatingPhysicianName.Builder set2420BNM102EntityTypeQualifier$1(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this._2420BNM102EntityTypeQualifier = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the '_2420BNM102EntityTypeQualifier' field has been set */
    public boolean has2420BNM102EntityTypeQualifier$1() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the '_2420BNM102EntityTypeQualifier' field */
    public net.explorys.samhat.z12.r837.X837Ins_2420B_NM1_OperatingPhysicianName.Builder clear2420BNM102EntityTypeQualifier$1() {
      _2420BNM102EntityTypeQualifier = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the '_2420BNM103OperatingPhysicianLastName' field */
    public java.lang.CharSequence get2420BNM103OperatingPhysicianLastName$1() {
      return _2420BNM103OperatingPhysicianLastName;
    }
    
    /** Sets the value of the '_2420BNM103OperatingPhysicianLastName' field */
    public net.explorys.samhat.z12.r837.X837Ins_2420B_NM1_OperatingPhysicianName.Builder set2420BNM103OperatingPhysicianLastName$1(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this._2420BNM103OperatingPhysicianLastName = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the '_2420BNM103OperatingPhysicianLastName' field has been set */
    public boolean has2420BNM103OperatingPhysicianLastName$1() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the '_2420BNM103OperatingPhysicianLastName' field */
    public net.explorys.samhat.z12.r837.X837Ins_2420B_NM1_OperatingPhysicianName.Builder clear2420BNM103OperatingPhysicianLastName$1() {
      _2420BNM103OperatingPhysicianLastName = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the '_2420BNM104OperatingPhysicianFirstName' field */
    public java.lang.CharSequence get2420BNM104OperatingPhysicianFirstName$1() {
      return _2420BNM104OperatingPhysicianFirstName;
    }
    
    /** Sets the value of the '_2420BNM104OperatingPhysicianFirstName' field */
    public net.explorys.samhat.z12.r837.X837Ins_2420B_NM1_OperatingPhysicianName.Builder set2420BNM104OperatingPhysicianFirstName$1(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this._2420BNM104OperatingPhysicianFirstName = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the '_2420BNM104OperatingPhysicianFirstName' field has been set */
    public boolean has2420BNM104OperatingPhysicianFirstName$1() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the '_2420BNM104OperatingPhysicianFirstName' field */
    public net.explorys.samhat.z12.r837.X837Ins_2420B_NM1_OperatingPhysicianName.Builder clear2420BNM104OperatingPhysicianFirstName$1() {
      _2420BNM104OperatingPhysicianFirstName = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the '_2420BNM105OperatingPhysicanMiddleName' field */
    public java.lang.CharSequence get2420BNM105OperatingPhysicanMiddleName$1() {
      return _2420BNM105OperatingPhysicanMiddleName;
    }
    
    /** Sets the value of the '_2420BNM105OperatingPhysicanMiddleName' field */
    public net.explorys.samhat.z12.r837.X837Ins_2420B_NM1_OperatingPhysicianName.Builder set2420BNM105OperatingPhysicanMiddleName$1(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this._2420BNM105OperatingPhysicanMiddleName = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the '_2420BNM105OperatingPhysicanMiddleName' field has been set */
    public boolean has2420BNM105OperatingPhysicanMiddleName$1() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the '_2420BNM105OperatingPhysicanMiddleName' field */
    public net.explorys.samhat.z12.r837.X837Ins_2420B_NM1_OperatingPhysicianName.Builder clear2420BNM105OperatingPhysicanMiddleName$1() {
      _2420BNM105OperatingPhysicanMiddleName = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the '_2420BNM107OperatingPhysicianNameSuffix' field */
    public java.lang.CharSequence get2420BNM107OperatingPhysicianNameSuffix$1() {
      return _2420BNM107OperatingPhysicianNameSuffix;
    }
    
    /** Sets the value of the '_2420BNM107OperatingPhysicianNameSuffix' field */
    public net.explorys.samhat.z12.r837.X837Ins_2420B_NM1_OperatingPhysicianName.Builder set2420BNM107OperatingPhysicianNameSuffix$1(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this._2420BNM107OperatingPhysicianNameSuffix = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the '_2420BNM107OperatingPhysicianNameSuffix' field has been set */
    public boolean has2420BNM107OperatingPhysicianNameSuffix$1() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the '_2420BNM107OperatingPhysicianNameSuffix' field */
    public net.explorys.samhat.z12.r837.X837Ins_2420B_NM1_OperatingPhysicianName.Builder clear2420BNM107OperatingPhysicianNameSuffix$1() {
      _2420BNM107OperatingPhysicianNameSuffix = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the '_2420BNM108IdentificationCodeQualifier' field */
    public java.lang.CharSequence get2420BNM108IdentificationCodeQualifier$1() {
      return _2420BNM108IdentificationCodeQualifier;
    }
    
    /** Sets the value of the '_2420BNM108IdentificationCodeQualifier' field */
    public net.explorys.samhat.z12.r837.X837Ins_2420B_NM1_OperatingPhysicianName.Builder set2420BNM108IdentificationCodeQualifier$1(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this._2420BNM108IdentificationCodeQualifier = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the '_2420BNM108IdentificationCodeQualifier' field has been set */
    public boolean has2420BNM108IdentificationCodeQualifier$1() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the '_2420BNM108IdentificationCodeQualifier' field */
    public net.explorys.samhat.z12.r837.X837Ins_2420B_NM1_OperatingPhysicianName.Builder clear2420BNM108IdentificationCodeQualifier$1() {
      _2420BNM108IdentificationCodeQualifier = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the '_2420BNM109OperatingPhysicianPrimaryIdentifier' field */
    public java.lang.CharSequence get2420BNM109OperatingPhysicianPrimaryIdentifier$1() {
      return _2420BNM109OperatingPhysicianPrimaryIdentifier;
    }
    
    /** Sets the value of the '_2420BNM109OperatingPhysicianPrimaryIdentifier' field */
    public net.explorys.samhat.z12.r837.X837Ins_2420B_NM1_OperatingPhysicianName.Builder set2420BNM109OperatingPhysicianPrimaryIdentifier$1(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this._2420BNM109OperatingPhysicianPrimaryIdentifier = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the '_2420BNM109OperatingPhysicianPrimaryIdentifier' field has been set */
    public boolean has2420BNM109OperatingPhysicianPrimaryIdentifier$1() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the '_2420BNM109OperatingPhysicianPrimaryIdentifier' field */
    public net.explorys.samhat.z12.r837.X837Ins_2420B_NM1_OperatingPhysicianName.Builder clear2420BNM109OperatingPhysicianPrimaryIdentifier$1() {
      _2420BNM109OperatingPhysicianPrimaryIdentifier = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    @Override
    public X837Ins_2420B_NM1_OperatingPhysicianName build() {
      try {
        X837Ins_2420B_NM1_OperatingPhysicianName record = new X837Ins_2420B_NM1_OperatingPhysicianName();
        record._2420BNM101EntityIdentifierCode = fieldSetFlags()[0] ? this._2420BNM101EntityIdentifierCode : (java.lang.CharSequence) defaultValue(fields()[0]);
        record._2420BNM102EntityTypeQualifier = fieldSetFlags()[1] ? this._2420BNM102EntityTypeQualifier : (java.lang.CharSequence) defaultValue(fields()[1]);
        record._2420BNM103OperatingPhysicianLastName = fieldSetFlags()[2] ? this._2420BNM103OperatingPhysicianLastName : (java.lang.CharSequence) defaultValue(fields()[2]);
        record._2420BNM104OperatingPhysicianFirstName = fieldSetFlags()[3] ? this._2420BNM104OperatingPhysicianFirstName : (java.lang.CharSequence) defaultValue(fields()[3]);
        record._2420BNM105OperatingPhysicanMiddleName = fieldSetFlags()[4] ? this._2420BNM105OperatingPhysicanMiddleName : (java.lang.CharSequence) defaultValue(fields()[4]);
        record._2420BNM107OperatingPhysicianNameSuffix = fieldSetFlags()[5] ? this._2420BNM107OperatingPhysicianNameSuffix : (java.lang.CharSequence) defaultValue(fields()[5]);
        record._2420BNM108IdentificationCodeQualifier = fieldSetFlags()[6] ? this._2420BNM108IdentificationCodeQualifier : (java.lang.CharSequence) defaultValue(fields()[6]);
        record._2420BNM109OperatingPhysicianPrimaryIdentifier = fieldSetFlags()[7] ? this._2420BNM109OperatingPhysicianPrimaryIdentifier : (java.lang.CharSequence) defaultValue(fields()[7]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
