/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package net.explorys.samhat.z12.r837;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class X837Ins_2330B_N4_OtherPayerCityStateZIPCode extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"X837Ins_2330B_N4_OtherPayerCityStateZIPCode\",\"namespace\":\"net.explorys.samhat.z12.r837\",\"fields\":[{\"name\":\"_2330BN401OtherPayerCityName\",\"type\":\"string\"},{\"name\":\"_2330BN402OtherPayerStateCode\",\"type\":\"string\"},{\"name\":\"_2330BN403OtherPayerPostalZoneOrZIPCode\",\"type\":\"string\"},{\"name\":\"_2330BN404CountryCode\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence _2330BN401OtherPayerCityName;
  @Deprecated public java.lang.CharSequence _2330BN402OtherPayerStateCode;
  @Deprecated public java.lang.CharSequence _2330BN403OtherPayerPostalZoneOrZIPCode;
  @Deprecated public java.lang.CharSequence _2330BN404CountryCode;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public X837Ins_2330B_N4_OtherPayerCityStateZIPCode() {}

  /**
   * All-args constructor.
   */
  public X837Ins_2330B_N4_OtherPayerCityStateZIPCode(java.lang.CharSequence _2330BN401OtherPayerCityName, java.lang.CharSequence _2330BN402OtherPayerStateCode, java.lang.CharSequence _2330BN403OtherPayerPostalZoneOrZIPCode, java.lang.CharSequence _2330BN404CountryCode) {
    this._2330BN401OtherPayerCityName = _2330BN401OtherPayerCityName;
    this._2330BN402OtherPayerStateCode = _2330BN402OtherPayerStateCode;
    this._2330BN403OtherPayerPostalZoneOrZIPCode = _2330BN403OtherPayerPostalZoneOrZIPCode;
    this._2330BN404CountryCode = _2330BN404CountryCode;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return _2330BN401OtherPayerCityName;
    case 1: return _2330BN402OtherPayerStateCode;
    case 2: return _2330BN403OtherPayerPostalZoneOrZIPCode;
    case 3: return _2330BN404CountryCode;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: _2330BN401OtherPayerCityName = (java.lang.CharSequence)value$; break;
    case 1: _2330BN402OtherPayerStateCode = (java.lang.CharSequence)value$; break;
    case 2: _2330BN403OtherPayerPostalZoneOrZIPCode = (java.lang.CharSequence)value$; break;
    case 3: _2330BN404CountryCode = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the '_2330BN401OtherPayerCityName' field.
   */
  public java.lang.CharSequence get2330BN401OtherPayerCityName$1() {
    return _2330BN401OtherPayerCityName;
  }

  /**
   * Sets the value of the '_2330BN401OtherPayerCityName' field.
   * @param value the value to set.
   */
  public void set2330BN401OtherPayerCityName$1(java.lang.CharSequence value) {
    this._2330BN401OtherPayerCityName = value;
  }

  /**
   * Gets the value of the '_2330BN402OtherPayerStateCode' field.
   */
  public java.lang.CharSequence get2330BN402OtherPayerStateCode$1() {
    return _2330BN402OtherPayerStateCode;
  }

  /**
   * Sets the value of the '_2330BN402OtherPayerStateCode' field.
   * @param value the value to set.
   */
  public void set2330BN402OtherPayerStateCode$1(java.lang.CharSequence value) {
    this._2330BN402OtherPayerStateCode = value;
  }

  /**
   * Gets the value of the '_2330BN403OtherPayerPostalZoneOrZIPCode' field.
   */
  public java.lang.CharSequence get2330BN403OtherPayerPostalZoneOrZIPCode$1() {
    return _2330BN403OtherPayerPostalZoneOrZIPCode;
  }

  /**
   * Sets the value of the '_2330BN403OtherPayerPostalZoneOrZIPCode' field.
   * @param value the value to set.
   */
  public void set2330BN403OtherPayerPostalZoneOrZIPCode$1(java.lang.CharSequence value) {
    this._2330BN403OtherPayerPostalZoneOrZIPCode = value;
  }

  /**
   * Gets the value of the '_2330BN404CountryCode' field.
   */
  public java.lang.CharSequence get2330BN404CountryCode$1() {
    return _2330BN404CountryCode;
  }

  /**
   * Sets the value of the '_2330BN404CountryCode' field.
   * @param value the value to set.
   */
  public void set2330BN404CountryCode$1(java.lang.CharSequence value) {
    this._2330BN404CountryCode = value;
  }

  /** Creates a new X837Ins_2330B_N4_OtherPayerCityStateZIPCode RecordBuilder */
  public static net.explorys.samhat.z12.r837.X837Ins_2330B_N4_OtherPayerCityStateZIPCode.Builder newBuilder() {
    return new net.explorys.samhat.z12.r837.X837Ins_2330B_N4_OtherPayerCityStateZIPCode.Builder();
  }
  
  /** Creates a new X837Ins_2330B_N4_OtherPayerCityStateZIPCode RecordBuilder by copying an existing Builder */
  public static net.explorys.samhat.z12.r837.X837Ins_2330B_N4_OtherPayerCityStateZIPCode.Builder newBuilder(net.explorys.samhat.z12.r837.X837Ins_2330B_N4_OtherPayerCityStateZIPCode.Builder other) {
    return new net.explorys.samhat.z12.r837.X837Ins_2330B_N4_OtherPayerCityStateZIPCode.Builder(other);
  }
  
  /** Creates a new X837Ins_2330B_N4_OtherPayerCityStateZIPCode RecordBuilder by copying an existing X837Ins_2330B_N4_OtherPayerCityStateZIPCode instance */
  public static net.explorys.samhat.z12.r837.X837Ins_2330B_N4_OtherPayerCityStateZIPCode.Builder newBuilder(net.explorys.samhat.z12.r837.X837Ins_2330B_N4_OtherPayerCityStateZIPCode other) {
    return new net.explorys.samhat.z12.r837.X837Ins_2330B_N4_OtherPayerCityStateZIPCode.Builder(other);
  }
  
  /**
   * RecordBuilder for X837Ins_2330B_N4_OtherPayerCityStateZIPCode instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<X837Ins_2330B_N4_OtherPayerCityStateZIPCode>
    implements org.apache.avro.data.RecordBuilder<X837Ins_2330B_N4_OtherPayerCityStateZIPCode> {

    private java.lang.CharSequence _2330BN401OtherPayerCityName;
    private java.lang.CharSequence _2330BN402OtherPayerStateCode;
    private java.lang.CharSequence _2330BN403OtherPayerPostalZoneOrZIPCode;
    private java.lang.CharSequence _2330BN404CountryCode;

    /** Creates a new Builder */
    private Builder() {
      super(net.explorys.samhat.z12.r837.X837Ins_2330B_N4_OtherPayerCityStateZIPCode.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(net.explorys.samhat.z12.r837.X837Ins_2330B_N4_OtherPayerCityStateZIPCode.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other._2330BN401OtherPayerCityName)) {
        this._2330BN401OtherPayerCityName = data().deepCopy(fields()[0].schema(), other._2330BN401OtherPayerCityName);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other._2330BN402OtherPayerStateCode)) {
        this._2330BN402OtherPayerStateCode = data().deepCopy(fields()[1].schema(), other._2330BN402OtherPayerStateCode);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other._2330BN403OtherPayerPostalZoneOrZIPCode)) {
        this._2330BN403OtherPayerPostalZoneOrZIPCode = data().deepCopy(fields()[2].schema(), other._2330BN403OtherPayerPostalZoneOrZIPCode);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other._2330BN404CountryCode)) {
        this._2330BN404CountryCode = data().deepCopy(fields()[3].schema(), other._2330BN404CountryCode);
        fieldSetFlags()[3] = true;
      }
    }
    
    /** Creates a Builder by copying an existing X837Ins_2330B_N4_OtherPayerCityStateZIPCode instance */
    private Builder(net.explorys.samhat.z12.r837.X837Ins_2330B_N4_OtherPayerCityStateZIPCode other) {
            super(net.explorys.samhat.z12.r837.X837Ins_2330B_N4_OtherPayerCityStateZIPCode.SCHEMA$);
      if (isValidValue(fields()[0], other._2330BN401OtherPayerCityName)) {
        this._2330BN401OtherPayerCityName = data().deepCopy(fields()[0].schema(), other._2330BN401OtherPayerCityName);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other._2330BN402OtherPayerStateCode)) {
        this._2330BN402OtherPayerStateCode = data().deepCopy(fields()[1].schema(), other._2330BN402OtherPayerStateCode);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other._2330BN403OtherPayerPostalZoneOrZIPCode)) {
        this._2330BN403OtherPayerPostalZoneOrZIPCode = data().deepCopy(fields()[2].schema(), other._2330BN403OtherPayerPostalZoneOrZIPCode);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other._2330BN404CountryCode)) {
        this._2330BN404CountryCode = data().deepCopy(fields()[3].schema(), other._2330BN404CountryCode);
        fieldSetFlags()[3] = true;
      }
    }

    /** Gets the value of the '_2330BN401OtherPayerCityName' field */
    public java.lang.CharSequence get2330BN401OtherPayerCityName$1() {
      return _2330BN401OtherPayerCityName;
    }
    
    /** Sets the value of the '_2330BN401OtherPayerCityName' field */
    public net.explorys.samhat.z12.r837.X837Ins_2330B_N4_OtherPayerCityStateZIPCode.Builder set2330BN401OtherPayerCityName$1(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this._2330BN401OtherPayerCityName = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the '_2330BN401OtherPayerCityName' field has been set */
    public boolean has2330BN401OtherPayerCityName$1() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the '_2330BN401OtherPayerCityName' field */
    public net.explorys.samhat.z12.r837.X837Ins_2330B_N4_OtherPayerCityStateZIPCode.Builder clear2330BN401OtherPayerCityName$1() {
      _2330BN401OtherPayerCityName = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the '_2330BN402OtherPayerStateCode' field */
    public java.lang.CharSequence get2330BN402OtherPayerStateCode$1() {
      return _2330BN402OtherPayerStateCode;
    }
    
    /** Sets the value of the '_2330BN402OtherPayerStateCode' field */
    public net.explorys.samhat.z12.r837.X837Ins_2330B_N4_OtherPayerCityStateZIPCode.Builder set2330BN402OtherPayerStateCode$1(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this._2330BN402OtherPayerStateCode = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the '_2330BN402OtherPayerStateCode' field has been set */
    public boolean has2330BN402OtherPayerStateCode$1() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the '_2330BN402OtherPayerStateCode' field */
    public net.explorys.samhat.z12.r837.X837Ins_2330B_N4_OtherPayerCityStateZIPCode.Builder clear2330BN402OtherPayerStateCode$1() {
      _2330BN402OtherPayerStateCode = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the '_2330BN403OtherPayerPostalZoneOrZIPCode' field */
    public java.lang.CharSequence get2330BN403OtherPayerPostalZoneOrZIPCode$1() {
      return _2330BN403OtherPayerPostalZoneOrZIPCode;
    }
    
    /** Sets the value of the '_2330BN403OtherPayerPostalZoneOrZIPCode' field */
    public net.explorys.samhat.z12.r837.X837Ins_2330B_N4_OtherPayerCityStateZIPCode.Builder set2330BN403OtherPayerPostalZoneOrZIPCode$1(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this._2330BN403OtherPayerPostalZoneOrZIPCode = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the '_2330BN403OtherPayerPostalZoneOrZIPCode' field has been set */
    public boolean has2330BN403OtherPayerPostalZoneOrZIPCode$1() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the '_2330BN403OtherPayerPostalZoneOrZIPCode' field */
    public net.explorys.samhat.z12.r837.X837Ins_2330B_N4_OtherPayerCityStateZIPCode.Builder clear2330BN403OtherPayerPostalZoneOrZIPCode$1() {
      _2330BN403OtherPayerPostalZoneOrZIPCode = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the '_2330BN404CountryCode' field */
    public java.lang.CharSequence get2330BN404CountryCode$1() {
      return _2330BN404CountryCode;
    }
    
    /** Sets the value of the '_2330BN404CountryCode' field */
    public net.explorys.samhat.z12.r837.X837Ins_2330B_N4_OtherPayerCityStateZIPCode.Builder set2330BN404CountryCode$1(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this._2330BN404CountryCode = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the '_2330BN404CountryCode' field has been set */
    public boolean has2330BN404CountryCode$1() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the '_2330BN404CountryCode' field */
    public net.explorys.samhat.z12.r837.X837Ins_2330B_N4_OtherPayerCityStateZIPCode.Builder clear2330BN404CountryCode$1() {
      _2330BN404CountryCode = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    public X837Ins_2330B_N4_OtherPayerCityStateZIPCode build() {
      try {
        X837Ins_2330B_N4_OtherPayerCityStateZIPCode record = new X837Ins_2330B_N4_OtherPayerCityStateZIPCode();
        record._2330BN401OtherPayerCityName = fieldSetFlags()[0] ? this._2330BN401OtherPayerCityName : (java.lang.CharSequence) defaultValue(fields()[0]);
        record._2330BN402OtherPayerStateCode = fieldSetFlags()[1] ? this._2330BN402OtherPayerStateCode : (java.lang.CharSequence) defaultValue(fields()[1]);
        record._2330BN403OtherPayerPostalZoneOrZIPCode = fieldSetFlags()[2] ? this._2330BN403OtherPayerPostalZoneOrZIPCode : (java.lang.CharSequence) defaultValue(fields()[2]);
        record._2330BN404CountryCode = fieldSetFlags()[3] ? this._2330BN404CountryCode : (java.lang.CharSequence) defaultValue(fields()[3]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
