/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package net.explorys.samhat.z12.r837;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class X837Pro_2400_CR2_SpinalManipulationServiceInformation extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"X837Pro_2400_CR2_SpinalManipulationServiceInformation\",\"namespace\":\"net.explorys.samhat.z12.r837\",\"fields\":[{\"name\":\"_2400CR208PatientConditionCode\",\"type\":\"string\"},{\"name\":\"_2400CR210PatientConditionDescription\",\"type\":\"string\"},{\"name\":\"_2400CR211PatientConditionDescription\",\"type\":\"string\"},{\"name\":\"_2400CR212XRayAvailabilityIndicator\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence _2400CR208PatientConditionCode;
  @Deprecated public java.lang.CharSequence _2400CR210PatientConditionDescription;
  @Deprecated public java.lang.CharSequence _2400CR211PatientConditionDescription;
  @Deprecated public java.lang.CharSequence _2400CR212XRayAvailabilityIndicator;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public X837Pro_2400_CR2_SpinalManipulationServiceInformation() {}

  /**
   * All-args constructor.
   */
  public X837Pro_2400_CR2_SpinalManipulationServiceInformation(java.lang.CharSequence _2400CR208PatientConditionCode, java.lang.CharSequence _2400CR210PatientConditionDescription, java.lang.CharSequence _2400CR211PatientConditionDescription, java.lang.CharSequence _2400CR212XRayAvailabilityIndicator) {
    this._2400CR208PatientConditionCode = _2400CR208PatientConditionCode;
    this._2400CR210PatientConditionDescription = _2400CR210PatientConditionDescription;
    this._2400CR211PatientConditionDescription = _2400CR211PatientConditionDescription;
    this._2400CR212XRayAvailabilityIndicator = _2400CR212XRayAvailabilityIndicator;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return _2400CR208PatientConditionCode;
    case 1: return _2400CR210PatientConditionDescription;
    case 2: return _2400CR211PatientConditionDescription;
    case 3: return _2400CR212XRayAvailabilityIndicator;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: _2400CR208PatientConditionCode = (java.lang.CharSequence)value$; break;
    case 1: _2400CR210PatientConditionDescription = (java.lang.CharSequence)value$; break;
    case 2: _2400CR211PatientConditionDescription = (java.lang.CharSequence)value$; break;
    case 3: _2400CR212XRayAvailabilityIndicator = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the '_2400CR208PatientConditionCode' field.
   */
  public java.lang.CharSequence get2400CR208PatientConditionCode$1() {
    return _2400CR208PatientConditionCode;
  }

  /**
   * Sets the value of the '_2400CR208PatientConditionCode' field.
   * @param value the value to set.
   */
  public void set2400CR208PatientConditionCode$1(java.lang.CharSequence value) {
    this._2400CR208PatientConditionCode = value;
  }

  /**
   * Gets the value of the '_2400CR210PatientConditionDescription' field.
   */
  public java.lang.CharSequence get2400CR210PatientConditionDescription$1() {
    return _2400CR210PatientConditionDescription;
  }

  /**
   * Sets the value of the '_2400CR210PatientConditionDescription' field.
   * @param value the value to set.
   */
  public void set2400CR210PatientConditionDescription$1(java.lang.CharSequence value) {
    this._2400CR210PatientConditionDescription = value;
  }

  /**
   * Gets the value of the '_2400CR211PatientConditionDescription' field.
   */
  public java.lang.CharSequence get2400CR211PatientConditionDescription$1() {
    return _2400CR211PatientConditionDescription;
  }

  /**
   * Sets the value of the '_2400CR211PatientConditionDescription' field.
   * @param value the value to set.
   */
  public void set2400CR211PatientConditionDescription$1(java.lang.CharSequence value) {
    this._2400CR211PatientConditionDescription = value;
  }

  /**
   * Gets the value of the '_2400CR212XRayAvailabilityIndicator' field.
   */
  public java.lang.CharSequence get2400CR212XRayAvailabilityIndicator$1() {
    return _2400CR212XRayAvailabilityIndicator;
  }

  /**
   * Sets the value of the '_2400CR212XRayAvailabilityIndicator' field.
   * @param value the value to set.
   */
  public void set2400CR212XRayAvailabilityIndicator$1(java.lang.CharSequence value) {
    this._2400CR212XRayAvailabilityIndicator = value;
  }

  /** Creates a new X837Pro_2400_CR2_SpinalManipulationServiceInformation RecordBuilder */
  public static net.explorys.samhat.z12.r837.X837Pro_2400_CR2_SpinalManipulationServiceInformation.Builder newBuilder() {
    return new net.explorys.samhat.z12.r837.X837Pro_2400_CR2_SpinalManipulationServiceInformation.Builder();
  }
  
  /** Creates a new X837Pro_2400_CR2_SpinalManipulationServiceInformation RecordBuilder by copying an existing Builder */
  public static net.explorys.samhat.z12.r837.X837Pro_2400_CR2_SpinalManipulationServiceInformation.Builder newBuilder(net.explorys.samhat.z12.r837.X837Pro_2400_CR2_SpinalManipulationServiceInformation.Builder other) {
    return new net.explorys.samhat.z12.r837.X837Pro_2400_CR2_SpinalManipulationServiceInformation.Builder(other);
  }
  
  /** Creates a new X837Pro_2400_CR2_SpinalManipulationServiceInformation RecordBuilder by copying an existing X837Pro_2400_CR2_SpinalManipulationServiceInformation instance */
  public static net.explorys.samhat.z12.r837.X837Pro_2400_CR2_SpinalManipulationServiceInformation.Builder newBuilder(net.explorys.samhat.z12.r837.X837Pro_2400_CR2_SpinalManipulationServiceInformation other) {
    return new net.explorys.samhat.z12.r837.X837Pro_2400_CR2_SpinalManipulationServiceInformation.Builder(other);
  }
  
  /**
   * RecordBuilder for X837Pro_2400_CR2_SpinalManipulationServiceInformation instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<X837Pro_2400_CR2_SpinalManipulationServiceInformation>
    implements org.apache.avro.data.RecordBuilder<X837Pro_2400_CR2_SpinalManipulationServiceInformation> {

    private java.lang.CharSequence _2400CR208PatientConditionCode;
    private java.lang.CharSequence _2400CR210PatientConditionDescription;
    private java.lang.CharSequence _2400CR211PatientConditionDescription;
    private java.lang.CharSequence _2400CR212XRayAvailabilityIndicator;

    /** Creates a new Builder */
    private Builder() {
      super(net.explorys.samhat.z12.r837.X837Pro_2400_CR2_SpinalManipulationServiceInformation.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(net.explorys.samhat.z12.r837.X837Pro_2400_CR2_SpinalManipulationServiceInformation.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other._2400CR208PatientConditionCode)) {
        this._2400CR208PatientConditionCode = data().deepCopy(fields()[0].schema(), other._2400CR208PatientConditionCode);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other._2400CR210PatientConditionDescription)) {
        this._2400CR210PatientConditionDescription = data().deepCopy(fields()[1].schema(), other._2400CR210PatientConditionDescription);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other._2400CR211PatientConditionDescription)) {
        this._2400CR211PatientConditionDescription = data().deepCopy(fields()[2].schema(), other._2400CR211PatientConditionDescription);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other._2400CR212XRayAvailabilityIndicator)) {
        this._2400CR212XRayAvailabilityIndicator = data().deepCopy(fields()[3].schema(), other._2400CR212XRayAvailabilityIndicator);
        fieldSetFlags()[3] = true;
      }
    }
    
    /** Creates a Builder by copying an existing X837Pro_2400_CR2_SpinalManipulationServiceInformation instance */
    private Builder(net.explorys.samhat.z12.r837.X837Pro_2400_CR2_SpinalManipulationServiceInformation other) {
            super(net.explorys.samhat.z12.r837.X837Pro_2400_CR2_SpinalManipulationServiceInformation.SCHEMA$);
      if (isValidValue(fields()[0], other._2400CR208PatientConditionCode)) {
        this._2400CR208PatientConditionCode = data().deepCopy(fields()[0].schema(), other._2400CR208PatientConditionCode);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other._2400CR210PatientConditionDescription)) {
        this._2400CR210PatientConditionDescription = data().deepCopy(fields()[1].schema(), other._2400CR210PatientConditionDescription);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other._2400CR211PatientConditionDescription)) {
        this._2400CR211PatientConditionDescription = data().deepCopy(fields()[2].schema(), other._2400CR211PatientConditionDescription);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other._2400CR212XRayAvailabilityIndicator)) {
        this._2400CR212XRayAvailabilityIndicator = data().deepCopy(fields()[3].schema(), other._2400CR212XRayAvailabilityIndicator);
        fieldSetFlags()[3] = true;
      }
    }

    /** Gets the value of the '_2400CR208PatientConditionCode' field */
    public java.lang.CharSequence get2400CR208PatientConditionCode$1() {
      return _2400CR208PatientConditionCode;
    }
    
    /** Sets the value of the '_2400CR208PatientConditionCode' field */
    public net.explorys.samhat.z12.r837.X837Pro_2400_CR2_SpinalManipulationServiceInformation.Builder set2400CR208PatientConditionCode$1(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this._2400CR208PatientConditionCode = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the '_2400CR208PatientConditionCode' field has been set */
    public boolean has2400CR208PatientConditionCode$1() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the '_2400CR208PatientConditionCode' field */
    public net.explorys.samhat.z12.r837.X837Pro_2400_CR2_SpinalManipulationServiceInformation.Builder clear2400CR208PatientConditionCode$1() {
      _2400CR208PatientConditionCode = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the '_2400CR210PatientConditionDescription' field */
    public java.lang.CharSequence get2400CR210PatientConditionDescription$1() {
      return _2400CR210PatientConditionDescription;
    }
    
    /** Sets the value of the '_2400CR210PatientConditionDescription' field */
    public net.explorys.samhat.z12.r837.X837Pro_2400_CR2_SpinalManipulationServiceInformation.Builder set2400CR210PatientConditionDescription$1(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this._2400CR210PatientConditionDescription = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the '_2400CR210PatientConditionDescription' field has been set */
    public boolean has2400CR210PatientConditionDescription$1() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the '_2400CR210PatientConditionDescription' field */
    public net.explorys.samhat.z12.r837.X837Pro_2400_CR2_SpinalManipulationServiceInformation.Builder clear2400CR210PatientConditionDescription$1() {
      _2400CR210PatientConditionDescription = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the '_2400CR211PatientConditionDescription' field */
    public java.lang.CharSequence get2400CR211PatientConditionDescription$1() {
      return _2400CR211PatientConditionDescription;
    }
    
    /** Sets the value of the '_2400CR211PatientConditionDescription' field */
    public net.explorys.samhat.z12.r837.X837Pro_2400_CR2_SpinalManipulationServiceInformation.Builder set2400CR211PatientConditionDescription$1(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this._2400CR211PatientConditionDescription = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the '_2400CR211PatientConditionDescription' field has been set */
    public boolean has2400CR211PatientConditionDescription$1() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the '_2400CR211PatientConditionDescription' field */
    public net.explorys.samhat.z12.r837.X837Pro_2400_CR2_SpinalManipulationServiceInformation.Builder clear2400CR211PatientConditionDescription$1() {
      _2400CR211PatientConditionDescription = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the '_2400CR212XRayAvailabilityIndicator' field */
    public java.lang.CharSequence get2400CR212XRayAvailabilityIndicator$1() {
      return _2400CR212XRayAvailabilityIndicator;
    }
    
    /** Sets the value of the '_2400CR212XRayAvailabilityIndicator' field */
    public net.explorys.samhat.z12.r837.X837Pro_2400_CR2_SpinalManipulationServiceInformation.Builder set2400CR212XRayAvailabilityIndicator$1(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this._2400CR212XRayAvailabilityIndicator = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the '_2400CR212XRayAvailabilityIndicator' field has been set */
    public boolean has2400CR212XRayAvailabilityIndicator$1() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the '_2400CR212XRayAvailabilityIndicator' field */
    public net.explorys.samhat.z12.r837.X837Pro_2400_CR2_SpinalManipulationServiceInformation.Builder clear2400CR212XRayAvailabilityIndicator$1() {
      _2400CR212XRayAvailabilityIndicator = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    public X837Pro_2400_CR2_SpinalManipulationServiceInformation build() {
      try {
        X837Pro_2400_CR2_SpinalManipulationServiceInformation record = new X837Pro_2400_CR2_SpinalManipulationServiceInformation();
        record._2400CR208PatientConditionCode = fieldSetFlags()[0] ? this._2400CR208PatientConditionCode : (java.lang.CharSequence) defaultValue(fields()[0]);
        record._2400CR210PatientConditionDescription = fieldSetFlags()[1] ? this._2400CR210PatientConditionDescription : (java.lang.CharSequence) defaultValue(fields()[1]);
        record._2400CR211PatientConditionDescription = fieldSetFlags()[2] ? this._2400CR211PatientConditionDescription : (java.lang.CharSequence) defaultValue(fields()[2]);
        record._2400CR212XRayAvailabilityIndicator = fieldSetFlags()[3] ? this._2400CR212XRayAvailabilityIndicator : (java.lang.CharSequence) defaultValue(fields()[3]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
