/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package net.explorys.samhat.z12.r837;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class X837Ins_2400_LX_ServiceLineNumber extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"X837Ins_2400_LX_ServiceLineNumber\",\"namespace\":\"net.explorys.samhat.z12.r837\",\"fields\":[{\"name\":\"_2400LX01AssignedNumber\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence _2400LX01AssignedNumber;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public X837Ins_2400_LX_ServiceLineNumber() {}

  /**
   * All-args constructor.
   */
  public X837Ins_2400_LX_ServiceLineNumber(java.lang.CharSequence _2400LX01AssignedNumber) {
    this._2400LX01AssignedNumber = _2400LX01AssignedNumber;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return _2400LX01AssignedNumber;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: _2400LX01AssignedNumber = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the '_2400LX01AssignedNumber' field.
   */
  public java.lang.CharSequence get2400LX01AssignedNumber$1() {
    return _2400LX01AssignedNumber;
  }

  /**
   * Sets the value of the '_2400LX01AssignedNumber' field.
   * @param value the value to set.
   */
  public void set2400LX01AssignedNumber$1(java.lang.CharSequence value) {
    this._2400LX01AssignedNumber = value;
  }

  /** Creates a new X837Ins_2400_LX_ServiceLineNumber RecordBuilder */
  public static net.explorys.samhat.z12.r837.X837Ins_2400_LX_ServiceLineNumber.Builder newBuilder() {
    return new net.explorys.samhat.z12.r837.X837Ins_2400_LX_ServiceLineNumber.Builder();
  }
  
  /** Creates a new X837Ins_2400_LX_ServiceLineNumber RecordBuilder by copying an existing Builder */
  public static net.explorys.samhat.z12.r837.X837Ins_2400_LX_ServiceLineNumber.Builder newBuilder(net.explorys.samhat.z12.r837.X837Ins_2400_LX_ServiceLineNumber.Builder other) {
    return new net.explorys.samhat.z12.r837.X837Ins_2400_LX_ServiceLineNumber.Builder(other);
  }
  
  /** Creates a new X837Ins_2400_LX_ServiceLineNumber RecordBuilder by copying an existing X837Ins_2400_LX_ServiceLineNumber instance */
  public static net.explorys.samhat.z12.r837.X837Ins_2400_LX_ServiceLineNumber.Builder newBuilder(net.explorys.samhat.z12.r837.X837Ins_2400_LX_ServiceLineNumber other) {
    return new net.explorys.samhat.z12.r837.X837Ins_2400_LX_ServiceLineNumber.Builder(other);
  }
  
  /**
   * RecordBuilder for X837Ins_2400_LX_ServiceLineNumber instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<X837Ins_2400_LX_ServiceLineNumber>
    implements org.apache.avro.data.RecordBuilder<X837Ins_2400_LX_ServiceLineNumber> {

    private java.lang.CharSequence _2400LX01AssignedNumber;

    /** Creates a new Builder */
    private Builder() {
      super(net.explorys.samhat.z12.r837.X837Ins_2400_LX_ServiceLineNumber.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(net.explorys.samhat.z12.r837.X837Ins_2400_LX_ServiceLineNumber.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other._2400LX01AssignedNumber)) {
        this._2400LX01AssignedNumber = data().deepCopy(fields()[0].schema(), other._2400LX01AssignedNumber);
        fieldSetFlags()[0] = true;
      }
    }
    
    /** Creates a Builder by copying an existing X837Ins_2400_LX_ServiceLineNumber instance */
    private Builder(net.explorys.samhat.z12.r837.X837Ins_2400_LX_ServiceLineNumber other) {
            super(net.explorys.samhat.z12.r837.X837Ins_2400_LX_ServiceLineNumber.SCHEMA$);
      if (isValidValue(fields()[0], other._2400LX01AssignedNumber)) {
        this._2400LX01AssignedNumber = data().deepCopy(fields()[0].schema(), other._2400LX01AssignedNumber);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the '_2400LX01AssignedNumber' field */
    public java.lang.CharSequence get2400LX01AssignedNumber$1() {
      return _2400LX01AssignedNumber;
    }
    
    /** Sets the value of the '_2400LX01AssignedNumber' field */
    public net.explorys.samhat.z12.r837.X837Ins_2400_LX_ServiceLineNumber.Builder set2400LX01AssignedNumber$1(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this._2400LX01AssignedNumber = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the '_2400LX01AssignedNumber' field has been set */
    public boolean has2400LX01AssignedNumber$1() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the '_2400LX01AssignedNumber' field */
    public net.explorys.samhat.z12.r837.X837Ins_2400_LX_ServiceLineNumber.Builder clear2400LX01AssignedNumber$1() {
      _2400LX01AssignedNumber = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public X837Ins_2400_LX_ServiceLineNumber build() {
      try {
        X837Ins_2400_LX_ServiceLineNumber record = new X837Ins_2400_LX_ServiceLineNumber();
        record._2400LX01AssignedNumber = fieldSetFlags()[0] ? this._2400LX01AssignedNumber : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
