/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package net.explorys.samhat.z12.r837;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class X837Pro_TransactionSetHeader extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"X837Pro_TransactionSetHeader\",\"namespace\":\"net.explorys.samhat.z12.r837\",\"fields\":[{\"name\":\"_TransactionSetIdentifierCode\",\"type\":\"string\"},{\"name\":\"_TransactionSetControlNumber\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence _TransactionSetIdentifierCode;
  @Deprecated public java.lang.CharSequence _TransactionSetControlNumber;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public X837Pro_TransactionSetHeader() {}

  /**
   * All-args constructor.
   */
  public X837Pro_TransactionSetHeader(java.lang.CharSequence _TransactionSetIdentifierCode, java.lang.CharSequence _TransactionSetControlNumber) {
    this._TransactionSetIdentifierCode = _TransactionSetIdentifierCode;
    this._TransactionSetControlNumber = _TransactionSetControlNumber;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return _TransactionSetIdentifierCode;
    case 1: return _TransactionSetControlNumber;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: _TransactionSetIdentifierCode = (java.lang.CharSequence)value$; break;
    case 1: _TransactionSetControlNumber = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the '_TransactionSetIdentifierCode' field.
   */
  public java.lang.CharSequence getTransactionSetIdentifierCode$1() {
    return _TransactionSetIdentifierCode;
  }

  /**
   * Sets the value of the '_TransactionSetIdentifierCode' field.
   * @param value the value to set.
   */
  public void setTransactionSetIdentifierCode$1(java.lang.CharSequence value) {
    this._TransactionSetIdentifierCode = value;
  }

  /**
   * Gets the value of the '_TransactionSetControlNumber' field.
   */
  public java.lang.CharSequence getTransactionSetControlNumber$1() {
    return _TransactionSetControlNumber;
  }

  /**
   * Sets the value of the '_TransactionSetControlNumber' field.
   * @param value the value to set.
   */
  public void setTransactionSetControlNumber$1(java.lang.CharSequence value) {
    this._TransactionSetControlNumber = value;
  }

  /** Creates a new X837Pro_TransactionSetHeader RecordBuilder */
  public static net.explorys.samhat.z12.r837.X837Pro_TransactionSetHeader.Builder newBuilder() {
    return new net.explorys.samhat.z12.r837.X837Pro_TransactionSetHeader.Builder();
  }
  
  /** Creates a new X837Pro_TransactionSetHeader RecordBuilder by copying an existing Builder */
  public static net.explorys.samhat.z12.r837.X837Pro_TransactionSetHeader.Builder newBuilder(net.explorys.samhat.z12.r837.X837Pro_TransactionSetHeader.Builder other) {
    return new net.explorys.samhat.z12.r837.X837Pro_TransactionSetHeader.Builder(other);
  }
  
  /** Creates a new X837Pro_TransactionSetHeader RecordBuilder by copying an existing X837Pro_TransactionSetHeader instance */
  public static net.explorys.samhat.z12.r837.X837Pro_TransactionSetHeader.Builder newBuilder(net.explorys.samhat.z12.r837.X837Pro_TransactionSetHeader other) {
    return new net.explorys.samhat.z12.r837.X837Pro_TransactionSetHeader.Builder(other);
  }
  
  /**
   * RecordBuilder for X837Pro_TransactionSetHeader instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<X837Pro_TransactionSetHeader>
    implements org.apache.avro.data.RecordBuilder<X837Pro_TransactionSetHeader> {

    private java.lang.CharSequence _TransactionSetIdentifierCode;
    private java.lang.CharSequence _TransactionSetControlNumber;

    /** Creates a new Builder */
    private Builder() {
      super(net.explorys.samhat.z12.r837.X837Pro_TransactionSetHeader.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(net.explorys.samhat.z12.r837.X837Pro_TransactionSetHeader.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other._TransactionSetIdentifierCode)) {
        this._TransactionSetIdentifierCode = data().deepCopy(fields()[0].schema(), other._TransactionSetIdentifierCode);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other._TransactionSetControlNumber)) {
        this._TransactionSetControlNumber = data().deepCopy(fields()[1].schema(), other._TransactionSetControlNumber);
        fieldSetFlags()[1] = true;
      }
    }
    
    /** Creates a Builder by copying an existing X837Pro_TransactionSetHeader instance */
    private Builder(net.explorys.samhat.z12.r837.X837Pro_TransactionSetHeader other) {
            super(net.explorys.samhat.z12.r837.X837Pro_TransactionSetHeader.SCHEMA$);
      if (isValidValue(fields()[0], other._TransactionSetIdentifierCode)) {
        this._TransactionSetIdentifierCode = data().deepCopy(fields()[0].schema(), other._TransactionSetIdentifierCode);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other._TransactionSetControlNumber)) {
        this._TransactionSetControlNumber = data().deepCopy(fields()[1].schema(), other._TransactionSetControlNumber);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the '_TransactionSetIdentifierCode' field */
    public java.lang.CharSequence getTransactionSetIdentifierCode$1() {
      return _TransactionSetIdentifierCode;
    }
    
    /** Sets the value of the '_TransactionSetIdentifierCode' field */
    public net.explorys.samhat.z12.r837.X837Pro_TransactionSetHeader.Builder setTransactionSetIdentifierCode$1(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this._TransactionSetIdentifierCode = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the '_TransactionSetIdentifierCode' field has been set */
    public boolean hasTransactionSetIdentifierCode$1() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the '_TransactionSetIdentifierCode' field */
    public net.explorys.samhat.z12.r837.X837Pro_TransactionSetHeader.Builder clearTransactionSetIdentifierCode$1() {
      _TransactionSetIdentifierCode = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the '_TransactionSetControlNumber' field */
    public java.lang.CharSequence getTransactionSetControlNumber$1() {
      return _TransactionSetControlNumber;
    }
    
    /** Sets the value of the '_TransactionSetControlNumber' field */
    public net.explorys.samhat.z12.r837.X837Pro_TransactionSetHeader.Builder setTransactionSetControlNumber$1(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this._TransactionSetControlNumber = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the '_TransactionSetControlNumber' field has been set */
    public boolean hasTransactionSetControlNumber$1() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the '_TransactionSetControlNumber' field */
    public net.explorys.samhat.z12.r837.X837Pro_TransactionSetHeader.Builder clearTransactionSetControlNumber$1() {
      _TransactionSetControlNumber = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public X837Pro_TransactionSetHeader build() {
      try {
        X837Pro_TransactionSetHeader record = new X837Pro_TransactionSetHeader();
        record._TransactionSetIdentifierCode = fieldSetFlags()[0] ? this._TransactionSetIdentifierCode : (java.lang.CharSequence) defaultValue(fields()[0]);
        record._TransactionSetControlNumber = fieldSetFlags()[1] ? this._TransactionSetControlNumber : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
